export * from "./types";
export {
  IFCPC_META,
  IFCPC_NOMENCLATURE,
  IFCPC_SECTIONS,
  IFCPC_SIGNS,
  getIfcpcSectionById,
  getIfcpcSignById,
  getIfcpcSignsBySection,
  validateIfcpcNomenclature,
} from "./knowledge/nomenclature";
export { assessIfcpcExam, finalizeIfcpcExam } from "./engine/assess-exam";
export {
  calculateCinRisk,
  getCinRiskCoefficients,
  getCinRiskModelMeta,
  CIN_RISK_FORMULA,
  CinRiskCalculatorInputSchema,
  CalculateCinRiskBodySchema,
  CalculateCinRiskResponseSchema,
  CIN_RISK_JSON_SCHEMA,
  type CinRiskCalculatorInput,
  type CinRiskCalculatorResult,
  type CinRiskProbability,
  type CalculateCinRiskBody,
} from "./cin-risk";
export type {
  BethesdaCytology,
  HpvStatus,
  PriorBiopsyResult,
  PriorCinTreatmentHistory,
  CinRiskOutcome,
  CinRiskTier,
} from "./cin-risk/types";
export {
  CreateIfcpcExamBodySchema,
  IfcpcAdequacyIdSchema,
  IfcpcBiopsyUrgencySchema,
  IfcpcClinicalContextSchema,
  IfcpcColposcopyExamSchema,
  IfcpcExamAssessmentSchema,
  IfcpcExamResponseSchema,
  IfcpcFindingSignIdSchema,
  IfcpcNomenclatureResponseSchema,
  IfcpcOverallImpressionSchema,
  IfcpcQuadrantNoteSchema,
  IfcpcQuadrantSchema,
  IfcpcScjVisibilityIdSchema,
  IfcpcSignIdSchema,
  IfcpcSignLookupQuerySchema,
  IfcpcTransformationZoneIdSchema,
  UpdateIfcpcExamBodySchema,
  type CreateIfcpcExamBody,
  type IfcpcColposcopyExamInput,
  type IfcpcNomenclatureResponse,
  type IfcpcSignLookupQuery,
  type UpdateIfcpcExamBody,
} from "./schema/api-schema";
