import type { FetalDopplerCase } from "./types";

export const FETAL_DOPPLER_CASES: FetalDopplerCase[] = [
  {
    id: "case-b01-normal-five",
    level: "beginner",
    title: "Норма · все 5 позиций",
    clinicalScenario: "Первичный скрининг 12+3. Женщина 32 года, без факторов риска. КТР и ТВП в норме.",
    ultrasoundFindings: [
      "Эмбрион живой, КТР соответствует сроку.",
      "ТВП 1.8 мм (< 95th).",
      "4CV симметричен, перегородки intact.",
    ],
    dopplerFindings: [
      "4CV + 3VT color — наполнение симметричное.",
      "VP: PI 1.05, A-wave antegrade.",
      "2 пупочные артерии у пузыря, 3-сосудистая пуповина.",
      "UTA PI R 1.4, L 1.5, mean 1.45.",
    ],
    interpretation: "Все допплер-позиции в пределах ожидаемого для 12 нед. Маркеры не повышают риск изолированно.",
    finalDiagnosis: "Нормальный расширенный допплер-протокол I триместра.",
    teachingPoints: [
      "Документируйте все 5 позиций даже при норме — baseline для последующих визитов.",
      "Mean UTA PI обязателен в протокол.",
    ],
  },
  {
    id: "case-b02-bladder-level",
    level: "beginner",
    title: "Идентификация уровня пузыря",
    clinicalScenario: "Стажёр не видит вторую пупочную артерию. Срез выше уровня iliac bifurcation.",
    ultrasoundFindings: ["Мочевой пузырь не в кадре.", "Видны только iliac vessels."],
    dopplerFindings: ["Color на iliac — высокоскоростной arterial flow."],
    interpretation: "Неверный уровень. Опустить датчик до поперечного среза с пузырём.",
    finalDiagnosis: "Техническая ошибка уровня — не SUA.",
    teachingPoints: ["Пузырь = якорь для 3-vessel cord.", "Не интерпретировать SUA без пузыря в кадре."],
  },
  {
    id: "case-b03-alara",
    level: "beginner",
    title: "ALARA на практике",
    clinicalScenario: "Длительное сканирование VP: color box на весь abdomen, TI 1.2.",
    ultrasoundFindings: ["Плод активный, срез нестабилен."],
    dopplerFindings: ["Многократные попытки PI, время > 12 мин."],
    interpretation: "Нарушение ALARA. Уменьшить box, сократить время, повторить при успокоении плода.",
    finalDiagnosis: "Протокольная ошибка безопасности — исправима.",
    teachingPoints: ["TI ≤ 1.0 контроль обязателен.", "Color box = только целевая структура."],
  },
  {
    id: "case-i01-sua",
    level: "intermediate",
    title: "Единственная пупочная артерия",
    clinicalScenario: "12+1, скрининг. Одна артерия по бокам пузыря, вена центральна.",
    ultrasoundFindings: ["SUA на color.", "Сердце: 4CV без gross-асимметрии."],
    dopplerFindings: ["VP PI 1.12, A-wave antegrade.", "UTA mean PI 1.6."],
    interpretation: "SUA — маркер для расширенного обследования. Оценить кардиологию, генетику по протоколу.",
    finalDiagnosis: "Single umbilical artery — скрининговая находка.",
    teachingPoints: [
      "SUA не редкость (~1%); документировать и вести по локальному протоколу.",
      "Повторное сканирование для подтверждения.",
    ],
  },
  {
    id: "case-i02-dv-pi",
    level: "intermediate",
    title: "Повышенный PI венозного протока",
    clinicalScenario: "13+0, увеличенное ТВП 3.2 мм, запрос расширенного протокола.",
    ultrasoundFindings: ["ТВП > 99th для срока.", "Носовая кость present."],
    dopplerFindings: ["VP PI 1.38 (> 95th).", "A-wave antegrade.", "TR trace positive."],
    interpretation: "Комбинация маркеров повышает риск. Не изолировать PI без ТВП и анамнеза.",
    finalDiagnosis: "Расширенный скрининг: множественные маркеры I триместра.",
    teachingPoints: ["PI VP интерпретировать с перцентилями FMF.", "Консультация MFM / генетика."],
  },
  {
    id: "case-i03-uta-notching",
    level: "intermediate",
    title: "PI маточных артерий · elevated",
    clinicalScenario: "11+6, ожирение I ст, первый визит скрининга PE.",
    ultrasoundFindings: ["Живой эмбрион, морфология без gross-аномалий."],
    dopplerFindings: ["UTA PI R 2.8, L 2.6, mean 2.7.", "Early diastolic notch bilaterally."],
    interpretation: "Повышенный mean PI + notch — компонент PE risk calculator.",
    finalDiagnosis: "Altered uteroplacental flow — скрининг PE.",
    teachingPoints: ["Mean PI = (R+L)/2.", "Угол < 30°, 3 цикла."],
  },
  {
    id: "case-a01-reversed-a",
    level: "advanced",
    title: "Reversed A-wave венозного протока",
    clinicalScenario: "12+5, подозрение на хромосомную аномалию, гипопlasia носовой кости.",
    ultrasoundFindings: ["Отсутствие носовой кости.", "ТВП 4.1 мм."],
    dopplerFindings: ["VP: reversed A-wave.", "PI 1.55.", "TR moderate."],
    interpretation: "Reversed A-wave — сильный функциональный маркер. Комбинированная стратегия MFM.",
    finalDiagnosis: "High-risk extended first-trimester profile.",
    teachingPoints: [
      "Reversed A-wave — не единственный критерий инвазивной диагностики.",
      "Документировать все маркеры для мультидисциплинарного консенсуса.",
    ],
  },
  {
    id: "case-a02-omphalocele",
    level: "advanced",
    title: "Омфaloцеле vs физиологическая грыжа",
    clinicalScenario: "11+2, выпячивание в epigastrium. Сомнение: физиология или патология?",
    ultrasoundFindings: ["Срединное выпячивание без free loops.", "Пуповина к вершине."],
    dopplerFindings: ["Color: пуповина входит в мешок.", "Сердце: 4CV без gross-CHD на этом сроке."],
    interpretation: "До 11 нед — осторожность. Повтор 12+ для окончательной классификации.",
    finalDiagnosis: "Подозрение на omphalocele — контроль 12+ нед.",
    teachingPoints: ["Физиологическая грыжа до 11 нед.", "Color на пуповину обязателен."],
  },
  {
    id: "case-a03-gastroschisis",
    level: "advanced",
    title: "Гастроshisis · paraumbilical defect",
    clinicalScenario: "13+1, free loops справа от пуповины, нет мембраны.",
    ultrasoundFindings: ["Paraumbilical defect справа.", "Кишечник вне брюшной полости."],
    dopplerFindings: ["Color: пуповина medial to defect.", "UTA и VP в норме."],
    interpretation: "Классическая картина gastroschisis. Планирование родов в перинatal центре.",
    finalDiagnosis: "Gastroschisis — confirmed.",
    teachingPoints: [
      "Без мембраны + free loops = gastroschisis.",
      "Отличие от omphalocele — midline + membrane.",
    ],
  },
];

export function casesByLevel(level: FetalDopplerCase["level"]): FetalDopplerCase[] {
  return FETAL_DOPPLER_CASES.filter((c) => c.level === level);
}
