import type { QuizBank } from "@/lib/education/quiz-bank-types";

export const FETAL_DOPPLER_QUIZ_BANK: QuizBank = {
  topic: "Doppler Ultrasound in the First Trimester (11–14 Weeks)",
  version: "1.0.0",
  lastReviewed: "2026-06-20",
  sources: [
    {
      id: "sitar-2026",
      title: "М.В. Ситарская — допплер I триместра (ultrasoundoc.com)",
      year: 2026,
    },
    {
      id: "fmf",
      title: "FMF First Trimester Screening Protocol",
      year: 2024,
    },
    {
      id: "medvedev",
      title: "Медведев М.В. Пренатальная эхография — нормы PI",
      year: 2016,
    },
  ],
  questions: [
    {
      id: "fd-q01",
      category: "safety",
      level: "student",
      question: "Какой максимальный TI рекомендуется при допплере I триместра?",
      options: ["0.5", "1.0", "2.0", "3.0"],
      correctIndex: 1,
      explanation: "TI ≤ 1.0 — контроль на экране аппарата (ALARA).",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q02",
      category: "safety",
      level: "doctor",
      question: "Правильный порядок работы с допплером:",
      options: [
        "Сразу спектральный допплер на всю область",
        "Color → короткий pulsed Doppler",
        "Только M-mode",
        "CW Doppler первым шагом",
      ],
      correctIndex: 1,
      explanation: "Сначала Color для локализации, затем короткий импульсный допплер для измерения.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q03",
      category: "protocol",
      level: "student",
      question: "Сколько допплер-позиций в расширенном протоколе?",
      options: ["3", "4", "5", "7"],
      correctIndex: 2,
      explanation: "5 позиций: сердце, VP, пуповина, кольцо (при подозрении), маточные артерии.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q04",
      category: "ductus-venosus",
      level: "doctor",
      question: "Рекомендуемый sample volume для PI венозного протока:",
      options: ["0.1 mm", "~1 mm", "~5 mm", "10 mm"],
      correctIndex: 1,
      explanation: "Пробный объём ~1 mm; не захватывать печёночные вены.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q05",
      category: "ductus-venosus",
      level: "doctor",
      question: "A-wave венозного протока в норме:",
      options: ["Reversed", "Absent", "Antegrade", "Biphasic only in II trimester"],
      correctIndex: 2,
      explanation: "В норме A-wave antegrade (не реверсная).",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q06",
      category: "umbilical",
      level: "student",
      question: "Якорная структура для идентификации пупочных артерий:",
      options: ["Placenta", "Fetal bladder", "Stomach", "Spine"],
      correctIndex: 1,
      explanation: "Поперечный срез таза на уровне мочевого пузыря — 2 артерии по бокам.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q07",
      category: "uterine",
      level: "doctor",
      question: "Максимальный угол инсонации для PI маточных артерий:",
      options: ["15°", "30°", "45°", "60°"],
      correctIndex: 1,
      explanation: "Угол инсонации < 30° для корректного PI.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q08",
      category: "uterine",
      level: "doctor",
      question: "Mean PI маточных артерий рассчитывается как:",
      options: ["Max(R, L)", "Min(R, L)", "(R + L) / 2", "R × L"],
      correctIndex: 2,
      explanation: "Среднее арифметическое правой и левой PI.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q09",
      category: "abdominal-wall",
      level: "student",
      question: "Физиологическая срединная грыжа кишечника возможна до:",
      options: ["8 нед", "11 нед", "16 нед", "20 нед"],
      correctIndex: 1,
      explanation: "До 11 нед — физиологическая грыжа; окончательная оценка кольца после 12 нед.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q10",
      category: "abdominal-wall",
      level: "doctor",
      question: "Gastroschisis vs omphalocele — верно:",
      options: [
        "Omphalocele — paraumbilical без мемbranous sac",
        "Gastroschisis — midline с мемbranous sac",
        "Gastroschisis — free loops, usually no membrane",
        "Оба всегда midline",
      ],
      correctIndex: 2,
      explanation: "Gastroschisis: paraumbilical, free loops, без мемbranous sac.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q11",
      category: "fetal-heart",
      level: "student",
      question: "Цель допплера сердца в I тримestre:",
      options: [
        "Полная fetal echocardiography",
        "Быстрая проверка наполнения и базовой анатомии",
        "Only CW Doppler aorta",
        "TR обязателен каждому",
      ],
      correctIndex: 1,
      explanation: "Не полная ЭхоКГ — быстрая функциональная проверка 4CV/3VT.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q12",
      category: "pitfalls",
      level: "doctor",
      question: "Частая ошибка при PI венозного протока:",
      options: [
        "Sample volume слишком мал",
        "Перепутали с печёночными венами",
        "Использовали только B-mode",
        "Слишком короткое время сканирования",
      ],
      correctIndex: 1,
      explanation: "Печёnoчные вены дают неверную кривую и PI.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q13",
      category: "protocol",
      level: "doctor",
      question: "Позиция «пупочное кольцо» выполняется:",
      options: [
        "Всегда на каждом визите",
        "Только при подозрении на gastroschisis/omphalocele",
        "Только после 20 нед",
        "Только transvaginally",
      ],
      correctIndex: 1,
      explanation: "Условная позиция — при подозрении на дефект АБС.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q14",
      category: "safety",
      level: "student",
      question: "До 11 недель рекомендуется:",
      options: [
        "Routine spectral Doppler all patients",
        "Avoid unnecessary spectral Doppler",
        "Only uterine artery PI",
        "CW Doppler mandatory",
      ],
      correctIndex: 1,
      explanation: "До 11 нед — избегать необоснованного спектрального допплера.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q15",
      category: "interpretation",
      level: "doctor",
      question: "Один допплер-маркер без контекста ведёт к:",
      options: ["Always terminate", "False alarms / wrong management", "No effect", "Mandatory amnio"],
      correctIndex: 1,
      explanation: "Интерпретация только в контексте КТР, ТВП, анатомии, анамнеза.",
      sourceId: "sitar-2026",
    },
    {
      id: "fd-q16",
      category: "uterine",
      level: "student",
      question: "Сколько стабильных комплексов записывать для PI маточных артерий?",
      options: ["1", "3", "10", "20"],
      correctIndex: 1,
      explanation: "3 похожих последовательных комплекса.",
      sourceId: "sitar-2026",
    },
  ],
};

export const FETAL_DOPPLER_ORAL_QUESTIONS = [
  "Опишите маршрут 5 допплер-позиций за 2 минуты.",
  "Как отличить венозный проток от печёночной вены на color?",
  "Когда можно окончательно классифицировать omphalocele vs physiological hernia?",
  "Перечислите ALARA-меры при допплере I тримestra.",
  "Как рассчитать mean PI маточных артерий и зачем он нужен?",
] as const;
