import type { EvidenceEntry } from "../types";

const FMF = "https://fetalmedicine.org/";
const FMF_CALC = "https://courses.fetalmedicine.com/calculator/";

const linkFmf = [{ label: "FMF · скрининги", href: "/assistant/fmf" }] as const;

/** Дополнительные темы FMF (калькуляторы, маркеры, II–III триместр, близнецы). */
export const FMF_ADDITIONAL_EVIDENCE: EvidenceEntry[] = [
  // ——— Риски I триместра ———
  {
    id: "fmf-risk-t21-t18-t13",
    shelf: "us-fmf",
    title: "Риск T21 / T18 / T13 (FMF calculator)",
    summary:
      "FMF First Trimester Screening Program рассчитывает patient-specific риск трисомий по NT, биохимии, материнским факторам и доп. маркерам; пороги cut-off — по локальному протоколу.",
    clinicalPearl: "В калькулятор вводят только valid NT и CRL; MoM PAPP-A/β-hCG — после лабораторной верификации.",
    excerpt: "FMF software integrates ultrasound and biochemistry to estimate trisomy 21, 18 and 13 risks.",
    tier: 1,
    source: { label: "FMF First Trimester Screening Program", organization: "FMF", year: 2023, url: FMF },
    tags: ["T21", "T18", "T13", "риск", "калькулятор", "FMF", "трисомия"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-increased-nt-normal-karyotype",
    shelf: "us-fmf",
    title: "Увеличенный NT · нормальная кариотип",
    summary:
      "Изолированное ↑NT при normal karyotype связано с риском структурных/cardiac аномалий, ЗРП, miscarriage — нужен expert fetal echo и II тримester scan.",
    clinicalPearl: "Сообщайте семье: NT — не только про хромосомы; план — fetal echocardiography + anomaly scan.",
    excerpt: "Increased NT with normal karyotype warrants detailed cardiac and anatomical follow-up.",
    tier: 1,
    source: { label: "FMF · Increased NT with normal karyotype", organization: "FMF", year: 2023, url: FMF },
    tags: ["NT", "увеличенный", "кариотип", "echo", "структурные"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-map",
    shelf: "us-fmf",
    title: "Среднее артериальное давление (MAP)",
    summary:
      "MAP на I скрининге — компонент FMF-алгоритма преэклампсии; измеряют по протоколу FMF (both arms, proper cuff).",
    clinicalPearl: "MAP вводят в FMF software вместе с UtA PI и maternal history для combined PE risk.",
    excerpt: "Mean arterial pressure at 11–13 weeks contributes to hypertensive disorder risk models.",
    tier: 1,
    source: { label: "FMF · MAP protocol", organization: "FMF", year: 2023, url: `${FMF_CALC}map` },
    tags: ["MAP", "давление", "преэклампсия", "скрининг"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-plgf",
    shelf: "us-fmf",
    title: "PlGF · MoM на 11–13 нед",
    summary:
      "PlGF MoM (validated assay) улучшает stratification преэклампсии в FMF-модели; используют только зарегистрированные анализаторы.",
    clinicalPearl: "PlGF + UtA PI + MAP + history — в FMF preeclampsia calculator; не смешивать assays.",
    excerpt: "First-trimester PlGF MoM is integrated in FMF pre-eclampsia screening when assay is validated.",
    tier: 1,
    source: { label: "FMF PlGF MoM calculator", organization: "FMF", year: 2023, url: `${FMF_CALC}plgf` },
    tags: ["PlGF", "MoM", "преэклампсия", "биохимия"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-mom-biochemistry",
    shelf: "us-fmf",
    title: "MoM · PAPP-A и free β-hCG",
    summary:
      "Лаборатория выдаёт MoM с коррекцией weight, smoking, diabetes, IVF, ethnicity; некорректные MoM → неверный риск T21.",
    clinicalPearl: "Проверьте в протоколе: CRL на момент заборa, singleton, корректная раса/вес в лабораторной карте.",
    excerpt: "MoM conversion for PAPP-A and free β-hCG requires maternal and gestational metadata.",
    tier: 1,
    source: { label: "FMF · maternal serum biochemistry", organization: "FMF", year: 2023, url: FMF },
    tags: ["MoM", "PAPP-A", "β-hCG", "лаборатория", "скрининг"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-megacystis",
    shelf: "us-fmf",
    title: "Мегacystis · мочевой пузырь ≥7 мм",
    summary:
      "Пузырный размер ≥7 мм на 11–13+6 нед — major marker; ассоциир с aneuploidy и obstructive uropathy; нужна кариотипизация и expert US.",
    clinicalPearl: "Измеряют inner-inner diameter; repeat через 1–2 нед для transient megacystis vs persistent.",
    excerpt: "First-trimester megacystis is a major marker requiring karyotype and urological evaluation.",
    tier: 1,
    source: { label: "FMF · major markers", organization: "FMF", year: 2023, url: FMF },
    tags: ["мегacystis", "мочевой пузырь", "маркер", "I скрининг"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-exomphalos",
    shelf: "us-fmf",
    title: "Omphalocele · I триместр",
    summary:
      "Omphalocele на I скрининге — major marker (↑ risk T18/T13); отличать от physiological midgut herniation до ~11 нед.",
    clinicalPearl: "Документируйте содержимое sac и size; referral fetal medicine / genetics.",
    excerpt: "First-trimester exomphalos is a major marker associated with chromosomal abnormalities.",
    tier: 1,
    source: { label: "FMF · major markers", organization: "FMF", year: 2023, url: FMF },
    tags: ["exomphalos", "omphalocele", "маркер", "T18"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-diaphragmatic-hernia",
    shelf: "us-fmf",
    title: "Diaphragmatic hernia · I триместр",
    summary:
      "Ранний CDH — major marker с высокой перinatal mortality; lung size и liver position — прогностические на later scans.",
    clinicalPearl: "Suspected CDH → referral Fetal Medicine Center; обсуждение postnatal pathway.",
    excerpt: "First-trimester detection of congenital diaphragmatic hernia requires specialized counseling.",
    tier: 1,
    source: { label: "FMF · major markers", organization: "FMF", year: 2023, url: FMF },
    tags: ["CDH", "диафрагмальная", "грыжа", "маркер"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-iv-ventricle",
    shelf: "us-fmf",
    title: "IV желудочек · задний размер (ПЗР)",
    summary:
      "ПЗР IV желудочка на I скрининге — brain marker в FMF/Медvedev; ↑ размер → риск открытой NT defects / aneuploidy correlation.",
    clinicalPearl: "Измеряют atria level, transventricular plane; перцентili по таблицам Медvedev (Прил. 11).",
    excerpt: "Posterior brain translucency / IV ventricle measurements contribute to first-trimester brain assessment.",
    tier: 1,
    source: { label: "FMF / Medvedev · brain markers", organization: "FMF · ISUOG", year: 2023 },
    tags: ["IV желудочек", "ПЗР", "мозг", "I скрининг", "Медvedev"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-assisted-conception",
    shelf: "us-fmf",
    title: "Вспомогательные репродуктивные технологии (ВРТ)",
    summary:
      "IVF/ovulation drugs меняют prior risk T21 и PE в FMF algorithms — обязательно указывать method of conception в software.",
    clinicalPearl: "Singleton после IVF ≠ spontaneous risk; twin после SET — chorionicity first.",
    excerpt: "Assisted conception modifies prior risks in FMF first-trimester screening calculations.",
    tier: 1,
    source: { label: "FMF · assisted conception", organization: "FMF", year: 2023, url: FMF },
    tags: ["IVF", "ВРТ", "ЭКО", "риск", "FMF"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-fhr-first-trimester-screening",
    shelf: "us-fmf",
    title: "ЧСС на I скрининге (11–13+6)",
    summary:
      "Abnormal FHR на I скрининге — soft marker; bradycardia/tachycardia → repeat scan и cardiac assessment по контексту.",
    clinicalPearl: "Записывайте FHR после NT plane; artifact от maternal vessels исключить.",
    excerpt: "Fetal heart rate assessment is part of the comprehensive 11–13+6 weeks scan.",
    tier: 1,
    source: { label: "FMF · fetal heart rate", organization: "FMF", year: 2023, url: FMF },
    tags: ["ЧСС", "FHR", "I скрининг", "11 нед"],
    relatedLinks: [...linkFmf],
  },

  // ——— FMF online calculators ———
  {
    id: "fmf-calc-preeclampsia",
    shelf: "us-fmf",
    title: "Калькулятор преэклампсии (FMF)",
    summary:
      "FMF preeclampsia calculator: maternal factors + MAP + UtA PI (+ PlGF при доступности) → risk early/term PE; high risk → aspirin 150 mg nocte с 11–14 нед по протоколу.",
    clinicalPearl: "Результат — вероятность, не диагноз; тактика aspirin — по локальным КР и shared decision.",
    excerpt: "FMF pre-eclampsia screening combines maternal history, MAP and Doppler for risk estimation.",
    tier: 1,
    source: { label: "FMF preeclampsia calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}pe` },
    tags: ["преэклампсия", "калькулятор", "aspirin", "аспirin", "FMF"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-calc-preterm",
    shelf: "us-fmf",
    title: "Калькулятор преждевременных родов (FMF)",
    summary:
      "FMF preterm calculator: CL + history + maternal factors → risk birth <34 / <37 weeks; high risk → progesterone/cervical cerclage по показаниям.",
    clinicalPearl: "TV CL только trained operators; funneling документировать отдельно.",
    excerpt: "FMF spontaneous preterm birth model integrates cervical length and obstetric history.",
    tier: 1,
    source: { label: "FMF preterm delivery calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}preterm` },
    tags: ["преждевременные", "preterm", "CL", "калькулятор", "34 нед"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-calc-sga",
    shelf: "us-fmf",
    title: "Калькулятор SGA / ЗРП риска (FMF)",
    summary:
      "FMF SGA calculator stratifies risk small-for-gestational-age using UtA PI, maternal factors, biometry trends.",
    clinicalPearl: "Сочетайте с serial EFW и UA/MCA Doppler в III триместре.",
    excerpt: "FMF SGA screening identifies pregnancies at increased risk of fetal growth restriction.",
    tier: 1,
    source: { label: "FMF SGA calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}sga` },
    tags: ["SGA", "ЗРП", "FGR", "калькулятор", "рост"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-calc-gdm",
    shelf: "us-fmf",
    title: "Калькулятор ГСД (FMF)",
    summary:
      "FMF gestational diabetes risk calculator использует maternal characteristics для stratification; не заменяет OGTT по срокам.",
    clinicalPearl: "High risk → раннее Glucose challenge / lifestyle counseling по локальному протоколу.",
    excerpt: "FMF gestational diabetes calculator estimates risk based on maternal demographic factors.",
    tier: 1,
    source: { label: "FMF gestational diabetes calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}gestational_diabetes` },
    tags: ["ГСД", "GDM", "диабет", "калькулятор", "беременность"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-calc-macrosomia",
    shelf: "us-fmf",
    title: "Калькулятор macrosomia (FMF)",
    summary:
      "FMF macrosomia calculator оценивает риск крупного плода; сочетать с AC/EFW перцентилями и maternal diabetes status.",
    clinicalPearl: "Macrosomia risk ≠ indication для early delivery без других факторов.",
    excerpt: "FMF macrosomia model integrates maternal and fetal parameters for birth weight risk.",
    tier: 1,
    source: { label: "FMF macrosomia calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}macrosomia` },
    tags: ["macrosomia", "макросомия", "крупный плод", "калькулятор"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-calc-stillbirth",
    shelf: "us-fmf",
    title: "Калькулятор stillbirth (FMF)",
    summary:
      "FMF stillbirth risk calculator — population-based stratification; abnormal Doppler/EFW повышают post-test risk.",
    clinicalPearl: "Используйте как adjunct к клинике; high risk → enhanced surveillance protocol.",
    excerpt: "FMF stillbirth screening tool combines maternal and pregnancy factors.",
    tier: 1,
    source: { label: "FMF stillbirth calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}stillbirth` },
    tags: ["stillbirth", "внутриутробная гибель", "риск", "калькулятор"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-calc-miscarriage",
    shelf: "us-fmf",
    title: "Калькулятор miscarriage (FMF)",
    summary:
      "FMF miscarriage calculator оценивает риск потери беременности на ранних сроках по maternal factors и US findings.",
    clinicalPearl: "Не заменяет RCOG/ISUOG criteria для non-viable pregnancy; counseling с осторожностью.",
    excerpt: "FMF miscarriage risk model supports early pregnancy counseling.",
    tier: 1,
    source: { label: "FMF miscarriage calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}miscarriage` },
    tags: ["miscarriage", "выкидыш", "ранняя беременность", "калькулятор"],
    relatedLinks: [{ label: "Помощник акушера", href: "/assistant/obstetrics" }],
  },
  {
    id: "fmf-calc-uterine-pi",
    shelf: "us-fmf",
    title: "Калькулятор UtA PI (FMF)",
    summary:
      "Отдельный FMF uterine artery PI calculator переводит raw PI в MoM с учётом CRL и maternal factors для PE/SGA models.",
    clinicalPearl: "PI измеряют bilateral at crossover; среднее — для калькулятора.",
    excerpt: "FMF uterine artery PI calculator converts measurements to MoM values.",
    tier: 1,
    source: { label: "FMF uterine artery PI calculator", organization: "FMF", year: 2024, url: `${FMF_CALC}uterine` },
    tags: ["uterine artery", "PI", "MoM", "калькулятор", "UtA"],
    relatedLinks: [...linkFmf],
  },

  // ——— Малый срок ———
  {
    id: "fmf-early-yolk-sac",
    shelf: "us-fmf",
    title: "Желточный мешок · малый срок",
    summary:
      "Желточный мешок виден при СДП ~8–10 мм; absent yolk sac при MSD criteria для pregnancy failure — по ISUOG thresholds.",
    clinicalPearl: "Не путать с artifact; при absent yolk sac + appropriate MSD — repeat 7–10 days.",
    excerpt: "Yolk sac appearance timing supports viability assessment in early pregnancy.",
    tier: 1,
    source: { label: "ISUOG · early pregnancy", organization: "ISUOG", year: 2023 },
    tags: ["желточный мешок", "yolk sac", "малый срок", "СДП"],
    relatedLinks: [{ label: "FMF · малый срок", href: "/assistant/fmf" }],
  },
  {
    id: "fmf-early-anembryonic",
    shelf: "us-fmf",
    title: "Анэмбриония · критерии",
    summary:
      "CRL ≥7 мм без cardiac activity или MSD ≥25 мм без embryo — criteria pregnancy failure (ISUOG); confirm senior / repeat.",
    clinicalPearl: "Исключите pseudo-sac и wrong dates; document two observers при возможности.",
    excerpt: "Ultrasound criteria for failed intrauterine pregnancy require strict measurement thresholds.",
    tier: 1,
    source: { label: "ISUOG early pregnancy failure", organization: "ISUOG", year: 2023 },
    tags: ["анэмбрия", "MSD", "КТР", "non-viable", "малый срок"],
    relatedLinks: [{ label: "FMF · малый срок", href: "/assistant/fmf" }],
  },
  {
    id: "fmf-early-hematoma",
    shelf: "us-fmf",
    title: "Ретрохориальная гематома",
    summary:
      "Subchorionic hematoma на ранних сроках — фактор риска miscarriage; размер и location влияют на prognosis; контроль US + symptoms.",
    clinicalPearl: "Документируйте % оболочки, distance from cervix; терапия — по симптомам и протоколу.",
    excerpt: "Subchorionic hemorrhage requires serial follow-up depending on size and clinical context.",
    tier: 1,
    source: { label: "ISUOG early pregnancy", organization: "ISUOG", year: 2023 },
    tags: ["гематома", "ретрохориальная", "угроза", "малый срок"],
    relatedLinks: [{ label: "FMF · малый срок", href: "/assistant/fmf" }],
  },

  // ——— Многоплодная ———
  {
    id: "fmf-twins-chorionicity",
    shelf: "us-fmf",
    title: "Близнецы · хорионичность",
    summary:
      "Chorionicity определяют до 13+6 нед (lambda/t-sign); monochorionic — higher risk TTTS/TAPS; weekly/biweekly surveillance protocols.",
    clinicalPearl: "Первый scan twins: number of placentas, gender, membrane insertion — mandatory documentation.",
    excerpt: "Chorionicity determination before 14 weeks guides twin pregnancy surveillance.",
    tier: 1,
    source: { label: "FMF · multiple pregnancies", organization: "FMF · ISUOG", year: 2023, url: FMF },
    tags: ["близнецы", "twins", "хорионичность", "monochorionic", "dichorionic"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-twins-ttts",
    shelf: "us-fmf",
    title: "TTTS · скрининг MC twins",
    summary:
      "Monochorionic twins: serial assessment polyhydramnios-oligohydramnios sequence; Quintero staging для TTTS; referral Fetal Medicine.",
    clinicalPearl: "Измеряйте SDP largest pool каждого sac; discordant bladder — red flag.",
    excerpt: "Monochorionic twin pregnancies require surveillance for twin-to-twin transfusion syndrome.",
    tier: 1,
    source: { label: "ISUOG twin pregnancy guideline", organization: "ISUOG", year: 2023 },
    tags: ["TTTS", "близнецы", "монохориальная", "полигидрамнион"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-twins-crl-discordance",
    shelf: "us-fmf",
    title: "CRL discordance · twins I триместр",
    summary:
      "Significant CRL discordance на I скрининге MC/DC twins → ↑ risk anomaly and selective FGR; NT измеряют каждому плоду.",
    clinicalPearl: "Отдельные NT/НB/DV для каждого fetus; риск T21 — per fetus в FMF software.",
    excerpt: "Crown-rump length discordance in twins prompts enhanced surveillance.",
    tier: 1,
    source: { label: "FMF · multiple pregnancies", organization: "FMF", year: 2023, url: FMF },
    tags: ["близнецы", "CRL", "discordance", "NT", "два плода"],
    relatedLinks: [...linkFmf],
  },

  // ——— II триместр ———
  {
    id: "fmf-brain-csp",
    shelf: "us-fmf",
    title: "Прозрачная перегородка (CSP)",
    summary:
      "CSP visualized 18–20 нед; absent CSP — marker для callosal anomalies; correlate with transventricular sweep.",
    clinicalPearl: "Boxed CSP width в протоколе; if absent — detailed neurosonography referral.",
    excerpt: "Cavum septi pellucidi assessment is part of mid-trimester neurosonography.",
    tier: 1,
    source: { label: "ISUOG neurosonography", organization: "ISUOG", year: 2023 },
    tags: ["CSP", "прозрачная перегородка", "мозг", "II триместр"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-ventriculomegaly",
    shelf: "us-fmf",
    title: "Вентрикулomegaly · lateral ventricles",
    summary:
      "Atrium width ≥10 мм — ventriculomegaly; mild 10–12 vs severe >15 — разная тактика MRI/fetal medicine.",
    clinicalPearl: "Measure at level of choroid plexus glomus; document unilateral vs bilateral.",
    excerpt: "Lateral ventricle atrium measurement thresholds guide neurosonographic workup.",
    tier: 1,
    source: { label: "ISUOG CNS guideline", organization: "ISUOG", year: 2023 },
    tags: ["ventriculomegaly", "желудочки", "мозг", "10 мм", "II триместр"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-placenta-previa",
    shelf: "us-fmf",
    title: "Placenta previa / low-lying",
    summary:
      "Расстояние края placenta до internal os ≥20 мм в III тримestre — usually safe vaginal delivery; low-lying — repeat US 32–36 нед.",
    clinicalPearl: "Transducer 3–4 cm from os, empty bladder; previa diagnosis — prefer third trimester.",
    excerpt: "Placenta location should be reassessed in the third trimester for delivery planning.",
    tier: 1,
    source: { label: "ISUOG placenta guideline", organization: "ISUOG", year: 2023 },
    tags: ["placenta previa", "low-lying", "placenta", "расстояние до зева"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-afi",
    shelf: "us-fmf",
    title: "ИАЖ (AFI) · олиго/полигидрамнион",
    summary:
      "AFI оценивают sum of four quadrants; oligohydramnios/polyhydramnios thresholds — по local charts (Медvedev Прил. 35); correlate with fetal growth and membranes.",
    clinicalPearl: "Single deepest pocket в twins; AFI в singleton — classic four-quadrant method.",
    excerpt: "Amniotic fluid index interpretation requires gestational age reference ranges.",
    tier: 1,
    source: { label: "ISUOG · amniotic fluid", organization: "ISUOG · Medvedev", year: 2023 },
    tags: ["AFI", "ИАЖ", "олигогидрамнион", "полигидрамнион", "воды"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-biometry-hadlock",
    shelf: "us-fmf",
    title: "Фетометрия · BPD HC AC FL",
    summary:
      "Стандарт II/III scan: BPD, HC, AC, FL → EFW (Hadlock); каждое измерение — standardized planes per ISUOG.",
    clinicalPearl: "Перцентili по Медvedev/INTERGROWTH; один outlier parameter — remeasure, не panic.",
    excerpt: "Standard fetal biometry requires strict anatomical planes for reproducible EFW.",
    tier: 1,
    source: { label: "ISUOG biometry practice", organization: "ISUOG", year: 2023 },
    tags: ["BPD", "HC", "AC", "FL", "EFW", "Hadlock", "фетометрия"],
    relatedLinks: [...linkFmf],
  },

  // ——— III триместр · Doppler ———
  {
    id: "fmf-ua-doppler",
    shelf: "us-fmf",
    title: "Пуповинная артерия · PI/RI",
    summary:
      "Elevated UA PI/RI или absent/reversed end-diastolic flow — marker placental insufficiency; stage with MCA and DV.",
    clinicalPearl: "Sample после fetal breathing quiet; RI often used per Medvedev tables (Прил. 37).",
    excerpt: "Umbilical artery Doppler is central to fetal growth restriction surveillance.",
    tier: 1,
    source: { label: "ISUOG Doppler guideline", organization: "ISUOG", year: 2023 },
    tags: ["umbilical artery", "UA", "PI", "RI", "допплер", "ЗРП"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-mca-doppler",
    shelf: "us-fmf",
    title: "СМА · PI и PSV",
    summary:
      "Brain sparing: ↓MCA PI; PSV MCA ≥1.5 MoM (Mari) — anemia screening; не путать with technical errors.",
    clinicalPearl: "PSV sample near MCA origin; gestational age critical for MoM.",
    excerpt: "Middle cerebral artery Doppler includes PI for FGR and PSV for anemia assessment.",
    tier: 1,
    source: { label: "ISUOG · MCA Doppler", organization: "ISUOG · Mari", year: 2023 },
    tags: ["MCA", "СМА", "PSV", "анemia", "brain sparing", "допплер"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-cpr",
    shelf: "us-fmf",
    title: "CPR · cerebroplacental ratio",
    summary:
      "CPR = MCA PI / UA PI; low CPR → ↑ risk adverse outcome in FGR; используют в conjunction с percentiles, not alone.",
    clinicalPearl: "Compute with contemporaneous UA and MCA; document GA at measurement.",
    excerpt: "Cerebroplacental ratio augments Doppler assessment in suspected growth restriction.",
    tier: 1,
    source: { label: "ISUOG fetal growth / Doppler", organization: "ISUOG", year: 2023 },
    tags: ["CPR", "cerebroplacental", "допплер", "ЗРП", "MCA", "UA"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-dv-third-trimester",
    shelf: "us-fmf",
    title: "Венозный проток · III триместр / ЗРП",
    summary:
      "DV a-wave absent/reversed in late FGR — severe hypoxia marker; timing of delivery decision with multidisciplinary team.",
    clinicalPearl: "DV в комплексе с UA/MCA/CTG; pattern change — escalate surveillance.",
    excerpt: "Ductus venosus Doppler in late pregnancy guides delivery timing in FGR.",
    tier: 1,
    source: { label: "ISUOG · DV in FGR", organization: "ISUOG", year: 2023 },
    tags: ["ductus venosus", "DV", "ЗРП", "III триместр", "a-wave"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-fgr-workup",
    shelf: "us-fmf",
    title: "ЗРП · диагностический алгоритм",
    summary:
      "FGR diagnosis: EFW or AC <3rd centile, or ↓ trajectory + Doppler changes; исключить aneuploidy/infection/placental causes.",
    clinicalPearl: "Serial scans q2–3 weeks; uteroplacental Doppler + amniotic fluid + biophysical profile per protocol.",
    excerpt: "Fetal growth restriction requires serial biometry and comprehensive Doppler evaluation.",
    tier: 1,
    source: { label: "ISUOG fetal growth guideline", organization: "ISUOG", year: 2023 },
    tags: ["ЗРП", "FGR", "SGA", "алгоритм", "допплер"],
    relatedLinks: [...linkFmf],
  },

  // ——— Шейка · рубец ———
  {
    id: "fmf-cervix-funneling",
    shelf: "us-fmf",
    title: "Funneling шейки матки",
    summary:
      "Cervical funneling на TV US — дополнительный признак ↑ preterm risk вместе с short CL; document length of closed cervix.",
    clinicalPearl: "Не давить transducer; measure CL before fundal pressure.",
    excerpt: "Cervical funneling complements cervical length in preterm birth risk assessment.",
    tier: 1,
    source: { label: "FMF · cervical assessment", organization: "FMF", year: 2023 },
    tags: ["funneling", "шейка", "CL", "преждевременные"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-cervix-short-threshold",
    shelf: "us-fmf",
    title: "Короткая шейка · пороги",
    summary:
      "CL <25 мм на 18–24 нед historically high PTB risk; на I тримestre FMF uses CL in calculator — пороги action зависят от GA и history.",
    clinicalPearl: "Не interrogate cervix после vaginal probe elsewhere same session; standardize bladder empty.",
    excerpt: "Cervical length thresholds are gestational-age and context dependent.",
    tier: 1,
    source: { label: "FMF preterm screening", organization: "FMF", year: 2023, url: `${FMF_CALC}preterm` },
    tags: ["CL", "короткая шейка", "25 мм", "преждевременные"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-uterine-scar",
    shelf: "us-fmf",
    title: "Рубец на матке · толщина (CS)",
    summary:
      "Lower uterine segment thickness в late pregnancy — assess trial of labor vs repeat CS; heterogeneous scar — ↑ rupture concern.",
    clinicalPearl: "Measure at hysterotomy site level; document myometrial continuity; не единственный критерий VBAC.",
    excerpt: "Ultrasound assessment of cesarean scar supports delivery planning.",
    tier: 1,
    source: { label: "ISUOG / RCOG scar assessment", organization: "ISUOG", year: 2023 },
    tags: ["рубец", "kesarevo", "CS", "VBAC", "толщина миометрия"],
    relatedLinks: [...linkFmf],
  },

  // ——— NIPT · invasive ———
  {
    id: "fmf-nipt-limits",
    shelf: "us-fmf",
    title: "NIPT · ограничения screening",
    summary:
      "cfDNA — screening для common aneuploidies; false positive/negative возможны; no-call rate; не заменяет anomaly scan.",
    clinicalPearl: "После high-risk NIPT — genetic counseling; invasive test для confirm при high clinical need.",
    excerpt: "Cell-free DNA testing is screening with defined sensitivity and failure rates.",
    tier: 1,
    source: { label: "ISUOG cfDNA guidance", organization: "ISUOG · FMF", year: 2023 },
    tags: ["NIPT", "cfDNA", "скрининг", "инвазивная"],
    relatedLinks: [...linkFmf],
  },
  {
    id: "fmf-invasive-testing",
    shelf: "us-fmf",
    title: "Инвазивная диагностика · CVS/amnio",
    summary:
      "CVS 11–14 нед vs amniocentesis ≥15–16 нед — по risk-benefit; offered when high risk T21 or structural markers.",
    clinicalPearl: "Pre-procedure: blood group, infections screen per protocol; counseling miscarriage risk.",
    excerpt: "Invasive prenatal diagnosis confirms karyotype when screening indicates high risk.",
    tier: 1,
    source: { label: "FMF · karyotype pathway", organization: "FMF", year: 2023, url: FMF },
    tags: ["CVS", "амnio", "амниocentesis", "кариотип", "инвазивная"],
    relatedLinks: [...linkFmf],
  },
];
