import { StyleSheet } from "react-native";

export const gynRouterStyles = StyleSheet.create({
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  title: { fontSize: 16, fontWeight: "700", color: "#111827" },
  label: { fontSize: 13, color: "#374151", marginTop: 4 },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#fff",
  },
  result: { fontSize: 14, color: "#0f172a", lineHeight: 20 },
  meta: { fontSize: 11, color: "#64748b" },
  rowWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  btn: {
    backgroundColor: "#0d9488",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  btnText: { color: "#fff", fontWeight: "700" },
  backBtn: {
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    marginBottom: 8,
  },
  backBtnText: { color: "#0f172a", fontWeight: "600" },
  tile: {
    width: "47%",
    flexGrow: 1,
    minHeight: 88,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    gap: 4,
  },
  tileTitle: { fontSize: 14, fontWeight: "800", color: "#831843" },
  tileSub: { fontSize: 11, color: "#4b5563", lineHeight: 15 },
  assistantGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginVertical: 8 },
  assistantWidget: {
    width: "47%",
    flexGrow: 1,
    minHeight: 126,
    borderRadius: 18,
    padding: 14,
    justifyContent: "space-between",
  },
  assistantKicker: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  assistantTitle: { color: "#fff", fontSize: 18, fontWeight: "900", lineHeight: 22, marginTop: 8 },
  assistantSub: { color: "rgba(255,255,255,0.86)", fontSize: 12, lineHeight: 16, fontWeight: "700", marginTop: 8 },
});
