import type { ClinicalTool } from "./types";

export const CLINICAL_TOOLS: ClinicalTool[] = [
  {
    id: "chat",
    title: "Чат врачей",
    subtitle: "Обсуждения, фото УЗИ, каналы гинекология / акушерство",
    category: "community",
    roles: ["ultrasound", "gynecologist", "obstetrician", "allied"],
    synonyms: ["болталка", "сообщество", "коллеги", "обсудить", "чат узд"],
    keywords: ["chat", "community"],
    webHref: "/cases",
    mobileAction: "chat_web",
  },
  {
    id: "new-case",
    title: "Новый кейс УЗИ",
    subtitle: "Снимок в галерею кейса для разбора",
    category: "community",
    roles: ["ultrasound", "gynecologist", "obstetrician", "allied"],
    synonyms: ["кейс", "фото узи", "разбор", "картинка"],
    keywords: ["case", "upload"],
    webHref: "/cases/new",
    mobileAction: "new_case",
  },
  {
    id: "orads-hub",
    title: "O-RADS US",
    subtitle: "Калькулятор, картинки, расчет по тексту, таблицы, IOTA",
    category: "ovary",
    roles: ["ultrasound", "gynecologist", "allied"],
    synonyms: ["эхограммы o-rads", "озерская", "orads карточки", "iota atlas", "орадс"],
    keywords: ["orads", "echograms", "hub"],
    webHref: "/tools/calc/rads/o-rads",
    mobileAction: "orads_hub",
  },
  {
    id: "orads-echograms",
    title: "O-RADS · эхограммы",
    subtitle: "Учебные карточки придатков по нозологиям (Озерская)",
    category: "ovary",
    roles: ["ultrasound", "gynecologist", "allied"],
    synonyms: ["эхограммы", "ozerskaya", "карточки придатков", "iota cases"],
    keywords: ["orads", "echograms"],
    webHref: "/tools/refs/orads-echograms",
    mobileAction: "orads_echograms",
  },
  {
    id: "orads-guide",
    title: "O-RADS · руководство",
    subtitle: "Реферат ACR v2022: алгоритм, случаи, категории 0–5",
    category: "ovary",
    roles: ["ultrasound", "gynecologist", "allied"],
    synonyms: ["реферат o-rads", "orads us", "acr guidance", "обучение o-rads"],
    keywords: ["orads", "referat", "guide"],
    webHref: "/tools/refs/orads-guide",
    mobileAction: "orads_guide",
  },
  {
    id: "orads-wizard",
    title: "O-RADS US · калькулятор",
    subtitle: "Пошаговый, по картинке, по тексту, Pro/IOTA",
    category: "ovary",
    roles: ["ultrasound", "gynecologist", "allied"],
    synonyms: ["o-rads", "калькулятор яичник", "orads us", "iota simple rules"],
    keywords: ["orads", "calculator", "iota"],
    webHref: "/tools/calc/rads/o-rads",
    mobileAction: "orads_wizard",
  },
  {
    id: "orads",
    title: "O-RADS US",
    subtitle: "O-RADS US v2022 + IOTA 2026",
    category: "ovary",
    roles: ["ultrasound", "gynecologist", "allied"],
    synonyms: ["яичник", "киста", "аднекс", "o-rads", "iota", "придаток"],
    keywords: ["ovary", "adnexa"],
    webHref: "/tools/calc/rads/o-rads",
    mobileAction: "orads",
  },
  {
    id: "endometrium",
    title: "Эндометрий",
    subtitle: "M-эхо, пороги, очаг, тамоксифен · ISUOG / КР РФ",
    category: "uterus",
    roles: ["ultrasound", "gynecologist", "allied"],
    synonyms: ["m-эхо", "полость матки", "кровотечение", "менопауза", "постменопауза", "згт", "смер"],
    keywords: ["endometrium", "lining"],
    webHref: "/calculators/endometrium",
    mobileAction: "endometrium",
  },
  {
    id: "uterus-clinic",
    title: "Матка · FIGO + аденомиоз / ДИЭ",
    subtitle: "Миома, sono-консенсус, протокол",
    category: "uterus",
    roles: ["ultrasound", "gynecologist", "allied"],
    synonyms: ["миома", "аденомиоз", "дие", "фиго", "матка", "эндометриоз глубокий"],
    keywords: ["uterus", "figo", "fibroid"],
    webHref: "/uterus-3d",
    mobileAction: "uterus_clinic",
  },
  {
    id: "cervical-length",
    title: "Длина шейки матки (CL)",
    subtitle: "Скрининг 16–24 нед, воронка, sludge",
    category: "pregnancy",
    roles: ["ultrasound", "obstetrician", "gynecologist"],
    synonyms: ["цервикальная длина", "шейка беременная", "укорочение шейки", "cl мм"],
    keywords: ["cervix", "cervical length"],
    webHref: "/calculators/cervical-length",
    mobileAction: "cervical_length",
  },
  {
    id: "popq",
    title: "POP-Q · русская версия",
    subtitle: "Опущение / выпадение ОМТ · золотой стандарт POP-Q",
    category: "pelvic",
    roles: ["gynecologist", "ultrasound"],
    synonyms: ["пролапс", "опущение", "выпадение", "тазовое дно", "поп-кью", "pop q", "pop-q"],
    keywords: ["prolapse", "popq"],
    webHref: "/calculators/pop-q",
    mobileAction: "popq",
  },
  {
    id: "colposcopy",
    title: "Кольпоскопия",
    subtitle: "Протокол по бланку · Swede Score · риск CIN 2+",
    category: "uterus",
    roles: ["gynecologist", "ultrasound"],
    synonyms: [
      "кольпоскопия",
      "swede score",
      "свид score",
      "ацетобелый",
      "йод-негативная",
      "cin",
      "дисплазия шейки",
      "шейка матки кольпо",
    ],
    keywords: ["colposcopy", "swede", "cervix"],
    webHref: "/calculators/colposcopy",
    mobileAction: "colposcopy",
  },
  {
    id: "cin-risk",
    title: "CIN Risk Calculator",
    subtitle: "CIN1 / CIN2+ / CIN3+ / AIS / инвазия — HPV, Bethesda, IFCPC",
    category: "uterus",
    roles: ["gynecologist", "ultrasound"],
    synonyms: ["cin risk", "cin1", "cin2", "cin3", "ais", "дисплазия", "ифцпк"],
    keywords: ["cin", "hpv", "bethesda", "ifcpc"],
    webHref: "/calculators/cin-risk",
    mobileAction: "cin_risk",
  },
  {
    id: "cervical-intelligence",
    title: "Cervical Pathology Intelligence",
    subtitle: "CDS: IFCPC + HPV + Bethesda + Swede + Quality + рекомендации",
    category: "uterus",
    roles: ["gynecologist", "ultrasound"],
    synonyms: ["cpi", "cervical intelligence", "патология шейки", "cds шейка"],
    keywords: ["cervical", "cpi", "cds", "colposcopy"],
    webHref: "/calculators/cervical-intelligence",
    mobileAction: "cervical_intelligence",
  },
  {
    id: "cervix-pathology",
    title: "Патология шейки · цитология",
    subtitle: "8 глав, Bethesda, скрининг, кейсы, quiz",
    category: "reference",
    roles: ["gynecologist", "obstetrician", "allied"],
    synonyms: ["цитология", "bethesda", "hpv", "скрининг", "шейка", "cin", "ршм", "pap"],
    keywords: ["cervix", "cytology", "colposcopy", "screening"],
    webHref: "/tools/refs/cervix-pathology?tab=cytology",
    mobileAction: "cervix_pathology",
  },
  {
    id: "birads",
    title: "BI-RADS US",
    subtitle: "Алгоритм v2025 · молочная железа",
    category: "breast",
    roles: ["ultrasound", "allied", "gynecologist"],
    synonyms: ["мж", "молочная", "бирэдс", "bi-rads", "узел мж"],
    keywords: ["breast", "birads"],
    webHref: "/calculators/bi-rads",
    mobileAction: "birads",
  },
  {
    id: "breast-3d",
    title: "Макет МЖ",
    subtitle: "Часы · см от соска · обе груди",
    category: "breast",
    roles: ["ultrasound", "allied"],
    synonyms: ["топография мж", "квадрант", "локализация мж"],
    keywords: ["breast map"],
    webHref: "/breast-3d",
    mobileAction: "breast_3d",
  },
  {
    id: "tirads",
    title: "TI-RADS ЩЖ",
    subtitle: "Российская адаптация 2023 · ТАБ · TI-MDS",
    category: "thyroid",
    roles: ["ultrasound", "allied"],
    synonyms: ["щитовидка", "узел щж", "ти радс", "тиреоид", "таб щж"],
    keywords: ["thyroid", "tirads"],
    webHref: "/calculators/ti-rads",
    mobileAction: "tirads",
  },
  {
    id: "ln-rads",
    title: "LN-RADS",
    subtitle: "Лимфоузлы · УЗИ",
    category: "lymph",
    roles: ["ultrasound", "allied"],
    synonyms: ["лимфоузел", "лу", "подмышечный", "шейный лу"],
    keywords: ["lymph", "lnrads"],
    mobileAction: "ln_rads",
  },
  {
    id: "elastography",
    title: "Эластография",
    subtitle: "Strain / SWE · шейка, миометрий, яичники, МЖ",
    category: "uterus",
    roles: ["ultrasound"],
    synonyms: ["эластография", "swe", "strain", "жёсткость"],
    keywords: ["elastography"],
    webHref: "/calculators/elastography",
    mobileAction: "elastography",
  },
  {
    id: "vascular-carotid",
    title: "Стеноз ВСА",
    subtitle: "Дуплекс · табл. 4.1 Куликов",
    category: "reference",
    roles: ["ultrasound", "allied"],
    synonyms: ["вса", "бца", "каротид", "стеноз", "дуплекс", "сосуды"],
    keywords: ["vascular", "carotid", "stenosis", "duplex"],
    webHref: "/assistant/vascular",
    mobileAction: "vascular_carotid",
  },
  {
    id: "ob-calc",
    title: "Калькулятор расчёта срока беременности",
    subtitle: "ПМП, УЗИ, КТР, ЭКО, фетометрия, декрет",
    category: "pregnancy",
    roles: ["obstetrician", "gynecologist", "ultrasound"],
    synonyms: [
      "калькулятор срока",
      "расчёт срока беременности",
      "oblcalc",
      "ob calc",
      "obcalc",
      "срок беременности",
      "пдр",
      "пмп",
      "датировка",
      "гестационный возраст",
      "ктр",
      "негеле",
    ],
    keywords: ["pregnancy dating", "edd", "ga", "obstetric calculator"],
    webHref: "/calculators/ob",
    mobileAction: "ga_lmp",
  },
  {
    id: "fmf",
    title: "FMF · скрининг",
    subtitle: "Малый срок, I/II/III, допплер, шейка, рубец",
    category: "pregnancy",
    roles: ["obstetrician", "ultrasound"],
    synonyms: ["скрининг", "первый триместр", "ктр", "твп", "fmf", "пренатальный"],
    keywords: ["fmf", "prenatal"],
    webHref: "/assistant/fmf",
    mobileAction: "fmf",
  },
  {
    id: "ga-lmp",
    title: "Срок по ПМП",
    subtitle: "ПДР, срок сегодня",
    category: "pregnancy",
    roles: ["obstetrician", "gynecologist", "ultrasound"],
    synonyms: ["пмп", "пдр", "менструация", "срок беременности", "oblcalc"],
    keywords: ["lmp", "edd"],
    webHref: "/calculators/ob?tab=lmp",
    mobileAction: "ga_lmp",
  },
  {
    id: "ga-us",
    title: "Срок по УЗИ",
    subtitle: "Дата исследования + срок на момент осмотра",
    category: "pregnancy",
    roles: ["obstetrician", "ultrasound"],
    synonyms: ["срок узи", "гестационный возраст"],
    keywords: ["ga ultrasound"],
    webHref: "/calculators/ob?tab=us",
    mobileAction: "ga_us",
  },
  {
    id: "ga-crl",
    title: "Срок по КТР",
    subtitle: "CRL мм + дата УЗИ",
    category: "pregnancy",
    roles: ["obstetrician", "ultrasound"],
    synonyms: ["ктр", "crl", "копчико-теменной"],
    keywords: ["crown rump"],
    webHref: "/calculators/ob?tab=crl",
    mobileAction: "ga_crl",
  },
  {
    id: "ga-feto",
    title: "Срок по фетометрии",
    subtitle: "BPD / HC / FL / AC (II–III тр.)",
    category: "pregnancy",
    roles: ["obstetrician", "ultrasound"],
    synonyms: ["bpd", "фетометрия", "биометрия плода"],
    keywords: ["biometry dating"],
    webHref: "/calculators/ob?tab=feto",
    mobileAction: "ga_us",
  },
  {
    id: "ga-ivf",
    title: "Срок · ЭКО / овуляция",
    subtitle: "ПДР от переноса или овуляции",
    category: "pregnancy",
    roles: ["obstetrician", "gynecologist"],
    synonyms: ["эко", "перенос", "овуляция", "ivf"],
    keywords: ["embryo transfer"],
    webHref: "/calculators/ob?tab=ivf",
    mobileAction: "ga_us",
  },
  {
    id: "assistant-gyn",
    title: "Помощник врача-гинеколога",
    subtitle: "Нозология → обследования → тактика → источник",
    category: "assistant",
    roles: ["gynecologist", "ultrasound"],
    synonyms: ["нозология", "маршрут", "приём гинеколог", "мкб", "помощник врача гинеколога"],
    keywords: ["gynecology assistant"],
    webHref: "/assistant/gynecology",
    mobileAction: "gyn_assistant_gyn",
  },
  {
    id: "assistant-obs",
    title: "Помощник врача-акушера",
    subtitle: "Беременность → риски → тактика → КР / приказы",
    category: "assistant",
    roles: ["obstetrician", "gynecologist"],
    synonyms: ["акушер", "беременность маршрут", "потери", "помощник врача акушера"],
    keywords: ["obstetrics assistant"],
    webHref: "/assistant/obstetrics",
    mobileAction: "gyn_assistant_obs",
  },
  {
    id: "assistant-us",
    title: "Помощник врача УЗИ",
    subtitle: "Карта органа → локализация → классификация → протокол",
    category: "assistant",
    roles: ["ultrasound", "gynecologist", "obstetrician"],
    synonyms: [
      "узи помощник",
      "врач узи",
      "локализация образования",
      "карта органа",
      "протокол узи",
      "помощник врача узи",
    ],
    keywords: ["ultrasound assistant", "topography", "protocol"],
    webHref: "/assistant/ultrasound",
    mobileAction: "ultrasound_assistant",
  },
  {
    id: "evidence-assistant",
    title: "Evidence Assistant",
    subtitle: "PubMed · Cochrane · КР · AI",
    category: "reference",
    roles: ["gynecologist", "obstetrician", "ultrasound", "allied"],
    synonyms: ["ebm", "pubmed", "доказательства", "cochrane", "evidence"],
    keywords: ["evidence", "assistant"],
    webHref: "/tools/refs/evidence-assistant",
    mobileAction: "evidence_assistant",
  },
  {
    id: "guidelines",
    title: "КР и приказы",
    subtitle: "КР МЗ РФ, приказы ДЗМ",
    category: "reference",
    roles: ["gynecologist", "obstetrician", "ultrasound", "allied"],
    synonyms: ["клинические рекомендации", "приказ", "мз рф", "дзм"],
    keywords: ["guidelines"],
    webHref: "/guidelines",
    mobileAction: "guidelines",
  },
  {
    id: "nosology",
    title: "Нозологии",
    subtitle: "Справочник заболеваний",
    category: "reference",
    roles: ["gynecologist", "obstetrician", "allied"],
    synonyms: ["заболевание", "диагноз", "справочник"],
    keywords: ["nosology"],
    webHref: "/nosologies",
    mobileAction: "nosology",
  },
  {
    id: "clinical-ref",
    title: "Клинические нормы УЗИ",
    subtitle: "ISUOG, Hadlock, методики",
    category: "reference",
    roles: ["ultrasound", "obstetrician"],
    synonyms: ["нормы", "hadlock", "фетометрия таблица"],
    keywords: ["reference"],
    webHref: "/reference",
    mobileAction: "clinical_ref",
  },
  {
    id: "medvedev",
    title: "Консенсусы УЗИ",
    subtitle: "MUSA · IETA · IOTA · IDEA",
    category: "reference",
    roles: ["ultrasound", "gynecologist"],
    synonyms: ["medvedev", "консенсус", "musa", "ieta"],
    keywords: ["consensus"],
    mobileAction: "medvedev",
  },
  {
    id: "orads-flow",
    title: "O-RADS Library",
    subtitle: "Дерево решений",
    category: "ovary",
    roles: ["ultrasound", "gynecologist"],
    synonyms: ["дерево o-rads", "библиотека яичник"],
    keywords: ["orads flow"],
    mobileAction: "orads_flow",
  },
  {
    id: "telegram",
    title: "Telegram сообщество",
    subtitle: "@UltraGynAnalytics",
    category: "community",
    roles: ["ultrasound", "gynecologist", "obstetrician", "allied"],
    synonyms: ["телеграм", "канал"],
    keywords: ["telegram"],
    mobileAction: "telegram",
  },
];

export function getClinicalToolById(id: string): ClinicalTool | undefined {
  return CLINICAL_TOOLS.find((t) => t.id === id);
}

export const TOOL_CATEGORY_LABELS: Record<ClinicalTool["category"], string> = {
  community: "Сообщество",
  ovary: "Яичник",
  uterus: "Матка",
  breast: "Молочная железа",
  thyroid: "Щитовидная железа",
  lymph: "Лимфоузлы",
  pregnancy: "Беременность",
  pelvic: "Тазовое дно",
  assistant: "Помощник приёма",
  reference: "Справочник",
};
