export const PROTOCOL_FIELD_TO_TOPIC: Record<string, string> = {
  crl_mm: "crl",
  nt_mm: "nt",
  bpd_mm: "bpd",
  hc_mm: "hc",
  ac_mm: "ac",
  fl_mm: "fl",
  hl_mm: "hl",
  lmp: "ga-dating",
  ga_days: "ga-dating",
  efw_grams: "efw",
  afi: "afi",
  "amniotic.afi_q1_cm": "afi",
  "amniotic.afi_q2_cm": "afi",
  "amniotic.afi_q3_cm": "afi",
  "amniotic.afi_q4_cm": "afi",
  "doppler.ua_pi": "doppler-ob",
  "doppler.ua_ri": "doppler-ob",
  "doppler.uterine_pi_left": "doppler-ob",
  "doppler.uterine_pi_right": "doppler-ob",
};
