import type { ClinicalReferenceIndex, ClinicalTopic } from "./types";

const TOPICS: ClinicalTopic[] = [
  {
    id: "ga-dating",
    title: "Расчёт срока беременности",
    section: "Акушерство",
    tags: ["срок", "пмп", "пдр", "датирование"],
    summary: "Срок по ПМП, по КТР (1-й триместр) или по фетометрии II–III триместра.",
    methodology:
      "ПМП + дата исследования → акушерский срок. 1-й триместр: приоритет КТР (Robinson-Fleming). При КТР >84 мм — ориентир по БПР. II–III триместр: комбинированная оценка по BPD/HC/AC/FL при согласованных измерениях.",
    sources: ["Robinson HP, Fleming JEH. Br J Obstet Gynaecol. 1975", "ISUOG practice guidelines"],
  },
  {
    id: "crl",
    title: "КТР (CRL)",
    section: "Акушерство",
    tags: ["ктр", "crl", "1 триместр", "срок"],
    summary: "Измерение в сагиттальной плоскости, нейтральное положение плода.",
    methodology:
      "Плод горизонтально, спинкой к датчику. Полоска амниотической жидкости между подбородком и грудью ~2–4 мм. Калиперы на коже в наиболее удалённых точках. Не включать конечности.",
    sources: ["Robinson-Fleming", "FMF / ISUOG 11–13+6"],
  },
  {
    id: "nt",
    title: "ТВП (NT)",
    section: "Акушерство",
    tags: ["твп", "nt", "воротниковое", "скрининг"],
    summary: "Скрининг 11–13+6 нед; измерение on-to-on по внутренним контурам.",
    methodology:
      "КТР 45–84 мм. Сагиттальная плоскость, плод нейтрален. Калиперы: внутренний контур гиперэхогенных линий, без амниотической оболочки.",
    sources: ["Nicolaides KH", "FMF guidelines"],
  },
  {
    id: "bpd",
    title: "БПР (BPD)",
    section: "Акушерство",
    tags: ["бпр", "bpd", "теменные", "таламус"],
    summary: "Аксиально на уровне зрительных бугров.",
    methodology:
      "Сечение на уровне таламуса и зрительных бугров. Мозжечок не виден. Калиперы: outer-inner (⊥ к М-эхо).",
    sources: ["Hadlock FP et al.", "ISUOG biometry"],
  },
  {
    id: "hc",
    title: "ОГ (HC)",
    section: "Акушерство",
    tags: ["ог", "hc", "голова"],
    summary: "Окружность головы по внешнему контуру на уровне BPD.",
    methodology: "Трассировка по внешнему контуру черепа. Перцентили — таблицы центра / INTERGROWTH.",
    sources: ["Hadlock", "INTERGROWTH-21st"],
  },
  {
    id: "ac",
    title: "ОЖ (AC)",
    section: "Акушерство",
    tags: ["ож", "ac", "живот"],
    summary: "На уровне желудка и ворот печени.",
    methodology: "Поперечное сечение: желудок, воротная вена, пупочная вена. Почки не включать.",
    sources: ["Hadlock AC", "ISUOG"],
  },
  {
    id: "fl",
    title: "ДБ (FL)",
    section: "Акушерство",
    tags: ["дб", "fl", "бедро"],
    summary: "Только диафиз; без эпифизов.",
    methodology: "Длинная ось бедра, угол ~90° к лучу.",
    sources: ["Hadlock FL", "ISUOG"],
  },
  {
    id: "hl",
    title: "ДП (HL)",
    section: "Акушерство",
    tags: ["дп", "hl", "плечо"],
    summary: "Диафиз плечевой кости.",
    methodology: "Аналогично ДБ. Используется в EFW Hadlock.",
    sources: ["Hadlock EFW"],
  },
  {
    id: "efw",
    title: "Масса плода (EFW)",
    section: "Акушерство",
    tags: ["efw", "масса", "hadlock"],
    summary: "Hadlock III/IV при BPD, HC, AC, FL.",
    methodology: "Hadlock IV предпочтителен при полном наборе. Сверка перцентилей роста.",
    sources: ["Hadlock FP et al. Radiology 1985"],
  },
  {
    id: "afi",
    title: "Амниотическая жидкость (AFI)",
    section: "Акушерство",
    tags: ["afi", "воды", "sdp"],
    summary: "Сумма четырёх карманов; SDP — макс. карман.",
    methodology: "AFI <5 / >25 см — ориентиры (уточнять протокол центра).",
    sources: ["Phelan 1987", "ISUOG"],
  },
  {
    id: "doppler-ob",
    title: "Допплер акушерский",
    section: "Акушерство",
    tags: ["допплер", "pi", "ri", "пуповина"],
    summary: "PI/RI пуповины и маточных артерий.",
    methodology: "Пуповина: свободная петля. Маточные — среднее L/R. Пороги по ISUOG/центру.",
    sources: ["ISUOG Doppler", "FMF"],
  },
  {
    id: "screening",
    title: "Скрининговые сроки",
    section: "Акушерство",
    tags: ["скрининг", "11-13", "18-22", "30-34"],
    summary: "I: 11–13+6; II: 18–22; III: 30–34 нед.",
    methodology: "I — КТР, ТВП; II — анатомия; III — рост, AFI, допплер по показаниям.",
    sources: ["ISUOG", "локальные рекомендации"],
  },
  {
    id: "thyroid",
    title: "Щитовидная железа",
    section: "Поверхностные органы",
    tags: ["щитовидная", "ti-rads"],
    summary: "Объём долей, TI-RADS узлов.",
    methodology: "V=A×B×C×0,479. Узлы — TI-RADS / ACR.",
    sources: ["ACR TI-RADS", "ATA"],
  },
  {
    id: "birads",
    title: "BI-RADS",
    section: "RADS",
    tags: ["bi-rads", "молочная"],
    summary: "Категории 0–6 по ACR.",
    methodology: "Используйте калькулятор BI-RADS в приложении.",
    sources: ["ACR BI-RADS"],
  },
];

export const CLINICAL_REFERENCE: ClinicalReferenceIndex = {
  id: "clinical_reference_v1",
  title: "Клинические нормы УЗИ",
  version: "1.0",
  builtAt: "2026-05-20T00:00:00.000Z",
  topics: TOPICS,
};
