begin;

create table if not exists public.security_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid references auth.users(id) on delete set null,
  actor_role text,
  ip_hash text not null,
  user_agent text,
  category text not null,
  action text not null,
  resource text,
  resource_id text,
  success boolean not null default true,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.security_audit_log enable row level security;

create policy security_audit_log_admin_inserter
  on public.security_audit_log
  for insert
  to service_role
  with check (true);

create policy security_audit_log_admin_read
  on public.security_audit_log
  for select
  to service_role
  using (true);

create index security_audit_log_created_at_idx
  on public.security_audit_log (created_at desc);

create index security_audit_log_actor_category_idx
  on public.security_audit_log (actor_id, category, created_at desc);

commit;
