import type { ClinicalGuideline } from "../types";

export const INTERNATIONAL_GUIDELINES: ClinicalGuideline[] = [
  {
    id: "int-isuog-pocus-2025",
    title: "ISUOG · Point-of-care ultrasound in Ob/Gyn (2025)",
    summary: "PoCUS в акушерстве и гинекологии: амбulatorия, emergency, bedside.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "ultrasound",
    year: 2025,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/isuog-guidelines/practice-guidelines-english.html",
    tags: ["ISUOG", "PoCUS", "emergency"],
    sections: [
      {
        title: "Ключевые сценарии",
        bullets: [
          "Emergency: эктопия, кровотечение, острая боль.",
          "Ambulatory: подтверждение беременности, AFI, предлежание.",
          "Процедуры: guided biopsy, IUD check.",
        ],
      },
    ],
  },
  {
    id: "int-isuog-twins-2025",
    title: "ISUOG · Ultrasound in twin pregnancy (updated 2025)",
    summary: "Многоплодие: хориальность, TTTS, рост, допpler.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "prenatal",
    year: 2025,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/isuog-guidelines/practice-guidelines-english.html",
    tags: ["ISUOG", "twins", "TTTS"],
  },
  {
    id: "int-isuog-endometrium-2024",
    title: "ISUOG Consensus · Sonographic assessment of the endometrium (2024)",
    summary: "Как выполнять гинекологическое УЗИ с фокусом на эндометрий и reporting.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "obgyn",
    year: 2024,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/isuog-guidelines.html",
    tags: ["ISUOG", "endometrium", "consensus"],
    relatedNosologyIds: ["endometrial-hyperplasia"],
  },
  {
    id: "int-isuog-11-14-2024",
    title: "ISUOG · Performance of 11–14 week ultrasound scan (2024)",
    summary: "Скрининг I триместра: КТР, NT, базовая анатомия, маркеры.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "prenatal",
    year: 2024,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/isuog-guidelines.html",
    tags: ["ISUOG", "11-14", "NT", "FMF"],
  },
  {
    id: "int-isuog-third-trimester-2024",
    title: "ISUOG · Third-trimester obstetric ultrasound scan (2024)",
    summary: "III триместр: biometry, placenta, AFI, doppler, presentation.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "prenatal",
    year: 2024,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/isuog-guidelines.html",
    tags: ["ISUOG", "III trimester", "FGR", "doppler"],
  },
  {
    id: "int-isuog-fetal-cardiac-2024",
    title: "ISUOG · Fetal cardiac screening (updated 2024)",
    summary: "Скрининг сердца плода: 4CV, outflow tracts, 3VT.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "prenatal",
    year: 2024,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/isuog-guidelines.html",
    tags: ["ISUOG", "fetal heart", "4CV"],
  },
  {
    id: "int-isuog-biometry-growth-2019",
    title: "ISUOG · Fetal biometry and growth (2019)",
    summary: "Биометрия, FGR, SGA, LGA — assessment and diagnosis.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "prenatal",
    year: 2019,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/fetal-biometry.html",
    tags: ["ISUOG", "biometry", "EFW", "FGR"],
  },
  {
    id: "int-isuog-obstetric",
    title: "ISUOG Practice Guidelines (акушерское УЗИ) — hub",
    summary: "Полный каталог ISUOG Practice Guidelines — дополнение к КР РФ.",
    shelf: "international",
    documentKind: "standard",
    issuer: "isuo",
    specialty: "ultrasound",
    year: 2024,
    status: "active",
    officialUrl: "https://www.isuog.org/clinical-resources/isuog-guidelines.html",
    tags: ["ISUOG", "акушерство", "УЗИ"],
  },
  {
    id: "int-eshre-endometriosis",
    title: "ESHRE Guideline — Endometriosis",
    summary: "Диагностика и лечение эндометриоза (европейский консенсус).",
    shelf: "international",
    documentKind: "clinical_recommendation",
    issuer: "eshre",
    specialty: "obgyn",
    year: 2022,
    status: "active",
    officialUrl: "https://www.eshre.eu/",
    tags: ["ESHRE", "эндометриоз"],
    relatedNosologyIds: ["pelvic-endometriosis", "endometrioma"],
  },
];
