export {
  ENDOMETRIUM_SOURCE,
  assessThickness,
  buildEndometriumProtocol,
  computeEffectiveThicknessMm,
  defaultEndometriumInput,
  endometriumFormOptions,
  evaluateFocalLesionTactic,
  evaluateTamoxifenTactic,
  type EndometriumAssessmentInput,
  type FluidInCavity,
  type PatientContext,
  type TacticResult,
  type ThicknessAssessment,
} from "../../../mobile/src/gynecology/endometrium/endometriumAssessment";
