import type { NavigationDomain } from "./navigation.config";

export type NavigationLinkOverride = {
  href?: string;
  externalHref?: string;
  accentBar?: string;
};

/** In-app routes and external URLs keyed by navigation.config `id`. */
export const NAVIGATION_LINK_OVERRIDES: Record<string, NavigationLinkOverride> = {
  "community.chat": { href: "/cases" },
  "community.new-case": { href: "/cases/new" },
  "community.telegram": { externalHref: "https://t.me/UltraGynAnalytics" },
  "assistant.hub": { href: "/assistant" },
  "ai-assistant.create-conclusion": { href: "/assistant" },
  "ai-assistant.analyze-ultrasound": { href: "/workspace" },
  "ai-assistant.consultation": { href: "/assistant" },
  "ai-assistant.find-patient": { href: "/patients" },
  "ai-assistant.create-protocol": { href: "/assistant" },
  "workspace.ai": { href: "/workspace" },
  "calculator.ob-hub": { href: "/calculators/ob" },
  "calculator.appointment.ga-lmp": { href: "/calculators/ob?tab=lmp" },
  "calculator.appointment.ga-us": { href: "/calculators/ob?tab=us" },
  "calculator.appointment.ga-ivf": { href: "/calculators/ob?tab=ivf" },
  "calculator.appointment.ga-movement": { href: "/calculators/ob?tab=movement" },
  "calculator.appointment.ga-antenatal": { href: "/calculators/ob?tab=antenatal" },
  "calculator.appointment.maternity-leave": { href: "/calculators/ob?tab=dekret" },
  "calculator.appointment.ga-edd": { href: "/calculators/ob?tab=edd" },
  "calculator.appointment.ga-crl": { href: "/calculators/ob?tab=crl" },
  "calculator.appointment.ga-feto": { href: "/calculators/ob?tab=feto" },
  "calculator.fetal-weight": { href: "/calculators/fetal-weight" },
  "calculator.bishop": { href: "/calculators/bishop" },
  "calculator.vbac": { href: "/calculators/vbac" },
  "calculator.pregnancy-meds": { href: "/calculators/pregnancy-medications" },
  "calculator.cervical-length": { href: "/calculators/cervical-length" },
  "education.obstetric-atlas": { href: "/library/obstetric-atlas" },
  "education.fetal-anatomy-22": { href: "/library/fetal-anatomy-22-views" },
  "education.fetal-doppler-1t": { href: "/library/fetal-doppler-first-trimester" },
  "education.fetal-spine": { href: "/library/fetal-spine" },
  "calculator.endometrium": { href: "/calculators/endometrium" },
  "calculator.pop-q": { href: "/calculators/pop-q" },
  "calculator.colposcopy": { href: "/calculators/colposcopy" },
  "calculator.cin-risk": { href: "/calculators/cin-risk" },
  "calculator.cervical-intelligence": { href: "/calculators/cervical-intelligence" },
  "calculator.risk-breast": { href: "/calculators/breast-risk" },
  "calculator.risk-cervical": { href: "/calculators/cervical-cancer-risk" },
  "calculator.risk-cin": { href: "/calculators/cin-follow-up" },
  "calculator.risk-ovarian": { href: "/calculators/ovarian-cancer-risk" },
  "clinical.idea-endometriosis": { href: "/idea-deep-endometriosis" },
  "education.cervix-pathology": { href: "/library/cervix-pathology" },
  "mockup.hub": { href: "/mockups" },
  "mockup.uterus": { href: "/uterus-3d" },
  "calculator.hub": { href: "/calculators" },
  "calculator.o-rads": { href: "/calculators/o-rads" },
  "calculator.bi-rads": { href: "/calculators/bi-rads" },
  "calculator.ti-rads": { href: "/calculators/ti-rads" },
  "calculator.ln-rads": { href: "/calculators/ln-rads" },
  "calculator.figo": { href: "/uterus-3d" },
  "calculator.elastography": { href: "/calculators/elastography" },
  "assistant.fmf": { href: "/assistant/fmf" },
  "report.adnex-orads": { href: "/reports/adnex" },
  "report.thyroid-tirads": { href: "/reports/thyroid" },
  "report.obstetric-biometry": { href: "/reports/obstetric" },
  "report.hub": { href: "/reports" },
  "mockup.ovary": { href: "/ovary-atlas" },
  "mockup.breast": { href: "/breast-3d" },
  "education.orads-guide": { href: "/tools/refs/orads-guide" },
  "education.orads-echograms": { href: "/tools/refs/orads-echograms" },
  "education.orads-hub": { href: "/tools/o-rads" },
  "education.iota-terms-2026": { href: "/tools/refs/iota-terms-2026" },
  "education.orads-flow": { href: "/tools/calc/rads/o-rads" },
  "education.library-hub": { href: "/library" },
  "reference.guidelines": { href: "/guidelines" },
  "reference.clinical-norms": { href: "/reference" },
  "reference.evidence": { href: "/evidence" },
  "reference.nosologies": { href: "/nosologies" },
  "reference.medvedev": { href: "/reference" },
  "workspace.home": { href: "/app" },
  "admin.dashboard": { href: "/dashboard" },
  "account.profile": { href: "/profile" },
  "education.isuog-basic": { href: "/library/basic-course" },
  "education.career-path": { href: "/app" },
  "billing.paywall": { href: "/paywall" },
  "pro.ai-full-conclusion": { href: "/paywall" },
  "pro.ai-diagnostic-recommendations": { href: "/paywall" },
  "pro.advanced-analytics": { href: "/dashboard" },
  "pro.voice-assistant": { href: "/assistant" },
  "pro.unlimited-ai": { href: "/paywall" },
};

/** Legacy home-tile gradient accents (overrides domain default). */
export const NAVIGATION_ACCENT_OVERRIDES: Record<string, string> = {
  "community.chat": "bg-gradient-to-r from-emerald-500 to-teal-500",
  "assistant.hub": "bg-gradient-to-r from-rose-600 to-pink-500",
  "calculator.ob-hub": "bg-gradient-to-r from-teal-600 to-cyan-500",
  "calculator.hub": "bg-gradient-to-r from-blue-500 to-cyan-400",
  "reference.guidelines": "bg-gradient-to-r from-amber-500 to-orange-400",
  "education.library-hub": "bg-gradient-to-r from-violet-500 to-purple-400",
  "education.isuog-basic": "bg-gradient-to-r from-rose-600 to-orange-500",
  "mockup.hub": "bg-gradient-to-r from-indigo-500 via-violet-500 to-pink-500",
  "mockup.ovary": "bg-gradient-to-r from-violet-600 to-purple-500",
  "mockup.uterus": "bg-gradient-to-r from-indigo-500 to-blue-400",
  "mockup.breast": "bg-gradient-to-r from-pink-500 to-rose-400",
  "workspace.ai": "bg-gradient-to-r from-sky-500 to-blue-500",
};

export const NAVIGATION_DOMAIN_ACCENT_BARS: Record<NavigationDomain, string> = {
  obstetrics: "bg-gradient-to-r from-teal-600 to-cyan-500",
  gynecology: "bg-gradient-to-r from-rose-500 to-pink-400",
  rads: "bg-gradient-to-r from-blue-500 to-cyan-400",
  library: "bg-gradient-to-r from-violet-500 to-purple-400",
  "ai-assistant": "bg-gradient-to-r from-sky-500 to-blue-500",
  "doctors-chat": "bg-gradient-to-r from-emerald-500 to-teal-500",
  education: "bg-gradient-to-r from-rose-600 to-orange-500",
  pro: "bg-gradient-to-r from-amber-500 to-orange-400",
};
