import type { QuizBank } from "../quiz-bank-types";

/** Expanded OBGYN exam question bank (Radiopaedia exam-practice style). */
export const EXAM_SET_PIECE_QUIZ_BANK: QuizBank = {
  topic: "OBGYN Exam Practice · set-pieces",
  version: "2026-07",
  lastReviewed: "2026-07-18",
  sources: [
    { id: "radiopaedia", title: "Radiopaedia · Gynecological ultrasound set-pieces", year: 2025 },
    { id: "isuog", title: "ISUOG Practice Guidelines", year: 2024 },
    { id: "o-rads", title: "ACR O-RADS US v2022", year: 2022 },
  ],
  questions: [
    {
      id: "sp-q01",
      category: "Endometrium",
      level: "doctor",
      question: "Эндометрий 12 мм у женщины 60 лет (ПМК). Первая тактика?",
      options: ["Наблюдение 1 год", "Гистероскопия/биопсия", "МРТ малого таза", "КОК"],
      correctIndex: 1,
      explanation: "ПМК + утолщение эндометрия → дообследование до исключения гиперплазии/рака.",
      sourceId: "radiopaedia",
    },
    {
      id: "sp-q02",
      category: "Adnexa",
      level: "student",
      question: "Papillary projection + vascularity в аднексальной массе →",
      options: ["O-RADS 1", "O-RADS 2", "O-RADS 3", "O-RADS ≥4"],
      correctIndex: 3,
      explanation: "Solid/papillary components with flow → high suspicion, O-RADS 4–5 workup.",
      sourceId: "o-rads",
    },
    {
      id: "sp-q03",
      category: "Myometrium",
      level: "student",
      question: "Submucosal myoma FIGO type 0–2 влияет на:",
      options: ["Только косметику", "Меноррагию, бесплодие", "Щитовидную железу", "Печень"],
      correctIndex: 1,
      explanation: "Submucosal/subserosal with cavity distortion → bleeding, fertility impact.",
      sourceId: "radiopaedia",
    },
    {
      id: "sp-q04",
      category: "Early pregnancy",
      level: "student",
      question: "При HCG 5000 mIU/mL и отсутствии ПЯ в матке —",
      options: ["Норма 5 нед", "Исключить эктопию", "Роды через 2 нед", "Не делать УЗИ"],
      correctIndex: 1,
      explanation: "Discriminatory zone ~3000–5000; empty uterus → ectopic until proven otherwise.",
      sourceId: "isuog",
    },
    {
      id: "sp-q05",
      category: "Early pregnancy",
      level: "doctor",
      question: "Критерий неудачной Б: embryo 6 mm без ЧСС —",
      options: ["Норма", "Missed abortion", "Twins", "Molar only"],
      correctIndex: 1,
      explanation: "CRL ≥7 mm no heartbeat or embryo visible no HR → pregnancy failure criteria.",
      sourceId: "isuog",
    },
    {
      id: "sp-q06",
      category: "Doppler",
      level: "doctor",
      question: "Absent end-diastolic flow в ПА при 34 нед —",
      options: ["Норма", "Urgent perinatal evaluation", "Контроль через месяц", "Плановые роды дома"],
      correctIndex: 1,
      explanation: "AEDF — critical Doppler; ISUOG FGR management.",
      sourceId: "isuog",
    },
    {
      id: "sp-q07",
      category: "AFV",
      level: "student",
      question: "Oligohydramnios: deepest vertical pocket —",
      options: [">8 cm", "<2 cm", "0 cm always normal", "Not measured"],
      correctIndex: 1,
      explanation: "DVP <2 cm = oligohydramnios (ISUOG).",
      sourceId: "isuog",
    },
    {
      id: "sp-q08",
      category: "Cervix",
      level: "doctor",
      question: "CL 18 mm в 22 нед при singleton без факторов риска —",
      options: ["Экстренные роды", "Интерпретация по протоколу; повтор при факторах", "Норма всегда", "Амниоцентез"],
      correctIndex: 1,
      explanation: "Short CL context-dependent; screening vs therapeutic cerclage protocols differ.",
      sourceId: "isuog",
    },
    {
      id: "sp-q09",
      category: "Screening",
      level: "student",
      question: "NT измеряется в сроке:",
      options: ["6–8 нед", "11–13+6 нед", "20–22 нед", "34–36 нед"],
      correctIndex: 1,
      explanation: "First trimester combined screening window.",
      sourceId: "isuog",
    },
    {
      id: "sp-q10",
      category: "Placenta",
      level: "doctor",
      question: "Placenta previa totalis в 32 нед — тактика родов:",
      options: ["Вагинальные роды", "Плановое КС", "Домашние роды", "Не УЗИ"],
      correctIndex: 1,
      explanation: "Complete previa → cesarean delivery.",
      sourceId: "isuog",
    },
    {
      id: "sp-q11",
      category: "Endometrium",
      level: "student",
      question: "Эндометрий 14 мм в proliferative phase (день 12) —",
      options: ["Всегда патология", "Может быть физиологичным", "Рак", "Не измеряют"],
      correctIndex: 1,
      explanation: "Endometrial thickness phase-dependent; postmenopausal rules differ.",
      sourceId: "radiopaedia",
    },
    {
      id: "sp-q12",
      category: "Adnexa",
      level: "student",
      question: "Simple anechoic cyst 3 cm in premenopausal woman —",
      options: ["O-RADS 1–2, follow-up", "Immediate surgery", "Chemotherapy", "TI-RADS"],
      correctIndex: 0,
      explanation: "Classic benign simple cyst → low O-RADS, short-interval follow-up if needed.",
      sourceId: "o-rads",
    },
    {
      id: "sp-q13",
      category: "Twins",
      level: "doctor",
      question: "Monochorionic diamniotic twins: обязательно оценить —",
      options: ["Только один плод", "TTTS signs, discordance, doppler", "Щитовидную", "Печень матери"],
      correctIndex: 1,
      explanation: "ISUOG twins guideline: MC complications surveillance.",
      sourceId: "isuog",
    },
    {
      id: "sp-q14",
      category: "Biometry",
      level: "student",
      question: "EFW <10th percentile — термин:",
      options: ["Macrosomia", "SGA / possible FGR", "Normal always", "Polyhydramnios"],
      correctIndex: 1,
      explanation: "Small for gestational age; FGR if pathological growth pattern.",
      sourceId: "isuog",
    },
    {
      id: "sp-q15",
      category: "Gynecology",
      level: "doctor",
      question: "Hemoperitoneum on pelvic US with acute pain —",
      options: ["Ignore", "Ruptured ectopic / hemorrhagic cyst until proven", "Vitamin D", "Massage"],
      correctIndex: 1,
      explanation: "Free fluid + pain → surgical emergency differential.",
      sourceId: "radiopaedia",
    },
    {
      id: "sp-q16",
      category: "Cervix",
      level: "student",
      question: "HSIL на цитологии — следующий шаг:",
      options: ["Ничего", "Colposcopy + biopsy", "МРТ головы", "Удаление яичника"],
      correctIndex: 1,
      explanation: "ASCCP/Bethesda pathway: colposcopy for HSIL.",
      sourceId: "isuog",
    },
    {
      id: "sp-q17",
      category: "Doppler",
      level: "doctor",
      question: "CPR (MCA/UA) снижен при FGR означает —",
      options: ["Улучшение", "Компромисс плода, стадия тяжелее", "Норма III trim", "Twins only"],
      correctIndex: 1,
      explanation: "Brain-sparing failure → worsening fetal status.",
      sourceId: "isuog",
    },
    {
      id: "sp-q18",
      category: "Anatomy",
      level: "student",
      question: "Absent nasal bone на 12 нед + ↑ NT —",
      options: ["Soft marker aneuploidy", "Normal always", "Placenta previa", "O-RADS 5"],
      correctIndex: 0,
      explanation: "FMF/ISUOG first trimester markers.",
      sourceId: "isuog",
    },
    {
      id: "sp-q19",
      category: "Gynecology",
      level: "student",
      question: "Структура gynecologic set-piece report:",
      options: [
        "Uterus → myometrium → endometrium → ovaries → fluid",
        "Only ovaries",
        "Only thyroid",
        "Random order",
      ],
      correctIndex: 0,
      explanation: "Radiopaedia structured set-piece approach.",
      sourceId: "radiopaedia",
    },
    {
      id: "sp-q20",
      category: "Obstetrics",
      level: "doctor",
      question: "IUGR with reversed ductus venosus a-wave —",
      options: ["Outpatient", "Highest urgency delivery planning", "Wait 4 weeks", "No Doppler needed"],
      correctIndex: 1,
      explanation: "DV abnormalities → imminent delivery consideration.",
      sourceId: "isuog",
    },
    {
      id: "sp-q21",
      category: "Adnexa",
      level: "doctor",
      question: "Dermoid cyst typical US features:",
      options: ["Pure anechoic", "Rokitansky nodule, fat-fluid level", "No shadowing", "Always solid"],
      correctIndex: 1,
      explanation: "Mature teratoma classic appearance.",
      sourceId: "radiopaedia",
    },
    {
      id: "sp-q22",
      category: "Endometrium",
      level: "student",
      question: "Intrauterine device on US — document:",
      options: ["Nothing", "Position relative to fundus/endometrium", "Only liver", "CA-125"],
      correctIndex: 1,
      explanation: "AIUM female pelvis: IUD location mandatory if present.",
      sourceId: "radiopaedia",
    },
    {
      id: "sp-q23",
      category: "Obstetrics",
      level: "student",
      question: "Breech presentation at 37 weeks —",
      options: ["Always vaginal", "Discuss ECV / cesarean per protocol", "No ultrasound", "Ignore"],
      correctIndex: 1,
      explanation: "Term breech management per local guidelines.",
      sourceId: "isuog",
    },
    {
      id: "sp-q24",
      category: "Screening",
      level: "doctor",
      question: "Integrated test vs NIPT: NIPT лучше для —",
      options: ["T21/T18/T13 detection rate", "Spina bifida", "Placenta grade", "Breast BI-RADS"],
      correctIndex: 0,
      explanation: "NIPT — aneuploidy screening; not structural anomaly test.",
      sourceId: "isuog",
    },
    {
      id: "sp-q25",
      category: "Gynecology",
      level: "doctor",
      question: "Deep endometriosis (DIE) on TVUS — typical site:",
      options: ["Thyroid", "Rectovaginal septum / uterosacral", "Carotid", "Patella"],
      correctIndex: 1,
      explanation: "IDEA consensus: posterior compartment DIE.",
      sourceId: "isuog",
    },
  ],
};
