import type { AppointmentCalculator } from "./types";

/** Референсный список OblCalc (19 пунктов) — ключи refKey */
export const REFERENCE_CALCULATOR_KEYS = [
  "ga-menstruation",
  "ga-ultrasound",
  "ga-ivf",
  "ga-movement",
  "ga-antenatal-visit",
  "maternity-leave",
  "ga-from-edd",
  "ga-crl",
  "ga-fetometry",
  "efw-maternal-anthropometry",
  "efw-rudakov",
  "bishop-score",
  "vbac-pre-labor",
  "vbac-in-labor",
  "breast-cancer-risk",
  "cervical-cancer-risk",
  "cin-follow-up",
  "ovarian-cancer-risk",
  "pregnancy-medications",
] as const;

export type ReferenceCalculatorKey = (typeof REFERENCE_CALCULATOR_KEYS)[number];

/** Калькуляторы для экрана «Для приёма врача» + референс OblCalc */
export const APPOINTMENT_CALCULATORS: AppointmentCalculator[] = [
  // —— Срок беременности ——
  {
    id: "ga-lmp",
    refKey: "ga-menstruation",
    title: "Срок беременности по менструации",
    description: "ПМП → срок сегодня, ПДР (Негеле), окна скринингов",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=lmp",
    icon: "calendar",
    frequentAtAppointment: true,
    searchTerms: ["пмп", "менструация", "пдр", "негеле"],
  },
  {
    id: "ga-us",
    refKey: "ga-ultrasound",
    title: "Срок беременности по УЗИ",
    description: "Дата исследования + срок на момент осмотра → ПДР",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=us",
    icon: "ultrasound",
    frequentAtAppointment: true,
    searchTerms: ["узи", "гестационный возраст"],
  },
  {
    id: "ga-ivf",
    refKey: "ga-ivf",
    title: "Срок беременности по овуляции/ЭКО",
    description: "ПДР от даты овуляции или переноса эмбриона (D3/D5)",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=ivf",
    icon: "egg",
    searchTerms: ["эко", "перенос", "овуляция", "ivf"],
  },
  {
    id: "ga-movement",
    refKey: "ga-movement",
    title: "Срок беременности по шевелениям плода",
    description: "Ориентир по первым шевелениям (18–22 нед.)",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=movement",
    icon: "baby",
    searchTerms: ["шевеления", "движения плода"],
  },
  {
    id: "ga-antenatal",
    refKey: "ga-antenatal-visit",
    title: "Срок беременности по явке в женскую консультацию",
    description: "Дата постановки на учёт + срок на момент явки",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=antenatal",
    icon: "hospital",
    searchTerms: ["жк", "учёт", "консультация"],
  },
  {
    id: "maternity-leave",
    refKey: "maternity-leave",
    title: "Сроки декретного отпуска",
    description: "Ориентиры начала декрета по ПДР (ТК РФ, упрощ.)",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=dekret",
    icon: "stroller",
    searchTerms: ["декрет", "отпуск", "бир"],
  },
  {
    id: "ga-edd",
    refKey: "ga-from-edd",
    title: "Срок беременности по предполагаемой дате родов",
    description: "ПДР → оценка ПМП и срок на сегодня",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=edd",
    icon: "calendar-back",
    frequentAtAppointment: true,
    searchTerms: ["пдр", "обратный расчёт", "edd"],
  },
  {
    id: "ga-crl",
    refKey: "ga-crl",
    title: "Срок беременности по КТР (I триместр)",
    description: "CRL мм + дата УЗИ → срок, ПДР, скрининги",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=crl",
    icon: "fetus-scan",
    frequentAtAppointment: true,
    searchTerms: ["ктр", "crl", "копчико-теменной"],
  },
  {
    id: "ga-feto",
    refKey: "ga-fetometry",
    title: "Срок беременности по фетометрии (II триместр)",
    description: "BPD / HC / FL / AC → срок на дату УЗИ и ПДР",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/calculators/ob?tab=feto",
    icon: "fetus-scan",
    searchTerms: ["фетометрия", "bpd", "биометрия"],
  },

  // —— Масса плода ——
  {
    id: "efw-hadlock",
    title: "Предполагаемая масса плода (Hadlock)",
    description: "EFW по BPD/HC/AC/FL — формулы Hadlock III/IV",
    category: "fetal-weight",
    status: "implemented",
    webHref: "/calculators/fetal-weight",
    icon: "scale",
    frequentAtAppointment: true,
    searchTerms: ["efw", "масса", "hadlock", "зрп"],
  },
  {
    id: "efw-maternal",
    refKey: "efw-maternal-anthropometry",
    title: "Предполагаемая масса плода по антропометрии матери",
    description: "Оценка EFW по росту/весу матери и ВДМ",
    category: "fetal-weight",
    status: "implemented",
    webHref: "/calculators/fetal-weight",
    icon: "scale",
    searchTerms: ["антропометрия", "имт матери"],
  },
  {
    id: "efw-rudakov",
    refKey: "efw-rudakov",
    title: "Метод Рудакова",
    description: "EFW = (ВДМ − n) × ОЖ по предлежанию",
    category: "fetal-weight",
    status: "implemented",
    webHref: "/calculators/fetal-weight",
    icon: "scale",
    searchTerms: ["рудаков", "живот", "вдм"],
  },

  // —— Акушерские ——
  {
    id: "bishop",
    refKey: "bishop-score",
    title: "Шкала Бишопа",
    description: "Оценка созревания шейки перед индукцией родов",
    category: "obstetric",
    status: "implemented",
    webHref: "/calculators/bishop",
    icon: "circle",
    frequentAtAppointment: true,
    searchTerms: ["bishop", "бишоп", "индукция", "созревание"],
  },
  {
    id: "vbac-pre",
    refKey: "vbac-pre-labor",
    title: "Вагинальные роды после кесарева сечения (до родов)",
    description: "Стратификация риска TOLAC / VBAC до начала родов",
    category: "obstetric",
    status: "implemented",
    webHref: "/calculators/vbac",
    icon: "scar",
    frequentAtAppointment: true,
    searchTerms: ["vbac", "tolac", "кс", "рубец"],
  },
  {
    id: "vbac-labor",
    refKey: "vbac-in-labor",
    title: "Вагинальные роды после кесарева сечения (в родах)",
    description: "Мониторинг и решения при родах после КС",
    category: "obstetric",
    status: "implemented",
    webHref: "/calculators/vbac",
    icon: "scar",
    searchTerms: ["vbac", "роды", "рубец на матке"],
  },

  // —— Гинекологические ——
  {
    id: "breast-risk",
    refKey: "breast-cancer-risk",
    title: "Риск рака молочной железы",
    description: "Образовательный чеклист факторов риска РМЖ",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/breast-risk",
    icon: "breast",
    searchTerms: ["мж", "рак груди", "gail"],
  },
  {
    id: "cervical-risk",
    refKey: "cervical-cancer-risk",
    title: "Риск рака шейки матки",
    description: "Стратификация риска РШМ по факторам и скринингу",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/cervical-cancer-risk",
    icon: "cervix",
    searchTerms: ["ршм", "впч", "цитология"],
  },
  {
    id: "cin-follow-up",
    refKey: "cin-follow-up",
    title: "Наблюдение после кольпоскопии или лечения CIN",
    description: "Интервалы наблюдения ASCCP / КР РФ после CIN",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/cin-follow-up",
    icon: "colposcopy",
    searchTerms: ["cin", "наблюдение", "asccp", "leep"],
  },
  {
    id: "ovarian-risk",
    refKey: "ovarian-cancer-risk",
    title: "Риск рака яичников",
    description: "Эпидемиологическая стратификация / семейный анамнез",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/ovarian-cancer-risk",
    icon: "ovary",
    searchTerms: ["яичник", "brca", "o-rads"],
  },

  // —— Справочники ——
  {
    id: "pregnancy-meds",
    refKey: "pregnancy-medications",
    title: "Лекарства при беременности",
    description: "Справочник безопасности препаратов в беременности",
    category: "reference",
    status: "implemented",
    webHref: "/calculators/pregnancy-medications",
    icon: "pill",
    searchTerms: ["лекарства", "беременность", "fda", "категория"],
  },
];

/** Калькуляторы вне референсного списка, но доступные в проекте */
export const EXTRA_PROJECT_CALCULATORS: AppointmentCalculator[] = [
  {
    id: "o-rads",
    title: "O-RADS US",
    description: "O-RADS US v2022 + IOTA 2026 — яичник на приёме",
    category: "gynecologic",
    status: "implemented",
    webHref: "/tools/calc/rads/o-rads",
    icon: "ovary",
    searchTerms: ["o-rads", "iota", "киста"],
  },
  {
    id: "bi-rads",
    title: "МЖ · BI-RADS",
    description: "УЗИ и ММГ молочных желёз · для врачей",
    category: "gynecologic",
    status: "implemented",
    webHref: "/tools/calc/rads/bi-rads",
    icon: "breast",
    searchTerms: ["bi-rads", "мж", "маммография", "ммг"],
  },
  {
    id: "colposcopy",
    title: "Кольпоскопия · Swede Score",
    description: "Протокол, 5 признаков IFCPC, риск CIN 2+",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/colposcopy",
    icon: "colposcopy",
  },
  {
    id: "cervical-length",
    title: "Длина шейки матки (CL)",
    description: "Скрининг 16–24 нед, воронка, sludge",
    category: "obstetric",
    status: "implemented",
    webHref: "/calculators/cervical-length",
    icon: "cervix",
  },
  {
    id: "endometrium",
    title: "Эндометрий · ISUOG / КР РФ",
    description: "M-эхо, пороги, очаг, тамоксифен",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/endometrium",
    icon: "cervix",
  },
  {
    id: "pop-q",
    title: "POP-Q · русская версия",
    description: "Стадирование пролапса по точкам Aa/Ba/C/D",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/pop-q",
    icon: "circle",
  },
  {
    id: "elastography",
    title: "Эластография",
    description: "Strain / SWE — шейка, миометрий, яичники, МЖ",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/elastography",
    icon: "ultrasound",
  },
  {
    id: "ti-rads",
    title: "TI-RADS ЩЖ",
    description: "ACR TI-RADS · Анализ → Доклад → Store · ТАБ",
    category: "gynecologic",
    status: "implemented",
    webHref: "/tools/calc/rads/ti-rads",
    icon: "circle",
  },
  {
    id: "fmf",
    title: "FMF · скрининг I–III триместра",
    description: "Малый срок, допплер, шейка, рубец, EFW",
    category: "pregnancy-term",
    status: "implemented",
    webHref: "/assistant/fmf",
    icon: "fetus-scan",
  },
  {
    id: "ln-rads",
    title: "LN-RADS",
    description: "Лимфоузлы · УЗИ (Intelligence Suite + mobile prototype)",
    category: "gynecologic",
    status: "implemented",
    webHref: "/calculators/ln-rads",
    icon: "circle",
  },
  {
    id: "figo",
    title: "FIGO fibroid typing",
    description: "Morphology / mural mapping → 3D матка",
    category: "gynecologic",
    status: "implemented",
    webHref: "/uterus-3d",
    icon: "circle",
  },
];

export function getAppointmentCalculatorById(id: string): AppointmentCalculator | undefined {
  return APPOINTMENT_CALCULATORS.find((c) => c.id === id) ?? EXTRA_PROJECT_CALCULATORS.find((c) => c.id === id);
}

export function getFrequentAtAppointment(): AppointmentCalculator[] {
  return APPOINTMENT_CALCULATORS.filter((c) => c.frequentAtAppointment);
}

export function getByCategory(category: AppointmentCalculator["category"]): AppointmentCalculator[] {
  return APPOINTMENT_CALCULATORS.filter((c) => c.category === category);
}
