import type { FetalAnomalyRecord } from "./types";

/** Дополнение до 65 ВПР по протоколу Емельяненко (views excludesAnomalyIds). */
export const FETAL_ANATOMY_ANOMALIES_EXTRA: FetalAnomalyRecord[] = [
  {
    id: "acc",
    name: "Agenesis of corpus callosum",
    nameRu: "Агенезия мозолистого тела (АМТ)",
    definition: "Отсутствие или гипопlasia corpus callosum.",
    embryology: "Нарушение формирования commissural fibers между hemispheres.",
    ultrasoundFindings: ["Absent CSP on transthalamic", "Colpocephaly", "Parallel lateral ventricles", "Racing car sign"],
    differentialDiagnosis: ["HPE", "Porencephaly", "Normal variant CSP size"],
    prognosis: "Variable — isolated may be mild; syndromic often severe.",
    associatedSyndromes: ["Aicardi", "Trisomy 18", "Prenatal alcohol exposure"],
    recommendedFollowUp: ["MRI brain", "Karyotype/microarray", "Genetics consult"],
    relatedViewIds: ["view-04-transventricular", "view-05-transthalamic", "view-06-transcerebellar"],
    severity: "major",
    searchableText: "ACC agenesis corpus callosum АМТ CSP",
  },
  {
    id: "occipital-encephalocele",
    name: "Occipital encephalocele",
    nameRu: "Затылочное эncephalocele",
    definition: "Грыжа оболочек и brain tissue через дефект черепа в occipital region.",
    embryology: "Failed closure of occipital neural tube / skull.",
    ultrasoundFindings: ["Cystic/solid mass posterior to skull", "Bone defect", "May distort posterior fossa"],
    differentialDiagnosis: ["Meningocele", "Cystic hygroma posterior", "Amniotic band"],
    prognosis: "Depends on herniated content and hydrocephalus.",
    associatedSyndromes: ["Meckel-Gruber", "Walker-Warburg"],
    recommendedFollowUp: ["MRI", "Karyotype", "Neurosurgery planning"],
    relatedViewIds: ["view-04-transventricular", "view-05-transthalamic", "view-06-transcerebellar"],
    severity: "critical",
    searchableText: "encephalocele occipital brain hernia",
  },
  {
    id: "subcutaneous-edema",
    name: "Subcutaneous edema / hydrops marker",
    nameRu: "Отёк подкожно-жировой клетчатки",
    definition: "Утолщение subcutaneous layer — marker of fetal hydrops or aneuploidy.",
    ultrasoundFindings: ["Skin edema ≥5 mm", "May accompany pleural/pericardial effusion", "Ascites"],
    differentialDiagnosis: ["Early nuchal edema", "Normal skin in oblique plane"],
    prognosis: "Poor if generalized hydrops unless treatable cause.",
    associatedSyndromes: ["Turner", "CMV", "Anemia", "Cardiac failure"],
    recommendedFollowUp: ["Complete hydrops workup", "Middle cerebral artery PSV", "Echocardiography"],
    relatedViewIds: ["view-04-transventricular", "view-07a-apical-four-chamber", "view-11-umbilical-vein"],
    severity: "major",
    searchableText: "subcutaneous edema hydrops skin",
  },
  {
    id: "cystic-hygroma",
    name: "Cystic hygroma",
    nameRu: "Кистозная гигрома",
    definition: "Multiseptated fluid collection in posterior neck/occipital region.",
    embryology: "Lymphatic maldevelopment.",
    ultrasoundFindings: ["Septated cystic neck mass", "Increased NT", "May progress to hydrops"],
    differentialDiagnosis: ["Encephalocele", "Cystic teratoma neck"],
    prognosis: "High aneuploidy risk; resolution may indicate better outcome.",
    associatedSyndromes: ["Turner", "Noonan", "Trisomy 21"],
    recommendedFollowUp: ["Karyotype", "Fetal echo", "Serial scans"],
    relatedViewIds: ["view-06-transcerebellar"],
    severity: "major",
    searchableText: "cystic hygroma lymph neck",
  },
  {
    id: "increased-nuchal-fold",
    name: "Increased nuchal fold thickness",
    nameRu: "Увеличение толщины шейной складки",
    definition: "Thickened soft tissue posterior neck in II trimester.",
    ultrasoundFindings: ["NF ≥6 mm at 16–22 weeks (typical cut-off)", "May be isolated marker"],
    differentialDiagnosis: ["Cystic hygroma resolved", "Posterior occipital encephalocele"],
    prognosis: "Increased aneuploidy risk if isolated.",
    associatedSyndromes: ["Trisomy 21", "Turner"],
    recommendedFollowUp: ["Karyotype discussion", "Detailed anatomy", "Fetal echo"],
    relatedViewIds: ["view-06-transcerebellar"],
    severity: "moderate",
    searchableText: "nuchal fold thickness NF neck",
  },
  {
    id: "posterior-fossa-cyst",
    name: "Posterior fossa cyst / Blake pouch",
    nameRu: "Киста задней черепной ямки",
    definition: "Cystic structure in posterior fossa — spectrum from benign to Dandy-Walker.",
    ultrasoundFindings: ["Cyst in posterior fossa", "Vermis position key", "Communication with 4th ventricle"],
    differentialDiagnosis: ["Mega cisterna magna", "Dandy-Walker malformation", "Arachnoid cyst"],
    prognosis: "Benign if isolated Blake pouch; poor if true Dandy-Walker with vermian agenesis.",
    recommendedFollowUp: ["MRI posterior fossa", "Genetics if syndromic features"],
    relatedViewIds: ["view-06-transcerebellar"],
    severity: "major",
    searchableText: "posterior fossa cyst Blake pouch vermis",
  },
  {
    id: "cardiac-axis-shift",
    name: "Abnormal cardiac axis (CAPV)",
    nameRu: "Смещение оси сердца (КАПРВ)",
    definition: "Deviation of cardiac apex from normal ~45° leftward orientation.",
    ultrasoundFindings: ["Apical axis <30° or >75°", "May indicate thoracic mass or situs anomaly"],
    differentialDiagnosis: ["Normal oblique plane", "Diaphragmatic hernia", "Pulmonary hypoplasia"],
    prognosis: "Depends on underlying cause.",
    associatedSyndromes: ["Heterotaxy", "CDH"],
    recommendedFollowUp: ["Repeat 4CV", "Detailed echo", "Thoracic survey"],
    relatedViewIds: ["view-03-trunk-coronal", "view-07a-apical-four-chamber"],
    severity: "moderate",
    searchableText: "cardiac axis CAPV apex heart",
  },
  {
    id: "echogenic-bowel",
    name: "Echogenic bowel",
    nameRu: "Эхогенный кишечник",
    definition: "Bowel echogenicity equal to or greater than bone.",
    ultrasoundFindings: ["Hyperechoic loops in abdomen", "May be transient"],
    differentialDiagnosis: ["Normal peristalsis artifact", "CF", "CMV", "IUGR"],
    prognosis: "Often resolves; persistent increases infection/aneuploidy risk.",
    associatedSyndromes: ["Cystic fibrosis", "Trisomy 21"],
    recommendedFollowUp: ["TORCH", "CF carrier testing", "Serial scans"],
    relatedViewIds: ["view-03-trunk-coronal"],
    severity: "moderate",
    searchableText: "echogenic bowel hyperechoic intestine",
  },
  {
    id: "esophageal-atresia",
    name: "Esophageal atresia without fistula",
    nameRu: "Атрезия пищевода без фистулы",
    definition: "Discontinuous esophagus without tracheoesophageal connection.",
    ultrasoundFindings: ["Small or absent stomach bubble", "Polyhydramnios possible", "Upper pouch not always seen"],
    differentialDiagnosis: ["Stomach not yet filled", "Swallowing delay"],
    prognosis: "Surgical repair required; VACTERL association.",
    associatedSyndromes: ["VACTERL", "Trisomy 18"],
    recommendedFollowUp: ["Repeat stomach assessment", "Amniotic fluid index", "Neonatal surgery plan"],
    relatedViewIds: ["view-03-trunk-coronal", "view-11-umbilical-vein"],
    severity: "major",
    searchableText: "esophageal atresia stomach bubble",
  },
  {
    id: "diaphragmatic-hernia-left",
    name: "Left congenital diaphragmatic hernia",
    nameRu: "Левосторонняя диафрагмальная грыжа",
    definition: "Abdominal organs herniate into thorax through diaphragmatic defect.",
    ultrasoundFindings: ["Stomach/liver in chest", "Mediastinal shift", "Small abdomen", "Polyhydramnios"],
    differentialDiagnosis: ["Congenital lung malformation", "Eventration"],
    prognosis: "Lung hypoplasia determines outcome; severity scoring (LHR).",
    associatedSyndromes: ["Trisomy 18", "Fryns"],
    recommendedFollowUp: ["Fetal MRI lung volumes", "ECMO center delivery", "Echo"],
    relatedViewIds: ["view-03-trunk-coronal"],
    severity: "critical",
    searchableText: "CDH diaphragmatic hernia Bochdalek",
  },
  {
    id: "ectopia-cordis",
    name: "Ectopia cordis",
    nameRu: "Эctopia cordis",
    definition: "Heart partially or completely outside thoracic cavity.",
    ultrasoundFindings: ["Heart outside chest wall", "Associated sternal defect", "Abnormal axis"],
    differentialDiagnosis: ["Pentalogy of Cantrell component", "Giant omphalocele"],
    prognosis: "Very poor unless mild thoracic variant.",
    associatedSyndromes: ["Pentalogy of Cantrell", "Amniotic band"],
    recommendedFollowUp: ["Fetal echo", "Genetics", "Termination counseling if severe"],
    relatedViewIds: ["view-07a-apical-four-chamber"],
    severity: "critical",
    searchableText: "ectopia cordis heart outside chest",
  },
  {
    id: "hlhs-left",
    name: "Hypoplastic left heart syndrome",
    nameRu: "Синдром гипоплазии левых отделов (ГЛОС)",
    definition: "Underdevelopment of left heart structures with systemic flow via ductus.",
    ultrasoundFindings: ["Small LV/aortic root", "Reversed foramen shunt", "Small ascending aorta"],
    differentialDiagnosis: ["Critical aortic stenosis", "Coarctation with VSD"],
    prognosis: "Requires staged palliation or transplant.",
    associatedSyndromes: ["Turner", "22q11"],
    recommendedFollowUp: ["Expert fetal echo", "Delivery at cardiac center"],
    relatedViewIds: ["view-07a-apical-four-chamber", "view-10-three-vessel-trachea"],
    severity: "critical",
    searchableText: "HLHS hypoplastic left heart",
  },
  {
    id: "hypoplastic-right-heart",
    name: "Hypoplastic right heart syndrome",
    nameRu: "Гипоплазия правых отделов сердца",
    definition: "Underdevelopment of RV, pulmonary valve, or main PA.",
    ultrasoundFindings: ["Small RV/PA", "Tricuspid hypoplasia", "Larger LV compensatory"],
    differentialDiagnosis: ["Pulmonary atresia with intact septum", "TOF with severe PS"],
    prognosis: "Palliative surgery required.",
    recommendedFollowUp: ["Fetal echo specialist", "Delivery planning"],
    relatedViewIds: ["view-07a-apical-four-chamber"],
    severity: "critical",
    searchableText: "hypoplastic right heart HRHS",
  },
  {
    id: "pericardial-effusion",
    name: "Pericardial effusion (significant)",
    nameRu: "Перикардиальный выпот (выраженный)",
    definition: "Fluid in pericardial sac — marker of hydrops or cardiac failure.",
    ultrasoundFindings: ["Anechoic rim around heart", ">2 mm often significant", "May be isolated transient"],
    differentialDiagnosis: ["Normal thin film", "Pleural effusion adjacent"],
    prognosis: "Depends on etiology — infection, anemia, structural heart disease.",
    recommendedFollowUp: ["MCA PSV", "TORCH", "Echo", "Hydrops protocol"],
    relatedViewIds: ["view-07a-apical-four-chamber"],
    severity: "major",
    searchableText: "pericardial effusion hydrops heart",
  },
  {
    id: "pleural-effusion",
    name: "Pleural effusion (significant)",
    nameRu: "Плевральная эффузия (выраженная)",
    definition: "Fluid in pleural space — component of hydrops.",
    ultrasoundFindings: ["Anechoic space around lungs", "Bilateral worse prognosis"],
    differentialDiagnosis: ["CDH", "Congenital pulmonary malformation"],
    prognosis: "Part of non-immune or immune hydrops workup.",
    recommendedFollowUp: ["Hydrops etiology panel", "Intrauterine transfusion if anemia"],
    relatedViewIds: ["view-07a-apical-four-chamber"],
    severity: "major",
    searchableText: "pleural effusion hydrops lung",
  },
  {
    id: "vsd-moderate",
    name: "Ventricular septal defect (moderate/severe)",
    nameRu: "Дефект межжелудочковой перегородки (ДМЖП)",
    definition: "Defect in interventricular septum with shunt.",
    ultrasoundFindings: ["Septal dropout on 4CV", "Color flow across septum", "May be sole lesion or part of complex CHD"],
    differentialDiagnosis: ["Moderator band artifact", "AV canal"],
    prognosis: "Isolated small VSD often closes; large may need surgery.",
    associatedSyndromes: ["Trisomy 21", "22q11"],
    recommendedFollowUp: ["Fetal echo", "Postnatal echo", "Genetics if syndromic"],
    relatedViewIds: ["view-07a-apical-four-chamber", "view-07b-lateral-four-chamber", "view-09b-crossing-outflow"],
    severity: "major",
    searchableText: "VSD ventricular septal defect",
  },
  {
    id: "single-ventricle",
    name: "Single ventricle physiology",
    nameRu: "Однокамерное сердце",
    definition: "Univentricular heart — one functional ventricle receiving both AV valves.",
    ultrasoundFindings: ["Single large ventricle", "Common AV valve often", "Great vessel abnormality"],
    differentialDiagnosis: ["Unbalanced AV canal", "HLHS variant"],
    prognosis: "Fontan palliation pathway; complex lifelong care.",
    recommendedFollowUp: ["Expert fetal echo", "Genetics", "Cardiac center delivery"],
    relatedViewIds: ["view-07a-apical-four-chamber"],
    severity: "critical",
    searchableText: "single ventricle univentricular heart",
  },
  {
    id: "aortic-stenosis",
    name: "Aortic stenosis (severe)",
    nameRu: "Аортальный стеноз (выраженный)",
    definition: "Obstruction at aortic valve or LVOT.",
    ultrasoundFindings: ["Thickened/dome aortic valve", "Turbulent LVOT flow", "LV hypertrophy or hypoplasia"],
    differentialDiagnosis: ["Coarctation", "HLHS evolving"],
    prognosis: "May evolve to HLHS in utero; balloon valvuloplasty option.",
    recommendedFollowUp: ["Serial echo", "Delivery at cardiac center"],
    relatedViewIds: ["view-08-lvot", "view-10-three-vessel-trachea"],
    severity: "major",
    searchableText: "aortic stenosis LVOT",
  },
  {
    id: "aorta-as-rider",
    name: "Overriding aorta (TOF marker)",
    nameRu: "Аорта-«наездница»",
    definition: "Aorta overrides ventricular septum — classic TOF component.",
    ultrasoundFindings: ["Aorta straddles septum on LVOT/RVOT views", "VSD beneath", "Anterior aorta"],
    differentialDiagnosis: ["DORV", "Truncus arteriosus"],
    prognosis: "Surgical repair in infancy.",
    associatedSyndromes: ["22q11", "DiGeorge"],
    recommendedFollowUp: ["Fetal echo", "22q11 FISH if indicated"],
    relatedViewIds: ["view-08-lvot"],
    severity: "major",
    searchableText: "overriding aorta TOF tetralogy",
  },
  {
    id: "tof",
    name: "Tetralogy of Fallot",
    nameRu: "Тетрада Фалло",
    definition: "VSD + overriding aorta + RVOT obstruction + RV hypertrophy.",
    ultrasoundFindings: ["Malaligned VSD", "Overriding aorta", "Narrow RVOT/PA"],
    differentialDiagnosis: ["Pulmonary atresia with VSD", "DORV"],
    prognosis: "Good with surgical repair; depends on pulmonary anatomy.",
    associatedSyndromes: ["22q11", "Trisomy 21"],
    recommendedFollowUp: ["Fetal echo", "Delivery at cardiac center"],
    relatedViewIds: ["view-09b-crossing-outflow", "view-08-lvot"],
    severity: "major",
    searchableText: "TOF tetralogy Fallot",
  },
  {
    id: "pulmonary-atresia",
    name: "Pulmonary atresia",
    nameRu: "Атрезия лёгочного ствола",
    definition: "No forward flow through pulmonary valve — ductal-dependent pulmonary circulation.",
    ultrasoundFindings: ["Atretic pulmonary valve", "No RVOT flow", "Reverse ductal flow to PA"],
    differentialDiagnosis: ["Critical pulmonary stenosis", "TGA with PS"],
    prognosis: "Staged surgery; depends on RV size and coronaries.",
    recommendedFollowUp: ["Expert fetal echo", "Prostaglandin plan at birth"],
    relatedViewIds: ["view-09-rvot", "view-10-three-vessel-trachea"],
    severity: "critical",
    searchableText: "pulmonary atresia PA",
  },
  {
    id: "pulmonary-stenosis-severe",
    name: "Pulmonary stenosis (severe)",
    nameRu: "Стеноз лёгочного ствола (выраженный)",
    definition: "Obstruction at pulmonary valve or main PA.",
    ultrasoundFindings: ["Domed/thickened pulmonary valve", "Post-stenotic dilation", "RV hypertrophy"],
    differentialDiagnosis: ["Pulmonary atresia", "TOF"],
    prognosis: "Valvuloplasty or surgery depending on severity.",
    recommendedFollowUp: ["Fetal echo", "Postnatal cardiology"],
    relatedViewIds: ["view-09-rvot"],
    severity: "major",
    searchableText: "pulmonary stenosis PS",
  },
  {
    id: "interrupted-aortic-arch",
    name: "Interrupted aortic arch",
    nameRu: "Перерыв дуги аорты",
    definition: "Discontinuity of aortic arch — ductal-dependent systemic flow.",
    ultrasoundFindings: ["Narrow/absent isthmus", "VSD often", "Abnormal 3VT"],
    differentialDiagnosis: ["Coarctation", "HLHS"],
    prognosis: "Neonatal surgery required.",
    associatedSyndromes: ["22q11 deletion"],
    recommendedFollowUp: ["FISH 22q11", "Fetal echo", "Cardiac center delivery"],
    relatedViewIds: ["view-10-three-vessel-trachea"],
    severity: "critical",
    searchableText: "interrupted aortic arch IAA 22q11",
  },
  {
    id: "persistent-lsv",
    name: "Persistent left superior vena cava",
    nameRu: "Персистирующая левая верхняя полая вена",
    definition: "Left SVC drains to coronary sinus — common variant or associated with CHD.",
    ultrasoundFindings: ["Extra vessel left of heart on 3VT", "Coronary sinus dilated"],
    differentialDiagnosis: ["Normal variant isolated", "Total anomalous pulmonary venous return"],
    prognosis: "Benign if isolated; workup if other anomalies.",
    recommendedFollowUp: ["Complete echo", "Karyotype if other findings"],
    relatedViewIds: ["view-10-three-vessel-trachea"],
    severity: "minor",
    searchableText: "persistent left SVC PLSVC",
  },
  {
    id: "right-aortic-arch",
    name: "Right aortic arch",
    nameRu: "Правая дуга аорты",
    definition: "Aortic arch courses to the right of trachea.",
    ultrasoundFindings: ["Aorta right of trachea on 3VT", "May form vascular ring"],
    differentialDiagnosis: ["Mirror image normal with situs inversus"],
    prognosis: "Symptomatic if ring compresses airway/esophagus.",
    associatedSyndromes: ["22q11", "Tetralogy of Fallot"],
    recommendedFollowUp: ["Fetal echo", "Postnatal airway assessment if ring suspected"],
    relatedViewIds: ["view-10-three-vessel-trachea"],
    severity: "moderate",
    searchableText: "right aortic arch RAA vascular ring",
  },
  {
    id: "ascites",
    name: "Fetal ascites",
    nameRu: "Асцит плода",
    definition: "Free fluid in peritoneal cavity — hydrops component.",
    ultrasoundFindings: ["Fluid around bowel/liver", "May precede full hydrops"],
    differentialDiagnosis: ["Normal bowel loops", "Urinary ascites from bladder rupture"],
    prognosis: "Etiology-dependent — infection, cardiac, anemia.",
    recommendedFollowUp: ["Hydrops workup", "MCA PSV", "Echo"],
    relatedViewIds: ["view-11-umbilical-vein", "view-12-cord-insertion"],
    severity: "major",
    searchableText: "ascites hydrops abdomen fluid",
  },
  {
    id: "duodenal-atresia",
    name: "Duodenal atresia",
    nameRu: "Дуоденальная атрезия",
    definition: "Obstruction at duodenum — classic double bubble sign.",
    ultrasoundFindings: ["Two fluid-filled bubbles (stomach + proximal duodenum)", "Polyhydramnios", "No connecting channel"],
    differentialDiagnosis: ["Stomach + cystic structure", "Antral web"],
    prognosis: "Surgical repair; strong Trisomy 21 association.",
    associatedSyndromes: ["Trisomy 21", "VACTERL"],
    recommendedFollowUp: ["Karyotype", "Detailed anatomy", "Neonatal surgery plan"],
    relatedViewIds: ["view-11-umbilical-vein"],
    severity: "major",
    searchableText: "duodenal atresia double bubble",
  },
  {
    id: "arpkd",
    name: "Autosomal recessive polycystic kidney disease",
    nameRu: "Аутосомно-рецессивное поликистозное заболевание почек",
    definition: "Inherited cystic kidney disease with echogenic enlarged kidneys.",
    ultrasoundFindings: ["Markedly enlarged echogenic kidneys", "Loss of corticomedullary differentiation", "Oligohydramnios"],
    differentialDiagnosis: ["MCDK", "Bilateral hydronephrosis"],
    prognosis: "Pulmonary hypoplasia from oligohydramnios — often lethal neonatal.",
    recommendedFollowUp: ["Genetic counseling", "Family history", "Amniotic fluid surveillance"],
    relatedViewIds: ["view-13-kidneys"],
    severity: "critical",
    searchableText: "ARPKD polycystic kidney recessive",
  },
  {
    id: "mcdk",
    name: "Multicystic dysplastic kidney",
    nameRu: "Мультикистозная дисплазия почки",
    definition: "Non-functioning kidney replaced by non-communicating cysts.",
    ultrasoundFindings: ["Cluster of cysts no central pelvis", "No normal cortex", "May be unilateral"],
    differentialDiagnosis: ["Hydronephrosis", "ARPKD bilateral"],
    prognosis: "Unilateral often good; bilateral incompatible with survival.",
    recommendedFollowUp: ["Confirm contralateral kidney", "Postnatal urology"],
    relatedViewIds: ["view-13-kidneys"],
    severity: "major",
    searchableText: "MCDK multicystic dysplastic kidney",
  },
  {
    id: "achondroplasia-suspect",
    name: "Achondroplasia (suspicion)",
    nameRu: "Подозрение на ахондроплазию",
    definition: "Most common non-lethal skeletal dysplasia — rhizomelic limb shortening.",
    ultrasoundFindings: ["Short femur with normal head size", "Trident hand (late)", "Narrow thorax"],
    differentialDiagnosis: ["Constitutional short femur", "Other skeletal dysplasias"],
    prognosis: "Non-lethal; FGFR3 mutation in most.",
    recommendedFollowUp: ["Biometry all long bones", "Genetics FGFR3", "Thoracic circumference"],
    relatedViewIds: ["view-15-femur", "view-16-lower-limbs"],
    severity: "major",
    searchableText: "achondroplasia short femur FGFR3",
  },
  {
    id: "limb-reduction-transverse",
    name: "Transverse limb reduction defect",
    nameRu: "Поперечный редукционный порок конечности",
    definition: "Absent distal segment — amputation-like defect.",
    ultrasoundFindings: ["Truncated limb without distal bones", "May be unilateral", "Nubbin or short stump"],
    differentialDiagnosis: ["Amniotic band sequence", "Focal limb deficiency"],
    prognosis: "Prosthetics/orthopedics; band sequence may have other defects.",
    associatedSyndromes: ["Amniotic band", "Adams-Oliver"],
    recommendedFollowUp: ["Detailed band survey", "Genetics if bilateral/syndromic"],
    relatedViewIds: ["view-15-femur", "view-16-lower-limbs", "view-17-upper-limbs"],
    severity: "major",
    searchableText: "limb reduction transverse amputation",
  },
  {
    id: "hand-flexion-deformity",
    name: "Hand flexion deformity",
    nameRu: "Флексорная деформация кисти",
    definition: "Fixed flexed posture of fetal hand — may indicate neuromuscular or chromosomal disorder.",
    ultrasoundFindings: ["Persistently clenched/overflexed hand", "Overlapping fingers possible"],
    differentialDiagnosis: ["Normal transient flexion", "Trisomy 18 clenched hand"],
    prognosis: "Syndromic if bilateral fixed.",
    associatedSyndromes: ["Trisomy 18", "Fetal akinesia sequence"],
    recommendedFollowUp: ["Karyotype", "Movement assessment", "Muscle/nerve workup"],
    relatedViewIds: ["view-17-upper-limbs"],
    severity: "moderate",
    searchableText: "hand flexion clenched fingers",
  },
  {
    id: "cleft-lip-unilateral",
    name: "Cleft lip (unilateral)",
    nameRu: "Односторонняя расщелина губы",
    definition: "Failure of fusion of maxillary and medial nasal processes on one side.",
    ultrasoundFindings: ["Defect in upper lip coronal plane", "Alveolar notch possible"],
    differentialDiagnosis: ["Shadow artifact", "Median cleft"],
    prognosis: "Surgical repair excellent; palate involvement affects feeding/speech.",
    recommendedFollowUp: ["Detailed palate assessment", "Genetics if syndromic features"],
    relatedViewIds: ["view-18-upper-lip"],
    severity: "moderate",
    searchableText: "cleft lip unilateral face",
  },
  {
    id: "hypertelorism",
    name: "Hypertelorism",
    nameRu: "Гипертелоризм",
    definition: "Increased interorbital distance.",
    ultrasoundFindings: ["Wide spacing between orbits on transverse view", "May accompany midline defects"],
    differentialDiagnosis: ["Measurement plane error", "Frontal bossing"],
    prognosis: "Often syndromic — workup required.",
    associatedSyndromes: ["Hypertelorism-hypospadias", "Fetal hydrops syndromes", "Frontonasal dysplasia"],
    recommendedFollowUp: ["Facial profile", "Genetics", "Karyotype"],
    relatedViewIds: ["view-19-orbits"],
    severity: "moderate",
    searchableText: "hypertelorism wide eyes orbit",
  },
  {
    id: "hypotelorism",
    name: "Hypotelorism",
    nameRu: "Гипотелоризм",
    definition: "Decreased interorbital distance — midline forebrain marker.",
    ultrasoundFindings: ["Close-set orbits", "Often with HPE spectrum"],
    differentialDiagnosis: ["Oblique orbit plane"],
    prognosis: "Strongly associated with holoprosencephaly.",
    associatedSyndromes: ["Holoprosencephaly", "Trisomy 13"],
    recommendedFollowUp: ["Brain MRI", "Karyotype", "Facial survey"],
    relatedViewIds: ["view-19-orbits"],
    severity: "major",
    searchableText: "hypotelorism close eyes HPE",
  },
  {
    id: "anophthalmia",
    name: "Anophthalmia",
    nameRu: "Анофтальмия",
    definition: "Absence of ocular globe.",
    ultrasoundFindings: ["Empty orbit", "May be unilateral or bilateral"],
    differentialDiagnosis: ["Severe microphthalmia", "Oblique plane missing eye"],
    prognosis: "Blindness; syndromic workup.",
    associatedSyndromes: ["SOX2", "STXBP1", "Midline defects"],
    recommendedFollowUp: ["Genetics", "Brain MRI", "Prosthetic planning"],
    relatedViewIds: ["view-19-orbits"],
    severity: "major",
    searchableText: "anophthalmia absent eye",
  },
  {
    id: "cataract",
    name: "Congenital cataract",
    nameRu: "Катаракта",
    definition: "Opacification of fetal lens.",
    ultrasoundFindings: ["Echogenic lens", "Loss of clear anechoic lens center"],
    differentialDiagnosis: ["Normal lens reflex", "Microphthalmia"],
    prognosis: "Early surgery needed to prevent amblyopia.",
    associatedSyndromes: ["Congenital infections", "Galactosemia", "Trisomy 21"],
    recommendedFollowUp: ["TORCH", "Pediatric ophthalmology plan", "Metabolic screen neonatal"],
    relatedViewIds: ["view-19-orbits"],
    severity: "moderate",
    searchableText: "cataract lens opacity eye",
  },
  {
    id: "microphthalmia",
    name: "Microphthalmia",
    nameRu: "Микрофтальмия",
    definition: "Abnormally small eye.",
    ultrasoundFindings: ["Reduced orbit size", "Small lens/globe"],
    differentialDiagnosis: ["Anophthalmia", "Normal if oblique"],
    prognosis: "Visual impairment; syndromic associations common.",
    associatedSyndromes: ["CHARGE", "Trisomy 13"],
    recommendedFollowUp: ["Genetics", "Detailed brain and ear survey"],
    relatedViewIds: ["view-19-orbits"],
    severity: "major",
    searchableText: "microphthalmia small eye",
  },
  {
    id: "depressed-nasal-bridge",
    name: "Depressed nasal bridge",
    nameRu: "Вдавленная переносица",
    definition: "Flat midface profile — dysmorphic marker.",
    ultrasoundFindings: ["Reduced nasofrontal angle on profile", "May accompany micrognathia"],
    differentialDiagnosis: ["Off-profile angle", "Ethnic variant"],
    prognosis: "Syndromic evaluation if other anomalies.",
    associatedSyndromes: ["Trisomy 21", "Achondroplasia", "Fetal akinesia"],
    recommendedFollowUp: ["Full dysmorphology survey", "Genetics"],
    relatedViewIds: ["view-20-profile"],
    severity: "moderate",
    searchableText: "depressed nasal bridge flat nose profile",
  },
  {
    id: "proboscis",
    name: "Proboscis",
    nameRu: "Пробoscis",
    definition: "Abnormal tubular nose structure — severe midline facial malformation.",
    ultrasoundFindings: ["Single tubular proboscis above mouth", "Often with HPE"],
    differentialDiagnosis: ["Prominent nose normal variant"],
    prognosis: "Severe — usually HPE or trisomy 13.",
    associatedSyndromes: ["Holoprosencephaly", "Trisomy 13"],
    recommendedFollowUp: ["Brain MRI", "Karyotype", "Genetic counseling"],
    relatedViewIds: ["view-20-profile"],
    severity: "critical",
    searchableText: "proboscis nose midline HPE",
  },
];
