import type { FetalAnomalyRecord } from "./types";
import { FETAL_ANATOMY_ANOMALIES_EXTRA } from "./anomalies-extra";

const FETAL_ANATOMY_ANOMALIES_CORE: FetalAnomalyRecord[] = [
  {
    id: "anencephaly",
    name: "Anencephaly",
    nameRu: "Анэнцефалия",
    definition: "Отсутствие мajor части мозга и черепных костей.",
    embryology: "Нарушение закрытия невральной трубки в области будущего мозга.",
    ultrasoundFindings: ["Отсутствие calvarium", "Degenerate brain tissue at skull base", "Frog-eye or absent head contour"],
    differentialDiagnosis: ["Acraenia", "Severe hydrocephalus with skull"],
    prognosis: "Не совместимо с extrauterine life.",
    associatedSyndromes: ["Amniotic band (rare)"],
    recommendedFollowUp: ["Confirm diagnosis", "Genetic counseling", "Pregnancy management per law/ethics"],
    relatedViewIds: ["overview-1", "view-04-transventricular", "view-05-transthalamic"],
    severity: "critical",
    searchableText: "anencephaly анэнцефалия head brain",
  },
  {
    id: "iufd",
    name: "Intrauterine fetal demise",
    nameRu: "Внутриутробная гибель плода",
    definition: "Отсутствие жизненных признаков плода.",
    ultrasoundFindings: ["Absent cardiac activity", "Loss of movement", "Skull/spine collapse over time"],
    differentialDiagnosis: ["Temporary bradycardia — repeat scan"],
    prognosis: "Depends on etiology.",
    recommendedFollowUp: ["Confirm absence of cardiac activity", "Karyotype/placenta if indicated"],
    relatedViewIds: ["overview-1"],
    severity: "critical",
    searchableText: "IUFD demise death",
  },
  {
    id: "spina-bifida-open",
    name: "Open spina bifida",
    nameRu: "Открытая spina bifida",
    definition: "Дефект позвоночника с нарушением покровов и возможной грыжей.",
    ultrasoundFindings: ["Lemon sign (skull)", "Banana cerebellum", "Spinal defect with CSF/herniation"],
    differentialDiagnosis: ["Meningocele without neural defect", "Amniotic band"],
    prognosis: "Variable neurologic deficit; depends on level.",
    associatedSyndromes: ["Chiari II", "Hydrocephalus"],
    recommendedFollowUp: ["MRI fetal spine", "Neurosurgery consult", "Delivery planning"],
    relatedViewIds: ["view-01-spine-sagittal", "view-02-spine-coronal", "overview-2"],
    severity: "major",
    searchableText: "spina bifida open spine",
  },
  {
    id: "meningocele",
    name: "Meningocele",
    nameRu: "Менингоцеле",
    definition: "Грыжа оболочек без открытого neural tissue (или minimal).",
    ultrasoundFindings: ["Cystic sac posterior spine", "Intact skin possible"],
    differentialDiagnosis: ["Myelomeningocele", "Sacrococcygeal teratoma"],
    prognosis: "Better than open myelomeningocele if isolated.",
    recommendedFollowUp: ["Detailed spine survey", "Genetics"],
    relatedViewIds: ["view-01-spine-sagittal"],
    severity: "major",
    searchableText: "meningocele spine",
  },
  {
    id: "sacral-agenesis",
    name: "Sacral agenesis",
    nameRu: "Агенезия крестца",
    definition: "Отсутствие или гипопlasia sacral vertebrae.",
    ultrasoundFindings: ["Truncated spine", "Abnormal conus level", "Abnormal pelvis shape"],
    differentialDiagnosis: ["Caudal regression spectrum"],
    prognosis: "Bowel/bladder dysfunction risk.",
    associatedSyndromes: ["VACTERL", "Diabetes maternal"],
    recommendedFollowUp: ["Spine MRI", "Pediatric surgery/urology"],
    relatedViewIds: ["view-01-spine-sagittal", "view-02-spine-coronal", "overview-2"],
    severity: "major",
    searchableText: "sacral agenesis caudal",
  },
  {
    id: "sct",
    name: "Sacrococcygeal teratoma",
    nameRu: "Крестцово-копчиковая тератoma (ККТ)",
    definition: "Опухоль в области sacrum/coccyx.",
    ultrasoundFindings: ["Mixed solid-cystic mass at sacrum", "Vascular on Doppler", "Hydrops if large"],
    differentialDiagnosis: ["Meningocele", "Lipoma"],
    prognosis: "Depends on size, vascularity, malignant potential.",
    recommendedFollowUp: ["Serial growth", "Fetal surgery center if giant SCT"],
    relatedViewIds: ["view-01-spine-sagittal", "overview-2"],
    severity: "major",
    searchableText: "SCT teratoma sacrococcygeal",
  },
  {
    id: "ventriculomegaly",
    name: "Ventriculomegaly",
    nameRu: "Вентрикуломегалия",
    definition: "Расширение lateral ventricles beyond percentile threshold.",
    ultrasoundFindings: ["Atrial width ≥10 mm (typical II trim cut-off)", "Asymmetric ventricles possible"],
    differentialDiagnosis: ["Hydrocephalus", "Arachnoid cyst", "HPE"],
    prognosis: "Depends on etiology and progression.",
    recommendedFollowUp: ["MRI brain", "TORCH/CMV", "Karyotype", "Serial scans"],
    relatedViewIds: ["view-04-transventricular"],
    severity: "major",
    searchableText: "ventriculomegaly brain ventricle",
  },
  {
    id: "alobar-hpe",
    name: "Alobar holoprosencephaly",
    nameRu: "Алобарная голопрозэнцефалия",
    definition: "Failure of forebrain cleavage — single ventricle.",
    ultrasoundFindings: ["Monoventricle", "Absent CSP", "Fused thalami"],
    differentialDiagnosis: ["Semilobar HPE", "Hydranencephaly"],
    prognosis: "Severe neurodevelopmental impairment.",
    recommendedFollowUp: ["Genetics", "Facial survey (midline defects)"],
    relatedViewIds: ["view-04-transventricular", "view-05-transthalamic", "view-06-transcerebellar"],
    severity: "critical",
    searchableText: "holoprosencephaly HPE brain",
  },
  {
    id: "lemon-sign",
    name: "Lemon sign",
    nameRu: "Признак «лимона»",
    definition: "Frontal scalloping of fetal skull — marker of spina bifida.",
    ultrasoundFindings: ["Concave frontal bones on transthalamic/transventricular plane"],
    differentialDiagnosis: ["Normal variant at early GA"],
    prognosis: "Not standalone diagnosis — seek spinal defect.",
    recommendedFollowUp: ["Complete spine protocol", "Amniocentesis if indicated"],
    relatedViewIds: ["view-04-transventricular", "view-05-transthalamic"],
    severity: "moderate",
    searchableText: "lemon sign skull spina bifida marker",
  },
  {
    id: "banana-sign",
    name: "Banana sign",
    nameRu: "Признак «банана» (мозжечок)",
    definition: "Elongated cerebellum wrapping around brainstem — Chiari II marker.",
    ultrasoundFindings: ["Cerebellum curved anteriorly on transcerebellar view"],
    differentialDiagnosis: ["Normal oblique plane"],
    prognosis: "Associated with open neural tube defect until proven otherwise.",
    recommendedFollowUp: ["Spine survey", "Posterior fossa MRI"],
    relatedViewIds: ["view-06-transcerebellar"],
    severity: "moderate",
    searchableText: "banana sign cerebellum chiari",
  },
  {
    id: "dandy-walker",
    name: "Dandy-Walker spectrum",
    nameRu: "Спектр Dandy-Walker",
    definition: "Posterior fossa malformation with cystic 4th ventricle.",
    ultrasoundFindings: ["Cyst communicating with 4th ventricle", "Vermis hypoplasia/absence", "Enlarged cisterna magna"],
    differentialDiagnosis: ["Blake pouch cyst", "Mega cisterna magna"],
    prognosis: "Variable; syndromic forms worse.",
    recommendedFollowUp: ["MRI", "Genetics", "Cardiac survey"],
    relatedViewIds: ["view-06-transcerebellar"],
    severity: "major",
    searchableText: "dandy walker posterior fossa",
  },
  {
    id: "av-canal",
    name: "Atrioventricular canal defect",
    nameRu: "AV-канал",
    definition: "Defect of atrioventricular septum with common AV valve.",
    ultrasoundFindings: ["Loss of normal 4-chamber symmetry", "Common AV junction", "Offset valves"],
    differentialDiagnosis: ["Large VSD", "Single ventricle"],
    prognosis: "Surgical repair required; Down syndrome association.",
    recommendedFollowUp: ["Fetal echocardiography", "Karyotype"],
    relatedViewIds: ["view-07a-apical-four-chamber", "view-07b-lateral-four-chamber"],
    severity: "major",
    searchableText: "AV canal heart septal",
  },
  {
    id: "coarctation-aorta",
    name: "Coarctation of aorta",
    nameRu: "Коарктация аорты",
    definition: "Narrowing of aortic isthmus.",
    ultrasoundFindings: ["Narrow isthmus", "Reverse arch flow", "Ventricular asymmetry"],
    differentialDiagnosis: ["Interrupted arch", "Hypoplastic arch"],
    prognosis: "Surgical/interventional repair.",
    recommendedFollowUp: ["Detailed fetal echo", "Postnatal echo"],
    relatedViewIds: ["view-07a-apical-four-chamber", "view-10-three-vessel-trachea"],
    severity: "major",
    searchableText: "coarctation aorta heart",
  },
  {
    id: "tga",
    name: "Transposition of great arteries",
    nameRu: "Транспозиция магистральных сосудов",
    definition: "Aorta arises from RV, PA from LV (discordant connections).",
    ultrasoundFindings: ["Parallel great vessels", "Abnormal outflow crossing", "IVS intact often"],
    differentialDiagnosis: ["Double outlet RV", "TAPVR"],
    prognosis: "Requires arterial switch or palliation.",
    recommendedFollowUp: ["Fetal echo specialist", "Delivery at cardiac center"],
    relatedViewIds: ["view-08-lvot", "view-09-rvot", "view-09b-crossing-outflow", "view-10-three-vessel-trachea"],
    severity: "critical",
    searchableText: "TGA transposition great arteries",
  },
  {
    id: "single-umbilical-artery",
    name: "Single umbilical artery",
    nameRu: "Единственная пупочная артерия (ЕАП)",
    definition: "Only one umbilical artery instead of two.",
    ultrasoundFindings: ["One artery lateral to bladder on color", "Two-vessel cord"],
    differentialDiagnosis: ["Missed second artery on poor plane"],
    prognosis: "Increased risk chromosomal/cardiac anomalies if isolated need workup.",
    recommendedFollowUp: ["Detailed anatomy", "Growth surveillance"],
    relatedViewIds: ["view-14-bladder-arteries"],
    severity: "moderate",
    searchableText: "SUA single umbilical artery",
  },
  {
    id: "gastroschisis",
    name: "Gastroschisis",
    nameRu: "Гастрошизис",
    definition: "Paraumbilical abdominal wall defect with free bowel loops.",
    ultrasoundFindings: ["Bowel outside abdomen", "No membrane", "Normal cord insertion usually"],
    differentialDiagnosis: ["Omphalocele", "Physiological hernia early GA"],
    prognosis: "Good with surgical repair; bowel matting risk.",
    recommendedFollowUp: ["Serial bowel assessment", "Delivery planning"],
    relatedViewIds: ["view-12-cord-insertion"],
    severity: "major",
    searchableText: "gastroschisis abdominal wall",
  },
  {
    id: "omphalocele",
    name: "Omphalocele",
    nameRu: "Омфалоцеле",
    definition: "Midline abdominal wall defect with membrane-covered herniation.",
    ultrasoundFindings: ["Membranous sac at cord insertion", "Liver/bowel in sac"],
    differentialDiagnosis: ["Gastroschisis", "Physiological midgut hernia"],
    prognosis: "Syndromic forms common — karyotype mandatory.",
    recommendedFollowUp: ["Karyotype", "Cardiac echo", "Genetics"],
    relatedViewIds: ["view-12-cord-insertion"],
    severity: "major",
    searchableText: "omphalocele abdominal",
  },
  {
    id: "cleft-lip-bilateral",
    name: "Cleft lip (bilateral)",
    nameRu: "Двусторонняя расщелина губы",
    definition: "Midline or bilateral failure of lip fusion.",
    ultrasoundFindings: ["Defect through upper lip coronal", "May extend to palate"],
    differentialDiagnosis: ["Shadow artifact", "Unilateral cleft"],
    prognosis: "Surgical repair; syndromic workup.",
    recommendedFollowUp: ["3D face if available", "Genetics", "Feeding plan"],
    relatedViewIds: ["view-18-upper-lip", "view-20-profile"],
    severity: "moderate",
    searchableText: "cleft lip face",
  },
  {
    id: "clubfoot",
    name: "Clubfoot",
    nameRu: "Косолапость",
    definition: "Fixed plantar flexion/inversion of foot.",
    ultrasoundFindings: ["Foot perpendicular to leg axis", "Rigid posture"],
    differentialDiagnosis: ["Positional deformity ( resolves )"],
    prognosis: "Often isolated; treat with casting/surgery.",
    recommendedFollowUp: ["Musculoskeletal survey", "Genetics if syndromic features"],
    relatedViewIds: ["view-16-lower-limbs"],
    severity: "moderate",
    searchableText: "clubfoot talipes foot",
  },
  {
    id: "skeletal-dysplasia",
    name: "Skeletal dysplasia",
    nameRu: "Скелетная дисплазия",
    definition: "Group of disorders affecting bone growth and shape.",
    ultrasoundFindings: ["Short long bones", "Abnormal skull shape", "Thoracic narrow"],
    differentialDiagnosis: ["Constitutional short femur", "IUGR"],
    prognosis: "Lethal vs non-lethal subtypes — molecular diagnosis key.",
    recommendedFollowUp: ["Biometry all limbs", "Genetics", "Pulmonary hypoplasia assessment"],
    relatedViewIds: ["view-15-femur", "view-16-lower-limbs", "view-17-upper-limbs"],
    severity: "major",
    searchableText: "skeletal dysplasia limbs femur",
  },
  {
    id: "luto",
    name: "Lower urinary tract obstruction",
    nameRu: "Обструкция нижних мочевыводящих путей (LUTO)",
    definition: "Obstruction causing bladder distension and oligohydramnios risk.",
    ultrasoundFindings: ["Megacystis", "Keyhole bladder", "Oligohydramnios progression"],
    differentialDiagnosis: ["Normal full bladder", "Posterior urethral valves"],
    prognosis: "Depends on severity and lung development.",
    recommendedFollowUp: ["Serial bladder/kidneys", "Vesicoamniotic shunt discussion"],
    relatedViewIds: ["view-14-bladder-arteries", "view-03-trunk-coronal"],
    severity: "major",
    searchableText: "LUTO bladder obstruction",
  },
  {
    id: "bilateral-renal-agenesis",
    name: "Bilateral renal agenesis",
    nameRu: "Двусторонняя агенезия почек",
    definition: "Absence of both kidneys.",
    ultrasoundFindings: ["Empty renal fossae", "Absent bladder", "Oligohydramnios", "Flat adrenal glands"],
    differentialDiagnosis: ["Severe MCDK bilateral", "Empty pelvis from other cause"],
    prognosis: "Incompatible with postnatal survival (Potter sequence).",
    recommendedFollowUp: ["Confirm with expert scan", "Genetic counseling"],
    relatedViewIds: ["view-13-kidneys", "view-14-bladder-arteries", "view-03-trunk-coronal"],
    severity: "critical",
    searchableText: "renal agenesis kidney bilateral",
  },
  {
    id: "hydronephrosis",
    name: "Hydronephrosis",
    nameRu: "Гидронефроз / дилатация ЧЛК",
    definition: "Dilation of renal pelvis/calyces.",
    ultrasoundFindings: ["Pelvis AP increased", "Calyceal dilation if severe"],
    differentialDiagnosis: ["Transient physiologic", "UVJ obstruction", "VUR"],
    prognosis: "Often resolves; severe needs urology follow-up.",
    recommendedFollowUp: ["Serial pelvis measurements", "Postnatal ultrasound"],
    relatedViewIds: ["view-13-kidneys"],
    severity: "moderate",
    searchableText: "hydronephrosis kidney pelvis",
  },
  {
    id: "situs-inversus",
    name: "Situs inversus",
    nameRu: "Situs inversus",
    definition: "Mirror-image organ arrangement.",
    ultrasoundFindings: ["Stomach right", "Heart axis reversed", "Aorta right-sided"],
    differentialDiagnosis: ["Situs ambiguous", "Normal variant isolated stomach"],
    prognosis: "Often benign if isolated; check heterotaxy.",
    recommendedFollowUp: ["Cardiac echo", "Polysplenia/asplenia workup if suspected"],
    relatedViewIds: ["view-03-trunk-coronal", "view-11-umbilical-vein"],
    severity: "moderate",
    searchableText: "situs inversus heterotaxy",
  },
  {
    id: "micrognathia",
    name: "Micrognathia",
    nameRu: "Микрогнатия",
    definition: "Small mandible on profile view.",
    ultrasoundFindings: ["Receding chin on sagittal profile", "May impede swallowing"],
    differentialDiagnosis: ["Off-angle profile"],
    prognosis: "Syndromic association common (Pierre Robin).",
    recommendedFollowUp: ["Genetics", "Airway planning at delivery"],
    relatedViewIds: ["view-20-profile"],
    severity: "moderate",
    searchableText: "micrognathia profile jaw",
  },
];

/** Полная searchable база — 65 ВПР по протоколу Емельяненко. */
export const FETAL_ANATOMY_ANOMALIES: FetalAnomalyRecord[] = [
  ...FETAL_ANATOMY_ANOMALIES_CORE,
  ...FETAL_ANATOMY_ANOMALIES_EXTRA,
];

export const FETAL_ANATOMY_ANOMALY_COUNT = FETAL_ANATOMY_ANOMALIES.length;

export function searchAnomalies(query: string): FetalAnomalyRecord[] {
  const q = query.trim().toLowerCase();
  if (!q) return FETAL_ANATOMY_ANOMALIES;
  return FETAL_ANATOMY_ANOMALIES.filter((a) => {
    const hay = `${a.name} ${a.nameRu} ${a.definition} ${a.searchableText}`.toLowerCase();
    return hay.includes(q);
  });
}

export function getAnomaly(id: string): FetalAnomalyRecord | undefined {
  return FETAL_ANATOMY_ANOMALIES.find((a) => a.id === id);
}

export function anomaliesForView(viewId: string): FetalAnomalyRecord[] {
  return FETAL_ANATOMY_ANOMALIES.filter((a) => a.relatedViewIds.includes(viewId as never));
}
