import type { FetalAnatomyCase } from "./types";

export const FETAL_ANATOMY_CASES: FetalAnatomyCase[] = [
  {
    id: "case-b01-lemon-banana",
    level: "beginner",
    title: "Lemon + banana · spina bifida workup",
    history: "18+3, routine II trimester scan. No prior anomalies.",
    ultrasoundFindings: [
      "Transventricular: frontal scalloping (lemon sign).",
      "Transcerebellar: curved cerebellum (banana sign).",
      "Spine sagittal: skin-covered line interrupted at L3.",
    ],
    relatedViewIds: ["view-04-transventricular", "view-06-transcerebellar", "view-01-spine-sagittal"],
    diagnosis: "Open spina bifida spectrum — complete 22-view protocol and genetics.",
    teachingPoints: ["Brain signs prompt spine views 1–2 and overview-2.", "Do not stop at brain only."],
  },
  {
    id: "case-b02-three-vessel",
    level: "beginner",
    title: "3VT · arch arrangement",
    history: "19+1, cardiac views requested after family history of CHD.",
    ultrasoundFindings: [
      "4CV symmetric.",
      "3VT: PA left, aorta center, SVC right — normal arrangement.",
      "Trachea air column posterior.",
    ],
    relatedViewIds: ["view-07a-apical-four-chamber", "view-10-three-vessel-trachea"],
    diagnosis: "Normal 3VT — document for protocol completeness.",
    teachingPoints: ["View 10 mandatory even if 4CV normal.", "Save cine loop for audit."],
  },
  {
    id: "case-b03-bladder-arteries",
    level: "beginner",
    title: "View 14 · bladder + 2 arteries",
    history: "20+0, systematic survey.",
    ultrasoundFindings: ["Filled bladder.", "Color: two arteries lateral, vein central."],
    relatedViewIds: ["view-14-bladder-arteries"],
    diagnosis: "Normal 3-vessel cord at pelvis level.",
    teachingPoints: ["Empty bladder — rescan in 30 min.", "Iliac vessels ≠ umbilical arteries."],
  },
  {
    id: "case-i01-vsd-lvot",
    level: "intermediate",
    title: "VSD + outflow alignment",
    history: "21+2, referred for echogenic focus and family CHD.",
    ultrasoundFindings: [
      "4CV: small muscular VSD.",
      "LVOT: continuous but turbulent.",
      "RVOT: normal PA size.",
    ],
    relatedViewIds: ["view-07a-apical-four-chamber", "view-08-lvot", "view-09-rvot"],
    diagnosis: "Isolated VSD — moderate; fetal echo follow-up.",
    teachingPoints: ["Always pair 4CV with LVOT/RVOT (views 8–9).", "Document VSD location/size."],
  },
  {
    id: "case-i02-omphalocele",
    level: "intermediate",
    title: "Omphalocele vs physiological hernia",
    history: "17+5, abdominal wall question.",
    ultrasoundFindings: [
      "Membranous sac at cord insertion.",
      "Liver edge in sac.",
      "No free loops outside membrane.",
    ],
    relatedViewIds: ["view-12-cord-insertion", "view-11-umbilical-vein"],
    diagnosis: "Omphalocele — karyotype and cardiac survey.",
    teachingPoints: ["Before 14 weeks physiological hernia possible.", "Membrane = omphalocele clue."],
  },
  {
    id: "case-i03-hydronephrosis",
    level: "intermediate",
    title: "Bilateral pelvis dilation",
    history: "22+0, routine anatomy.",
    ultrasoundFindings: [
      "Right pelvis 6 mm, left 5 mm.",
      "Bladder present, normal cord vessels.",
      "No oligohydramnios yet.",
    ],
    relatedViewIds: ["view-13-kidneys", "view-14-bladder-arteries"],
    diagnosis: "Bilateral hydronephrosis — urology pathway, serial scans.",
    teachingPoints: ["Measure each kidney separately (13a/b).", "Track amniotic fluid volume."],
  },
  {
    id: "case-a01-tga-outflow",
    level: "advanced",
    title: "Parallel outflows · TGA suspicion",
    history: "20+4, abnormal outflow crossing on screening.",
    ultrasoundFindings: [
      "4CV: intact septum.",
      "9b: parallel great vessels, no normal crossing.",
      "3VT: abnormal vessel arrangement.",
    ],
    relatedViewIds: ["view-09b-crossing-outflow", "view-10-three-vessel-trachea", "view-07a-apical-four-chamber"],
    diagnosis: "Suspicion TGA — level III fetal echo, delivery at cardiac center.",
    teachingPoints: ["TGA can have 'normal' 4CV.", "Views 9b and 10 are decisive."],
  },
  {
    id: "case-a02-bra",
    level: "advanced",
    title: "Bilateral renal agenesis · Potter",
    history: "19+6, oligohydramnios, empty renal fossae.",
    ultrasoundFindings: [
      "No kidneys on views 13a/b.",
      "Bladder absent on view 14.",
      "Flat adrenals, chest hypoplasia risk.",
    ],
    relatedViewIds: ["view-13-kidneys", "view-14-bladder-arteries", "view-03-trunk-coronal"],
    diagnosis: "Bilateral renal agenesis — confirm expert, counseling.",
    teachingPoints: ["Always obtain kidneys AND bladder in same session.", "Overview-1 documents IUFD risk if missed early."],
  },
  {
    id: "case-a03-overview2-spine",
    level: "advanced",
    title: "Overview-2 catches missed spine defect",
    history: "18+1, fast protocol — initial spine views 'normal'.",
    ultrasoundFindings: [
      "Overview-2 transverse sweep: defect at upper lumbar level.",
      "Repeat sagittal confirms open defect.",
    ],
    relatedViewIds: ["overview-2", "view-01-spine-sagittal"],
    diagnosis: "Open spina bifida — found on movement scan 2.",
    teachingPoints: ["Never skip overview-2.", "Vertebra-by-vertebra documentation."],
  },
  {
    id: "case-b04-csp",
    level: "beginner",
    title: "Absent CSP · ACC workup",
    history: "19+2, transthalamic plane reviewed.",
    ultrasoundFindings: [
      "Transthalamic: CSP not visualized after repeat.",
      "Transventricular: parallel lateral ventricles, colpocephaly hint.",
      "Profile and face otherwise unremarkable.",
    ],
    relatedViewIds: ["view-05-transthalamic", "view-04-transventricular"],
    diagnosis: "Suspicion agenesis of corpus callosum — fetal MRI and genetics.",
    teachingPoints: ["Repeat CSP on true transthalamic plane.", "ACC ≠ HPE if thalami separated."],
  },
  {
    id: "case-b05-gastroschisis",
    level: "beginner",
    title: "Gastroschisis · free loops",
    history: "20+1, paraumbilical defect on cord insertion view.",
    ultrasoundFindings: [
      "View 12: bowel loops outside abdomen, no membrane.",
      "Cord insertion lateral to defect.",
      "Stomach bubble intrabdominal.",
    ],
    relatedViewIds: ["view-12-cord-insertion", "view-11-umbilical-vein"],
    diagnosis: "Gastroschisis — surgical repair expected; karyotype usually normal.",
    teachingPoints: ["No membrane distinguishes from omphalocele.", "Document bowel dilation/matting serially."],
  },
  {
    id: "case-b06-clubfoot",
    level: "beginner",
    title: "Bilateral clubfoot",
    history: "21+0, limb survey.",
    ultrasoundFindings: [
      "View 16: both feet plantar flexed and inverted.",
      "Three bones each leg present.",
      "Femur length normal for GA.",
    ],
    relatedViewIds: ["view-16-lower-limbs", "view-15-femur"],
    diagnosis: "Bilateral talipes equinovarus — isolated likely; MSK survey complete.",
    teachingPoints: ["Distinguish positional vs fixed clubfoot.", "Check spine if neuromuscular concern."],
  },
  {
    id: "case-i04-dandy-walker",
    level: "intermediate",
    title: "Dandy-Walker spectrum",
    history: "22+1, posterior fossa referred.",
    ultrasoundFindings: [
      "Transcerebellar: cystic 4th ventricle communicating with cisterna magna.",
      "Vermis hypoplastic.",
      "No banana sign.",
    ],
    relatedViewIds: ["view-06-transcerebellar"],
    diagnosis: "Dandy-Walker spectrum — MRI, genetics, cardiac survey.",
    teachingPoints: ["Measure cisterna magna and vermis.", "DDx: Blake pouch vs true DWM."],
  },
  {
    id: "case-i05-cdh",
    level: "intermediate",
    title: "Left diaphragmatic hernia",
    history: "18+6, stomach not in usual left abdomen.",
    ultrasoundFindings: [
      "Coronal trunk: stomach in left chest.",
      "Heart axis shifted.",
      "Abdominal circumference small.",
    ],
    relatedViewIds: ["view-03-trunk-coronal", "view-07a-apical-four-chamber"],
    diagnosis: "Left CDH — LHR assessment, delivery at ECMO-capable center.",
    teachingPoints: ["View 3 trunk catches situs and CDH.", "Document lung size and liver herniation."],
  },
  {
    id: "case-i06-sua",
    level: "intermediate",
    title: "Single umbilical artery",
    history: "19+4, color at pelvis.",
    ultrasoundFindings: [
      "View 14: one artery lateral to bladder on color.",
      "Two-vessel cord at cross-section.",
      "Kidneys present bilaterally.",
    ],
    relatedViewIds: ["view-14-bladder-arteries", "view-13-kidneys"],
    diagnosis: "SUA — extended anatomy and growth surveillance per protocol.",
    teachingPoints: ["Confirm with two separate scans if possible.", "Not SUA if bladder empty."],
  },
  {
    id: "case-a04-hlhs-3vt",
    level: "advanced",
    title: "HLHS · small aortic arch",
    history: "20+2, asymmetric 4CV.",
    ultrasoundFindings: [
      "4CV: small LV, small aortic root.",
      "LVOT narrow.",
      "3VT: tiny ascending aorta, normal PA size.",
    ],
    relatedViewIds: ["view-07a-apical-four-chamber", "view-08-lvot", "view-10-three-vessel-trachea"],
    diagnosis: "Hypoplastic left heart syndrome — staged palliation counseling.",
    teachingPoints: ["4CV asymmetry triggers full sequence 8–10.", "3VT confirms small aorta."],
  },
  {
    id: "case-a05-hpe-face",
    level: "advanced",
    title: "Holoprosencephaly · midline face",
    history: "17+5, abnormal brain on screening.",
    ultrasoundFindings: [
      "Transventricular: monoventricle.",
      "Transthalamic: fused thalami, absent CSP.",
      "Profile: micrognathia; orbits hypoteloric.",
    ],
    relatedViewIds: ["view-04-transventricular", "view-05-transthalamic", "view-19-orbits", "view-20-profile"],
    diagnosis: "Alobar holoprosencephaly — genetics, poor neuroprognosis counseling.",
    teachingPoints: ["Brain + face correlation.", "Hypotelorism supports HPE spectrum."],
  },
  {
    id: "case-a06-luto",
    level: "advanced",
    title: "LUTO · megacystis",
    history: "16+2, enlarged bladder, normal amniotic fluid for now.",
    ultrasoundFindings: [
      "View 14: megacystis, two arteries present.",
      "Kidneys with mild pelvis dilation.",
      "No oligohydramnios yet.",
    ],
    relatedViewIds: ["view-14-bladder-arteries", "view-13-kidneys"],
    diagnosis: "Lower urinary tract obstruction — serial bladder/kidneys, discuss shunt vs expectant.",
    teachingPoints: ["Differentiate full bladder vs LUTO.", "Track lung development and AFI."],
  },
];

export function casesByLevel(level: FetalAnatomyCase["level"]): FetalAnatomyCase[] {
  return FETAL_ANATOMY_CASES.filter((c) => c.level === level);
}
