import type { QuizBank } from "@/lib/education/quiz-bank-types";

export const FETAL_ANATOMY_QUIZ_BANK: QuizBank = {
  topic: "22 Ultrasound Views · 65 Fetal Anomalies",
  version: "1.0.0",
  lastReviewed: "2026-06-20",
  sources: [
    {
      id: "emelyanenko",
      title: "Е.С. Емельяненко — 22 среза II триместра",
      year: 2026,
    },
    { id: "isuog", title: "ISUOG second trimester anatomy guidelines", year: 2024 },
  ],
  questions: [
    {
      id: "fa-q01",
      category: "protocol",
      level: "student",
      question: "Сколько стандартных срезов в протоколе Емельяненко (без обзоров)?",
      options: ["12", "18", "20", "22"],
      correctIndex: 3,
      explanation: "22 views including overviews and sub-views (7a/b, 9b, 13a/b, etc.).",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q02",
      category: "spine",
      level: "doctor",
      question: "Lemon sign чаще ассоциирован с:",
      options: ["Gastroschisis", "Open spina bifida", "Omphalocele", "Clubfoot"],
      correctIndex: 1,
      explanation: "Frontal skull scalloping — marker для spina bifida (views 4–5).",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q03",
      category: "brain",
      level: "student",
      question: "Banana sign оценивают на срезе:",
      options: ["Transventricular", "Transthalamic", "Transcerebellar", "Profile"],
      correctIndex: 2,
      explanation: "View 6 — transcerebellar plane.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q04",
      category: "heart",
      level: "doctor",
      question: "3VT (view 10) обязателен для исключения:",
      options: ["Clubfoot only", "Arch anomalies and vessel arrangement", "Cleft lip", "Femur length"],
      correctIndex: 1,
      explanation: "3VT — interrupted arch, RAA, persistent LSV, TGA clues.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q05",
      category: "pelvis",
      level: "student",
      question: "View 14 требует в кадре:",
      options: ["Only bladder", "Bladder + two umbilical arteries", "Femur", "CSP"],
      correctIndex: 1,
      explanation: "Мочевой пузырь и 2 артерии пуповины — SUA/LUTO/BRA screening.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q06",
      category: "abdomen",
      level: "doctor",
      question: "Omphalocele vs gastroschisis — верно:",
      options: [
        "Gastroschisis has membrane",
        "Omphalocele midline with membrane often",
        "Both always without membrane",
        "Only view 15 distinguishes",
      ],
      correctIndex: 1,
      explanation: "Omphalocele — midline + membrane; gastroschisis — free loops, no membrane.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q07",
      category: "limbs",
      level: "student",
      question: "Femur length (view 15) используют для подозрения на:",
      options: ["Cataract", "Skeletal dysplasia", "TGA", "CSP absence"],
      correctIndex: 1,
      explanation: "Short femur → skeletal dysplasia / achondroplasia workup.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q08",
      category: "face",
      level: "doctor",
      question: "Cleft lip screening — primary view:",
      options: ["View 18 coronal upper lip", "View 15 femur", "View 11 UV", "View 2 spine"],
      correctIndex: 0,
      explanation: "View 18 — upper lip, nostrils, nose tip coronal.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q09",
      category: "overview",
      level: "student",
      question: "Overview-2 (movement scan 2) — цель:",
      options: [
        "Only heart",
        "Transverse sweep neck to sacrum, vertebra by vertebra",
        "Replace all other views",
        "Measure NT",
      ],
      correctIndex: 1,
      explanation: "Systematic body survey — catch spine defects missed elsewhere.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q10",
      category: "heart",
      level: "doctor",
      question: "TGA may have normal:",
      options: ["4-chamber view only", "Femur", "Profile", "Kidneys only"],
      correctIndex: 0,
      explanation: "4CV can look normal — need outflow crossing (9b) and 3VT.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q11",
      category: "brain",
      level: "doctor",
      question: "Absent CSP на transthalamic plane требует:",
      options: [
        "Только повтор через неделю",
        "ACC/HPE workup + MRI discussion",
        "Измерения femur",
        "Только view 14",
      ],
      correctIndex: 1,
      explanation: "Absent CSP — маркер ACC или HPE; views 4–6 + genetics/MRI.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q12",
      category: "spine",
      level: "student",
      question: "Срез 1 (сагиттальный позвоночник) оценивает:",
      options: [
        "Только femur",
        "Непрерывную кожу и тела позвонков",
        "Только orbits",
        "Только 3VT",
      ],
      correctIndex: 1,
      explanation: "View 1 — intact skin line, vertebral bodies, lordosis.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q13",
      category: "abdomen",
      level: "doctor",
      question: "Double bubble sign связан с:",
      options: ["Duodenal atresia", "Clubfoot", "TGA", "Anophthalmia"],
      correctIndex: 0,
      explanation: "Stomach + proximal duodenum — view 11 abdomen.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q14",
      category: "heart",
      level: "doctor",
      question: "Interrupted aortic arch часто ассоциирован с:",
      options: ["22q11 deletion", "Achondroplasia only", "Cleft lip only", "SCT"],
      correctIndex: 0,
      explanation: "3VT — marker for IAA and 22q11; expert echo mandatory.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q15",
      category: "pelvis",
      level: "student",
      question: "Persistent absent bladder + absent kidneys suggests:",
      options: ["Normal variant", "Bilateral renal agenesis", "Clubfoot", "Cataract"],
      correctIndex: 1,
      explanation: "BRA — empty fossae, no bladder, oligohydramnios (Potter).",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q16",
      category: "face",
      level: "doctor",
      question: "Hypotelorism чаще ассоциирован с:",
      options: ["Holoprosencephaly spectrum", "Isolated gastroschisis", "Normal femur", "SUA only"],
      correctIndex: 0,
      explanation: "View 19 orbits — midline brain malformation marker.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q17",
      category: "overview",
      level: "doctor",
      question: "Overview-1 (движение 1) исключает в первую очередь:",
      options: ["Anencephaly and IUFD", "Only clubfoot", "Only cataract", "Only SUA"],
      correctIndex: 0,
      explanation: "Longitudinal head/body — gross viability and major cranial defects.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q18",
      category: "heart",
      level: "student",
      question: "Сколько four-chamber views в протоколе?",
      options: ["One (7a only)", "Two (7a and 7b)", "None", "Four"],
      correctIndex: 1,
      explanation: "Apical 7a + lateral 7b — both required.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q19",
      category: "abdomen",
      level: "student",
      question: "View 13 требует:",
      options: [
        "Only one kidney",
        "Left and right kidney with renal pelvis",
        "Only profile",
        "Only spine sagittal",
      ],
      correctIndex: 1,
      explanation: "13a/b — bilateral kidneys and pelvis for MCDK, ARPKD, hydronephrosis.",
      sourceId: "emelyanenko",
    },
    {
      id: "fa-q20",
      category: "protocol",
      level: "doctor",
      question: "При lemon sign правильный следующий шаг:",
      options: [
        "Stop scan — brain only",
        "Complete spine views 1–2 and overview-2",
        "Skip heart",
        "Only measure FL",
      ],
      correctIndex: 1,
      explanation: "Lemon is marker — mandatory spine protocol, not standalone diagnosis.",
      sourceId: "emelyanenko",
    },
  ],
};

export const FETAL_ANATOMY_ORAL_QUESTIONS = [
  "Перечислите 22 среза по группам (spine, brain, heart, abdomen, pelvis, limbs, face).",
  "Как отличить omphalocele от gastroschisis на views 11–12?",
  "Зачем нужны и 7a, и 7b four-chamber?",
  "Опишите алгоритм при lemon sign на view 4.",
  "Как документировать SUA на view 14?",
] as const;
