import { FETAL_ANATOMY_IMAGE_BASE } from "./constants";
import type { FetalAnatomyView, FetalAnatomyViewId } from "./types";

function atlas(viewId: string, kind: "normal" | "pathology"): string {
  return `${FETAL_ANATOMY_IMAGE_BASE}/${viewId}_${kind}.png`;
}

export const FETAL_ANATOMY_VIEWS: FetalAnatomyView[] = [
  {
    id: "overview-1",
    number: "Обзор 1",
    region: "overview",
    title: "Longitudinal head and body",
    titleRu: "Сагиттальный обзор головы и тела",
    plane: "Longitudinal · head + trunk",
    probeOrientation: "Mid-sagittal, neutral tilt",
    howToObtain: [
      "Начать с сагиттального среза от макушки до таза для ориентации.",
      "Убедиться, что видны контуры головы, позвоночник, живот, конечности.",
      "Зафиксировать жизнеспособность и базовую симметрию.",
    ],
    normalAnatomy: ["Целостный контур плода", "Симметричное тело", "Активные движения"],
    keyLandmarks: ["Головной контур", "Позвоночник", "Живот", "Конечности"],
    commonMistakes: ["Слишком узкий sector — пропуск gross-аномалий", "Пропуск IUFD без ЧСС/движений"],
    clinicalSignificance: "Первичная ориентация перед систематическим проходом 22 срезов.",
    excludesAnomalyIds: ["anencephaly", "iufd"],
    atlasNormal: atlas("overview-1", "normal"),
    atlasPathology: atlas("overview-1", "pathology"),
  },
  {
    id: "view-01-spine-sagittal",
    number: 1,
    region: "spine",
    title: "Sagittal spine · skin-covered",
    titleRu: "Позвоночник · сагиттальный · кожа intact",
    plane: "Sagittal spine",
    probeOrientation: "Parallel to fetal spine",
    howToObtain: [
      "Сагиттальный срез вдоль позвоночника.",
      "Кожа над позвонком должна быть видна непрерывно.",
      "Оценить lordosis, continuity тел позвонков.",
    ],
    normalAnatomy: ["Непрерывная линия тел и дуг", "Intact skin line", "Normal curvature"],
    keyLandmarks: ["Vertebral bodies", "Spinal canal", "Skin covering"],
    commonMistakes: ["Oblique plane mimicking defect", "Confusing rib shadow with spine"],
    clinicalSignificance: "Скрининг spina bifida aperta/oculta, meningocele, sacral agenesis.",
    excludesAnomalyIds: ["meningocele", "spina-bifida-open", "sacral-agenesis", "sct"],
    atlasNormal: atlas("view-01-spine-sagittal", "normal"),
    atlasPathology: atlas("view-01-spine-sagittal", "pathology"),
  },
  {
    id: "view-02-spine-coronal",
    number: 2,
    region: "spine",
    title: "Coronal spine",
    titleRu: "Позвоночник · коронарный",
    plane: "Coronal spine",
    probeOrientation: "Perpendicular to spine axis",
    howToObtain: ["Коронарный срез через позвоночник.", "Симметрия pedicles и laminae."],
    normalAnatomy: ["Symmetric neural arches", "Intact posterior elements"],
    keyLandmarks: ["Pedicles", "Laminae", "Spinous processes"],
    commonMistakes: ["Off-axis coronal → false asymmetry"],
    clinicalSignificance: "Дополнение к сагиттали для открытой spina bifida.",
    excludesAnomalyIds: ["spina-bifida-open", "sacral-agenesis"],
    atlasNormal: atlas("view-02-spine-coronal", "normal"),
    atlasPathology: atlas("view-02-spine-coronal", "pathology"),
  },
  {
    id: "view-03-trunk-coronal",
    number: 3,
    region: "spine",
    title: "Coronal trunk",
    titleRu: "Туловище · коронарный обзор",
    plane: "Coronal trunk",
    probeOrientation: "Through thorax and abdomen",
    howToObtain: [
      "Широкий коронарный срез туловища.",
      "Оценить situs, сердце, кишечник, почки (если видны).",
    ],
    normalAnatomy: ["Situs solitus", "Heart axis ~45°", "Echogenic bowel appropriate GA"],
    keyLandmarks: ["Four-chamber hint", "Stomach bubble", "Kidney poles if visible"],
    commonMistakes: ["Incomplete sweep — missed diaphragmatic hernia"],
    clinicalSignificance: "Мультиорганный скрининг: situs, CAPV axis, echogenic bowel, hernia.",
    excludesAnomalyIds: [
      "situs-inversus",
      "bilateral-renal-agenesis",
      "cardiac-axis-shift",
      "echogenic-bowel",
      "esophageal-atresia",
      "diaphragmatic-hernia-left",
      "luto",
    ],
    atlasNormal: atlas("view-03-trunk-coronal", "normal"),
    atlasPathology: atlas("view-03-trunk-coronal", "pathology"),
  },
  {
    id: "view-04-transventricular",
    number: 4,
    region: "head-brain",
    title: "Transventricular plane",
    titleRu: "Трансвентрикулярный срез",
    plane: "Transventricular",
    probeOrientation: "Axial skull at ventricular level",
    howToObtain: [
      "Axial через боковые ventricles на уровне choroid plexus.",
      "Измерить width lateral ventricles at atrium.",
    ],
    normalAnatomy: ["Symmetric lateral ventricles", "Choroid plexus", "Midline falx"],
    keyLandmarks: ["Lateral ventricles", "Choroid", "CSP if more cephalad"],
    commonMistakes: ["Oblique plane → false ventriculomegaly", "Missing lemon sign context"],
    clinicalSignificance: "Ventriculomegaly, HPE spectrum, anencephaly exclusion upstream.",
    excludesAnomalyIds: [
      "ventriculomegaly",
      "alobar-hpe",
      "anencephaly",
      "lemon-sign",
      "occipital-encephalocele",
      "skeletal-dysplasia",
      "subcutaneous-edema",
    ],
    atlasNormal: atlas("view-04-transventricular", "normal"),
    atlasPathology: atlas("view-04-transventricular", "pathology"),
  },
  {
    id: "view-05-transthalamic",
    number: 5,
    region: "head-brain",
    title: "Transthalamic plane",
    titleRu: "Трансталамический срез",
    plane: "Transthalamic",
    probeOrientation: "Axial through thalami",
    howToObtain: ["Axial на уровне thalami и CSP.", "Thalami symmetric, CSP visible."],
    normalAnatomy: ["CSP present", "Symmetric thalami", "Normal midline"],
    keyLandmarks: ["Cavum septi pellucidi", "Thalami", "Falx"],
    commonMistakes: ["CSP absent — confirm with repeat / higher plane"],
    clinicalSignificance: "CSP — marker for callosal development; HPE screening.",
    excludesAnomalyIds: [
      "ventriculomegaly",
      "alobar-hpe",
      "anencephaly",
      "lemon-sign",
      "occipital-encephalocele",
      "skeletal-dysplasia",
      "subcutaneous-edema",
    ],
    atlasNormal: atlas("view-05-transthalamic", "normal"),
    atlasPathology: atlas("view-05-transthalamic", "pathology"),
  },
  {
    id: "view-06-transcerebellar",
    number: 6,
    region: "head-brain",
    title: "Transcerebellar plane",
    titleRu: "Трансцеребеллярный срез",
    plane: "Transcerebellar",
    probeOrientation: "Axial through cerebellum and cisterna magna",
    howToObtain: [
      "Axial через cerebellum — «dumbbell» or butterfly shape.",
      "Measure cisterna magna, transcerebellar diameter.",
    ],
    normalAnatomy: ["Intact vermis", "Cisterna magna 2–10 mm", "Symmetric hemispheres"],
    keyLandmarks: ["Cerebellum", "Cisterna magna", "NT fold if early"],
    commonMistakes: ["Confusing banana sign with normal obliquity"],
    clinicalSignificance: "Dandy-Walker spectrum, Chiari II marker (banana sign).",
    excludesAnomalyIds: [
      "alobar-hpe",
      "anencephaly",
      "banana-sign",
      "cystic-hygroma",
      "dandy-walker",
      "increased-nuchal-fold",
      "occipital-encephalocele",
      "posterior-fossa-cyst",
      "skeletal-dysplasia",
    ],
    atlasNormal: atlas("view-06-transcerebellar", "normal"),
    atlasPathology: atlas("view-06-transcerebellar", "pathology"),
  },
  {
    id: "view-07a-apical-four-chamber",
    number: "7a",
    region: "heart",
    title: "Apical four-chamber view",
    titleRu: "Апикальный 4-камерный срез",
    plane: "Apical 4CV",
    probeOrientation: "Heart apex toward transducer",
    howToObtain: [
      "True apical 4-chamber — all four chambers, atrioventricular valves.",
      "Assess symmetry, septum, foramen ovale flap.",
    ],
    normalAnatomy: ["Symmetric chambers", "Intact septum", "Normal AV valves"],
    keyLandmarks: ["RA/LA", "RV/LV", "Interventricular septum", "Foramen ovale"],
    commonMistakes: ["Foreshortened apex → missed AV canal", "Confusing moderator band with VSD"],
    clinicalSignificance: "Core cardiac screening view — AV canal, HLHS markers, effusions.",
    excludesAnomalyIds: [
      "av-canal",
      "cardiac-axis-shift",
      "coarctation-aorta",
      "ectopia-cordis",
      "hlhs-left",
      "hypoplastic-right-heart",
      "pericardial-effusion",
      "pleural-effusion",
      "subcutaneous-edema",
      "vsd-moderate",
      "single-ventricle",
    ],
    atlasNormal: atlas("view-07a-apical-four-chamber", "normal"),
    atlasPathology: atlas("view-07a-apical-four-chamber", "pathology"),
  },
  {
    id: "view-07b-lateral-four-chamber",
    number: "7b",
    region: "heart",
    title: "Lateral four-chamber view",
    titleRu: "Латеральный 4-камерный срез",
    plane: "Lateral 4CV",
    probeOrientation: "Slightly rotated from apical 4CV",
    howToObtain: ["Rotate from apical 4CV to lateral four-chamber.", "Better visualize outflow alignment."],
    normalAnatomy: ["Chamber proportions", "Outflow continuity hint"],
    keyLandmarks: ["LV/RV", "Outflow tracts approach"],
    commonMistakes: ["Not obtaining both 7a and 7b in protocol"],
    clinicalSignificance: "Complements apical 4CV for outflow and septal defects.",
    excludesAnomalyIds: ["av-canal", "vsd-moderate", "single-ventricle"],
    atlasNormal: atlas("view-07b-lateral-four-chamber", "normal"),
    atlasPathology: atlas("view-07b-lateral-four-chamber", "pathology"),
  },
  {
    id: "view-08-lvot",
    number: 8,
    region: "heart",
    title: "Left ventricular outflow tract",
    titleRu: "Выходной тракт левого желудочка",
    plane: "LVOT",
    probeOrientation: "From 4CV rotate to visualize LV → aorta",
    howToObtain: ["LVOT: continuous LV cavity into ascending aorta.", "Aortic valve leaflets."],
    normalAnatomy: ["Single aortic arch origin from LV", "No overriding vessel"],
    keyLandmarks: ["Aortic root", "LVOT", "Ascending aorta"],
    commonMistakes: ["Confusing pulmonary artery for aorta"],
    clinicalSignificance: "Aortic stenosis, coarctation, TGA workup.",
    excludesAnomalyIds: ["aortic-stenosis", "aorta-as-rider", "tga", "vsd-moderate"],
    atlasNormal: atlas("view-08-lvot", "normal"),
    atlasPathology: atlas("view-08-lvot", "pathology"),
  },
  {
    id: "view-09-rvot",
    number: 9,
    region: "heart",
    title: "Right ventricular outflow tract",
    titleRu: "Выходной тракт правого желудочка",
    plane: "RVOT",
    probeOrientation: "RV → pulmonary artery",
    howToObtain: ["RVOT: pulmonary valve and main pulmonary artery.", "Branch toward left/right PA."],
    normalAnatomy: ["Pulmonary valve mobile", "Main PA centered"],
    keyLandmarks: ["Pulmonary valve", "Main PA", "Ductal arch if visible"],
    commonMistakes: ["Missing pulmonary atresia when 4CV looks 'normal'"],
    clinicalSignificance: "Pulmonary atresia/stenosis, TGA differential.",
    excludesAnomalyIds: ["pulmonary-atresia", "pulmonary-stenosis-severe", "tga"],
    atlasNormal: atlas("view-09-rvot", "normal"),
    atlasPathology: atlas("view-09-rvot", "pathology"),
  },
  {
    id: "view-09b-crossing-outflow",
    number: "9b",
    region: "heart",
    title: "Crossing outflow tracts",
    titleRu: "Перекрёст выходных трактов",
    plane: "Outflow crossing",
    probeOrientation: "Both outflows in one plane",
    howToObtain: ["Demonstrate crossing/normal relationship of LVOT and RVOT.", "Document side-by-side vs parallel."],
    normalAnatomy: ["Great vessels cross appropriately", "No parallel outflows"],
    keyLandmarks: ["LVOT", "RVOT", "Great vessel relationship"],
    commonMistakes: ["Stopping at 4CV without outflow crossing check"],
    clinicalSignificance: "Critical for conotruncal anomalies and TGA.",
    excludesAnomalyIds: ["tga", "tof", "vsd-moderate"],
    atlasNormal: atlas("view-09b-crossing-outflow", "normal"),
    atlasPathology: atlas("view-09b-crossing-outflow", "pathology"),
  },
  {
    id: "view-10-three-vessel-trachea",
    number: 10,
    region: "heart",
    title: "Three vessel trachea view",
    titleRu: "3 сосуда и трахея",
    plane: "3VT",
    probeOrientation: "Axial upper mediastinum",
    howToObtain: [
      "3VT: PA (left), aorta (center/right), SVC — trachea air column posterior.",
      "Assess vessel size and arrangement.",
    ],
    normalAnatomy: ["PA smallest left", "Aorta and SVC right", "Trachea posterior"],
    keyLandmarks: ["Main PA", "Aortic arch", "SVC", "Trachea"],
    commonMistakes: ["Missing right aortic arch or interrupted arch"],
    clinicalSignificance: "Arch anomalies, 22q11 marker, persistent left SVC.",
    excludesAnomalyIds: [
      "aortic-stenosis",
      "coarctation-aorta",
      "hlhs-left",
      "interrupted-aortic-arch",
      "persistent-lsv",
      "right-aortic-arch",
      "pulmonary-atresia",
      "tga",
      "vsd-moderate",
    ],
    atlasNormal: atlas("view-10-three-vessel-trachea", "normal"),
    atlasPathology: atlas("view-10-three-vessel-trachea", "pathology"),
  },
  {
    id: "view-11-umbilical-vein",
    number: 11,
    region: "abdomen",
    title: "Umbilical vein plane",
    titleRu: "Плоскость вены пуповины",
    plane: "Transverse abdomen · UV",
    probeOrientation: "UV entering liver left portal branch",
    howToObtain: ["Transverse abdomen — UV entering portal sinus.", "Stomach left, spine posterior."],
    normalAnatomy: ["UV → left portal", "Stomach bubble", "Normal situs"],
    keyLandmarks: ["Umbilical vein", "Portal sinus", "Stomach"],
    commonMistakes: ["Confusing UV with other venous structures"],
    clinicalSignificance: "Situs, ascites, atresias, spina bifida association.",
    excludesAnomalyIds: [
      "situs-inversus",
      "ascites",
      "duodenal-atresia",
      "esophageal-atresia",
      "spina-bifida-open",
      "subcutaneous-edema",
    ],
    atlasNormal: atlas("view-11-umbilical-vein", "normal"),
    atlasPathology: atlas("view-11-umbilical-vein", "pathology"),
  },
  {
    id: "view-12-cord-insertion",
    number: 12,
    region: "abdomen",
    title: "Umbilical cord insertion",
    titleRu: "Место вхождения пуповины",
    plane: "Cord insertion site",
    probeOrientation: "Transverse at insertion",
    howToObtain: ["Document cord insertion into abdominal wall.", "Three-vessel cord if color used."],
    normalAnatomy: ["Central insertion", "Intact anterior wall"],
    keyLandmarks: ["Cord insertion", "Abdominal wall continuity"],
    commonMistakes: ["Missing gastroschisis paraumbilical defect"],
    clinicalSignificance: "Omphalocele vs gastroschisis, wall defects.",
    excludesAnomalyIds: ["ascites", "gastroschisis", "omphalocele", "spina-bifida-open", "subcutaneous-edema"],
    atlasNormal: atlas("view-12-cord-insertion", "normal"),
    atlasPathology: atlas("view-12-cord-insertion", "pathology"),
  },
  {
    id: "view-13-kidneys",
    number: "13a/b",
    region: "abdomen",
    title: "Kidneys and renal pelvis",
    titleRu: "Почки и лоханки",
    plane: "Transverse kidneys bilateral",
    probeOrientation: "Each kidney long/short axis with pelvis",
    howToObtain: [
      "Obtain left and right kidney with renal pelvis.",
      "Measure AP pelvis if dilated; note cystic vs solid.",
    ],
    normalAnatomy: ["Bilateral kidneys", "Pelvis <4 mm II trimester typical", "Cortex echogenicity normal"],
    keyLandmarks: ["Renal cortex", "Pelvis", "Ureter if visible"],
    commonMistakes: ["Single kidney slice — missing bilateral agenesis"],
    clinicalSignificance: "ARPKD, MCDK, hydronephrosis screening.",
    excludesAnomalyIds: ["arpkd", "mcdk", "hydronephrosis", "bilateral-renal-agenesis"],
    atlasNormal: atlas("view-13-kidneys", "normal"),
    atlasPathology: atlas("view-13-kidneys", "pathology"),
  },
  {
    id: "view-14-bladder-arteries",
    number: 14,
    region: "pelvis",
    title: "Bladder and two umbilical arteries",
    titleRu: "Мочевой пузырь и 2 артерии пуповины",
    plane: "Transverse pelvis",
    probeOrientation: "Bladder center, arteries lateral on color",
    howToObtain: [
      "Transverse pelvis: bladder filled.",
      "Color Doppler — two umbilical arteries lateral to bladder.",
    ],
    normalAnatomy: ["Bladder visible", "2 arteries + 1 vein (3-vessel cord)"],
    keyLandmarks: ["Fetal bladder", "Umbilical arteries", "Cord vessels"],
    commonMistakes: ["Empty bladder — repeat scan", "Confusing iliac for umbilical arteries"],
    clinicalSignificance: "SUA, bilateral renal agenesis, LUTO.",
    excludesAnomalyIds: ["bilateral-renal-agenesis", "luto", "single-umbilical-artery"],
    atlasNormal: atlas("view-14-bladder-arteries", "normal"),
    atlasPathology: atlas("view-14-bladder-arteries", "pathology"),
  },
  {
    id: "view-15-femur",
    number: 15,
    region: "limbs",
    title: "Femur length",
    titleRu: "Длина бедренной кости",
    plane: "Femur longitudinal",
    probeOrientation: "Full diaphysis perpendicular to beam",
    howToObtain: ["Measure femur diaphysis — ossified shaft only.", "Compare to GA charts."],
    normalAnatomy: ["Femur length appropriate GA", "Intact diaphysis"],
    keyLandmarks: ["Femoral diaphysis", "Distal/proximal epiphyses if visible"],
    commonMistakes: ["Foreshortened femur on oblique plane"],
    clinicalSignificance: "Skeletal dysplasia, achondroplasia suspicion.",
    excludesAnomalyIds: ["skeletal-dysplasia", "achondroplasia-suspect", "limb-reduction-transverse"],
    atlasNormal: atlas("view-15-femur", "normal"),
    atlasPathology: atlas("view-15-femur", "pathology"),
  },
  {
    id: "view-16-lower-limbs",
    number: "16a/b",
    region: "limbs",
    title: "Lower limbs",
    titleRu: "Нижние конечности",
    plane: "Three bones leg + foot",
    probeOrientation: "Tibia, fibula, foot relationship",
    howToObtain: ["Three bones of each leg + foot position.", "Document clubfoot if plantar flexion/inversion."],
    normalAnatomy: ["Three segments", "Foot aligned with leg", "Toes present"],
    keyLandmarks: ["Femur-tibia-fibula-foot chain", "Ankle mobility"],
    commonMistakes: ["Not documenting bilateral feet"],
    clinicalSignificance: "Clubfoot, reduction defects, dysplasia.",
    excludesAnomalyIds: ["skeletal-dysplasia", "achondroplasia-suspect", "clubfoot", "limb-reduction-transverse"],
    atlasNormal: atlas("view-16-lower-limbs", "normal"),
    atlasPathology: atlas("view-16-lower-limbs", "pathology"),
  },
  {
    id: "view-17-upper-limbs",
    number: "17a/b",
    region: "limbs",
    title: "Upper limbs",
    titleRu: "Верхние конечности",
    plane: "Arm + hand",
    probeOrientation: "Humerus, radius/ulna, hand",
    howToObtain: ["Three bones each arm + hand flexion/extension.", "Count digits."],
    normalAnatomy: ["Symmetric arms", "Normal hand posture", "Five digits"],
    keyLandmarks: ["Humerus", "Forearm bones", "Hand"],
    commonMistakes: ["Missing unilateral hand anomaly"],
    clinicalSignificance: "Reduction defects, flexion deformities.",
    excludesAnomalyIds: ["skeletal-dysplasia", "limb-reduction-transverse", "hand-flexion-deformity"],
    atlasNormal: atlas("view-17-upper-limbs", "normal"),
    atlasPathology: atlas("view-17-upper-limbs", "pathology"),
  },
  {
    id: "view-18-upper-lip",
    number: 18,
    region: "face",
    title: "Upper lip · nostrils · nose tip",
    titleRu: "Верхняя губа · ноздри · кончик носа",
    plane: "Coronal face",
    probeOrientation: "Coronal through upper lip and nose",
    howToObtain: ["Coronal: intact philtrum, symmetric nostrils.", "No cleft through alveolus."],
    normalAnatomy: ["Intact upper lip", "Symmetric nostrils", "Intact alveolar ridge"],
    keyLandmarks: ["Philtrum", "Nostrils", "Primary palate"],
    commonMistakes: ["Shadow artifact mimicking cleft"],
    clinicalSignificance: "Cleft lip/palate screening.",
    excludesAnomalyIds: ["cleft-lip-unilateral", "cleft-lip-bilateral"],
    atlasNormal: atlas("view-18-upper-lip", "normal"),
    atlasPathology: atlas("view-18-upper-lip", "pathology"),
  },
  {
    id: "view-19-orbits",
    number: 19,
    region: "face",
    title: "Orbits and lenses",
    titleRu: "Орбиты и хрусталики",
    plane: "Transverse orbits",
    probeOrientation: "Both orbits in one plane",
    howToObtain: ["Transverse through both orbits.", "Lens echogenicity symmetric."],
    normalAnatomy: ["Symmetric orbits", "Clear lenses", "Normal interorbital distance"],
    keyLandmarks: ["Lenses", "Orbits", "Hypertelorism/hypotelorism assessment"],
    commonMistakes: ["Single orbit slice — missing anophthalmia"],
    clinicalSignificance: "Hypertelorism, cataract, microphthalmia.",
    excludesAnomalyIds: ["hypertelorism", "hypotelorism", "anophthalmia", "cataract", "microphthalmia"],
    atlasNormal: atlas("view-19-orbits", "normal"),
    atlasPathology: atlas("view-19-orbits", "pathology"),
  },
  {
    id: "view-20-profile",
    number: 20,
    region: "face",
    title: "Sagittal profile",
    titleRu: "Профиль плода",
    plane: "Mid-sagittal face",
    probeOrientation: "Profile: forehead, nose, chin",
    howToObtain: ["True profile — nasal bone, chin, forehead line.", "Assess micrognathia."],
    normalAnatomy: ["Smooth profile", "Nasal bone present", "Normal chin"],
    keyLandmarks: ["Nasal bone", "Mandible", "Forehead"],
    commonMistakes: ["Off-profile → false micrognathia"],
    clinicalSignificance: "Micrognathia, proboscis, cleft association.",
    excludesAnomalyIds: ["depressed-nasal-bridge", "micrognathia", "cleft-lip-bilateral", "proboscis"],
    atlasNormal: atlas("view-20-profile", "normal"),
    atlasPathology: atlas("view-20-profile", "pathology"),
  },
  {
    id: "overview-2",
    number: "Обзор 2 · Движение 2",
    region: "whole-body",
    title: "Systematic body survey neck to sacrum",
    titleRu: "Обзор тела от шеи до крестца",
    plane: "Transverse sweep",
    probeOrientation: "Sequential transverse slices",
    howToObtain: [
      "Transverse sweep entire body neck → sacrum.",
      "Vertebra-by-vertebra spine review.",
      "Document movement and tone.",
    ],
    normalAnatomy: ["Continuous spine skin line", "Symmetric thorax/abdomen", "Active movement"],
    keyLandmarks: ["Each vertebral level", "Rib cage", "Abdominal organs"],
    commonMistakes: ["Skipping overview-2 after checklist fatigue"],
    clinicalSignificance: "Catch spina bifida, sacral agenesis, SCT missed on single views.",
    excludesAnomalyIds: ["spina-bifida-open", "sacral-agenesis", "sct"],
    atlasNormal: atlas("overview-2", "normal"),
    atlasPathology: atlas("overview-2", "pathology"),
  },
];

export function getFetalAnatomyView(id: FetalAnatomyViewId): FetalAnatomyView | undefined {
  return FETAL_ANATOMY_VIEWS.find((v) => v.id === id);
}

export function viewsByRegion(region: FetalAnatomyView["region"]): FetalAnatomyView[] {
  return FETAL_ANATOMY_VIEWS.filter((v) => v.region === region);
}

export const FETAL_ANATOMY_VIEW_COUNT = FETAL_ANATOMY_VIEWS.length;
