import type { QuizBank } from "../quiz-bank-types";

export const EXAM_CHECKLISTS_QUIZ_BANK: QuizBank = {
  topic: "Чек-листы полного УЗИ (AIUM / ISUOG)",
  version: "2026-07",
  lastReviewed: "2026-07-18",
  sources: [
    {
      id: "aium-female-pelvis-2024",
      title: "AIUM Practice Parameter · Female Pelvis",
      year: 2024,
    },
    {
      id: "aium-obstetric-standard-2024",
      title: "AIUM Practice Parameter · Obstetric Standard",
      year: 2024,
    },
    {
      id: "isuog-11-14",
      title: "ISUOG Practice Guidelines · 11–14 week scan",
      year: 2024,
    },
    {
      id: "isuog-3rd-trimester",
      title: "ISUOG Practice Guidelines · III trimester",
      year: 2024,
    },
    {
      id: "radiopaedia-set-pieces",
      title: "Radiopaedia · Gynecological ultrasound set-pieces",
      year: 2025,
    },
    {
      id: "o-rads-us",
      title: "ACR O-RADS US v2022",
      year: 2022,
    },
    {
      id: "isuog-fgr",
      title: "ISUOG · Fetal growth restriction",
      year: 2020,
    },
    {
      id: "isuog-afi",
      title: "ISUOG · Amniotic fluid assessment",
      year: 2024,
    },
    {
      id: "fmf-extended",
      title: "FMF · Extended first trimester protocol",
      year: 2024,
    },
    {
      id: "aium-disclaimer",
      title: "AIUM · Practice Parameters scope",
      year: 2024,
    },
  ],
  questions: [
    {
      id: "ec-q1",
      category: "Gynecology",
      level: "doctor",
      question: "При УЗИ малого таза AIUM рекомендует выполнять:",
      options: [
        "Только трансабдоминально",
        "Только трансвагинально",
        "TA + TV (TV — для детализации при доступности)",
        "Только при острой боли",
      ],
      correctIndex: 2,
      explanation:
        "AIUM Female Pelvis: TA — обязательный компонент; TV — второй этап с более высоким разрешением для эндометрия, шейки и придатков.",
      sourceId: "aium-female-pelvis-2024",
    },
    {
      id: "ec-q2",
      category: "Obstetrics",
      level: "doctor",
      question: "Стандартное акушерское УЗИ (AIUM Obstetric Standard) обязательно включает:",
      options: [
        "Только КТР",
        "Число плодов, предлежание, ЧСС, плацента, AFI, шейка, биометрию",
        "Полную анатомию 22 срезов",
        "Только допплер ПА",
      ],
      correctIndex: 1,
      explanation:
        "Obstetric Standard — базовое исследование для мониторинга; детальная анатомия — отдельный параметр (Detailed 2nd/3rd trimester).",
      sourceId: "aium-obstetric-standard-2024",
    },
    {
      id: "ec-q3",
      category: "Obstetrics",
      level: "student",
      question: "При скрининге 11–13+6 нед ISUOG обязательно измеряют:",
      options: ["Только BPD", "КТР и ТВ (NT)", "Только FL", "Только AFI"],
      correctIndex: 1,
      explanation: "КТР — dating; NT — ключевой маркер комбинированного скрининга I триместра.",
      sourceId: "isuog-11-14",
    },
    {
      id: "ec-q4",
      category: "Obstetrics",
      level: "doctor",
      question: "При FGR в III триместре ISUOG рекомендует оценить:",
      options: [
        "Только ЧСС",
        "Umbilical artery Doppler; MCA и CPR при подозрении на FGR",
        "Только шейку матки",
        "Только плаценту без допплера",
      ],
      correctIndex: 1,
      explanation: "UA Doppler — базовый; MCA и CPR уточняют стадию и прогноз при задержке роста.",
      sourceId: "isuog-3rd-trimester",
    },
    {
      id: "ec-q5",
      category: "Gynecology",
      level: "student",
      question: "«Set-piece» гинекологического УЗИ включает обязательную оценку:",
      options: [
        "Только печени",
        "Матка, миометрий, эндометрий, яичники, жидкость в Douglas",
        "Только щитовидная железа",
        "Только молочные железы",
      ],
      correctIndex: 1,
      explanation: "Структурированный подход (Radiopaedia set-pieces + AIUM Female Pelvis) — систематический отчёт по всем компартментам.",
      sourceId: "radiopaedia-set-pieces",
    },
    {
      id: "ec-q6",
      category: "Obstetrics",
      level: "doctor",
      question: "Absent end-diastolic flow в пупочной артерии при FGR означает:",
      options: [
        "Норму III триместра",
        "Критическое допpler-нарушение — требует срочной оценки и плана родоразрешения",
        "Артефакт без значения",
        "Показание только к повтору через месяц",
      ],
      correctIndex: 1,
      explanation: "AEDF/REDF — маркеры тяжёлой плацентарной недостаточности; ISUOG FGR guidelines.",
      sourceId: "isuog-fgr",
    },
    {
      id: "ec-q7",
      category: "Gynecology",
      level: "doctor",
      question: "При подозрении на злокачественную аднексальную массу AIUM рекомендует:",
      options: [
        "Не использовать допплер",
        "O-RADS / IOTA-дескрипторы + допплер при необходимости",
        "Только TA без TV",
        "Отложить исследование на 6 месяцев",
      ],
      correctIndex: 1,
      explanation: "Структурированная оценка (O-RADS US) + vascularity — стандарт SonoGyn Pro и международных рекомендаций.",
      sourceId: "o-rads-us",
    },
    {
      id: "ec-q8",
      category: "Obstetrics",
      level: "student",
      question: "Олигогидрамнион по ISUOG часто определяют как deepest vertical pocket:",
      options: ["< 2 cm", "> 8 cm", "0 cm всегда норма", "Не измеряют"],
      correctIndex: 0,
      explanation: "DVP < 2 cm — олигогидрамнион; AFI ≤ 5 cm — альтернативный критерий.",
      sourceId: "isuog-afi",
    },
    {
      id: "ec-q9",
      category: "Obstetrics",
      level: "doctor",
      question: "Комбинированный скрининг I триместра включает дополнительно к NT:",
      options: [
        "Только УЗИ без анализов",
        "Ductus venosus, tricuspid flow, uterine artery PI — по протоколу FMF/ISUOG",
        "Только FL",
        "Только шейку матки",
      ],
      correctIndex: 1,
      explanation: "Расширенный протокол FMF: DV, tricuspid, UtA — повышают детекцию при сохранении низкого FPR.",
      sourceId: "fmf-extended",
    },
    {
      id: "ec-q10",
      category: "General",
      level: "student",
      question: "Practice Parameters AIUM предназначены для:",
      options: [
        "Установления юридического стандарта лечения",
        "Минимальных критериев полного исследования и документирования",
        "Замены клинического суждения врача",
        "Рекламы аппаратов",
      ],
      correctIndex: 1,
      explanation: "AIUM явно указывает: parameters — minimum criteria, not legal standard of care.",
      sourceId: "aium-disclaimer",
    },
  ],
};
